### ISSUE TITLE
Flaky test: should set poster and controls in prerender mode

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#10890]
```
FAILED TESTS:
  amp-video
    ● should set poster and controls in prerender mode
      Chrome 60.0.3112 (Linux 0.0.0)
    Error: Failed to load: http://localhost:9876/video.mp4​​​
        at createErrorVargs (/home/travis/build/ampproject/amphtml/src/log.js:490:12 <- /tmp/53702d2e67f792f4d6488a168d07ff41.browserify:144763:13)
        at Log.createError (/home/travis/build/ampproject/amphtml/src/log.js:263:35 <- /tmp/53702d2e67f792f4d6488a168d07ff41.browserify:144524:36)
        at failedToLoad (/home/travis/build/ampproject/amphtml/src/event-helper.js:184:15 <- /tmp/53702d2e67f792f4d6488a168d07ff41.browserify:137179:26)
        at /home/travis/build/ampproject/amphtml/src/event-helper.js:168:4 <- /tmp/53702d2e67f792f4d6488a168d07ff41.browserify:137163:5
        at <anonymous>
```

**Comment by aghassemi** [comment]
Chrome 60 is becoming too fast :) Will send PR soon.

**Comment by aghassemi** [comment]
not fiexed

**Comment by aghassemi** [comment]
never mind, it is fixed.
