### ISSUE TITLE
TypeError: Unable to get property 'obj' of undefined or null reference

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#11185]
stack:

TypeError: Unable to get property 'obj' of undefined or null reference
   at Pb (https://cdn.ampproject.org/v0/amp-login-done-0.1.js:41:734)
   at Ob (https://cdn.ampproject.org/v0/amp-login-done-0.1.js:41:514)
   at xc (https://cdn.ampproject.org/v0/amp-login-done-0.1.js:45:5)
   at Gc (https://cdn.ampproject.org/v0/amp-login-done-0.1.js:45:980)
   at Anonymous function (https://cdn.ampproject.org/v0/amp-login-done-0.1.js:58:75)

url:  "https://cdn.ampproject.org/v0/amp-login-done-0.1.html?url=https%3A%2F%2Fwww.wsj.com%2Famp%2Farticles%2Fthe-costs-of-workplace-rudeness-1503061187"     

http_user_agent:  "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"

**Comment by erwinmombay** [comment]
@dvoytenko can you assess priority?

**Comment by dvoytenko** [comment]
Not great, b/c it masks some other error. Fixing.
