### ISSUE TITLE
Travis is suppressing validator test errors for PRs

### ISSUE THREAD

**Issue by honeybadgerdontcare** [ampproject/amphtml#11275]
From #11199, Travis is reporting that the validator test exits status 1 but it doesn't display why. When I test this locally it does state why.

Here's what Travis is displaying:
```
[13:33:06] Starting 'validator'...
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
Traceback (most recent call last):
  File "build.py", line 580, in <module>
    Main()
  File "build.py", line 576, in Main
    RunTests(out_dir='dist', nodejs_cmd=nodejs_cmd)
  File "build.py", line 548, in RunTests
    subprocess.check_call([nodejs_cmd, '%s/test_runner' % out_dir])
  File "/opt/python/2.7.13/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['node', 'dist/test_runner']' returned non-zero exit status 1
[13:35:23] 'validator' errored after 2.27 min
[13:35:23] Error: Command failed: cd validator && python build.py
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
Traceback (most recent call last):
  File "build.py", line 580, in <module>
    Main()
  File "build.py", line 576, in Main
    RunTests(out_dir='dist', nodejs_cmd=nodejs_cmd)
  File "build.py", line 548, in RunTests
    subprocess.check_call([nodejs_cmd, '%s/test_runner' % out_dir])
  File "/opt/python/2.7.13/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['node', 'dist/test_runner']' returned non-zero exit status 1
    at checkExecSyncError (child_process.js:468:13)
    at execSync (child_process.js:508:13)
    at Gulp.validator (/home/travis/build/ampproject/amphtml/build-system/tasks/validator.js:26:3)
    at module.exports (/home/travis/build/ampproject/amphtml/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/travis/build/ampproject/amphtml/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/travis/build/ampproject/amphtml/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/travis/build/ampproject/amphtml/node_modules/orchestrator/index.js:134:8)
    at /home/travis/build/ampproject/amphtml/node_modules/gulp/bin/gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:140:18)
    at node.js:1043:3
Command failed: node_modules/gulp/bin/gulp.js validator
```

For example, here is what the output should look like (with minor differences cause it's on Travis):

```
[[build.py RunTests]] - entering ...
Started
.....F....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Failures:
1) ValidatorFeatures feature_tests/ads.html
  Message:
    AssertionError: 
    feature_tests/ads.out:1:0
    expected:
    PASS
    feature_tests/ads.html:1333:7 The extension 'amp-analytics' was found on this page, but is unused (no 'amp-analytics' tag seen). This may become an error in the future. [DEPRECATION]
    saw:
    PASS
    feature_tests/ads.html:1334:7 The extension 'amp-analytics' was found on this page, but is unused (no 'amp-analytics' tag seen). This may become an error in the future. [DEPRECATION]
  Stack:
    AssertionError: 
    feature_tests/ads.out:1:0
    expected:
    PASS
    feature_tests/ads.html:1333:7 The extension 'amp-analytics' was found on this page, but is unused (no 'amp-analytics' tag seen). This may become an error in the future. [DEPRECATION]
    saw:
    PASS
    feature_tests/ads.html:1334:7 The extension 'amp-analytics' was found on this page, but is unused (no 'amp-analytics' tag seen). This may become an error in the future. [DEPRECATION]
        at ValidatorTestCase.run (/amphtml/validator/dist/validator_test_minified.js:948:398)
        at Object.<anonymous> (//amphtml/validator/dist/validator_test_minified.js:949:248)

3802 specs, 1 failure
Finished in 3.485 seconds
Traceback (most recent call last):
  File "build.py", line 580, in <module>
    Main()
  File "build.py", line 576, in Main
    RunTests(out_dir='dist', nodejs_cmd=nodejs_cmd)
  File "build.py", line 548, in RunTests
    subprocess.check_call([nodejs_cmd, '%s/test_runner' % out_dir])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['node', 'dist/test_runner']' returned non-zero exit status 1
```

**Comment by rsimha-amp** [comment]
Interesting. AFAIK, we suppress stdout on Travis, but we do print any errors that are part of stderr. The easiest way to reproduce the Travis behavior on your local machine is to run the following:
```
export TRAVIS=true
gulp validator
gulp validator-webui
```
Let me know if there's an easy way to reproduce the errors you expect to see, and I can take a look at whether we're suppressing any output that ought to be printed.

**Comment by rsimha-amp** [comment]
@honeybadgerdontcare, here's where we set the logging level for validator tests: https://github.com/ampproject/amphtml/blob/master/validator/build.py#L556

I suspect that the validator build scripts are printing failures to `logging.INFO` instead of `logging.ERROR`. That explains the behavior you're seeing.

The reason we restrict the logging level on Travis is that the validator tests were printing hundreds of lines on the console for every build, which were making it difficult to read the logs for other test tasks that followed it.

**Comment by honeybadgerdontcare** [comment]
@rsimha-amp Yes I tested it with travis=true and also travis=false and in both situations it suppresses the validator test errors, which means we've been not showing them for at least a month? Could you clarify what part of the validator output was noise and not actual errors?

fyi @ampproject/validator

**Comment by honeybadgerdontcare** [comment]
@rsimha-amp As to the errors we're expecting to see, I created a copy of the above mentioned PR in #11277. That should have the following error:

```
Failures:
1) ValidatorFeatures feature_tests/ads.html
  Message:
    AssertionError: 
    feature_tests/ads.out:1:0
    expected:
    PASS
    feature_tests/ads.html:1333:7 The extension 'amp-analytics' was found on this page, but is unused (no 'amp-analytics' tag seen). This may become an error in the future. [DEPRECATION]
    saw:
    PASS
    feature_tests/ads.html:1334:7 The extension 'amp-analytics' was found on this page, but is unused (no 'amp-analytics' tag seen). This may become an error in the future. [DEPRECATION]
  Stack:
    AssertionError: 
    feature_tests/ads.out:1:0
    expected:
    PASS
    feature_tests/ads.html:1333:7 The extension 'amp-analytics' was found on this page, but is unused (no 'amp-analytics' tag seen). This may become an error in the future. [DEPRECATION]
    saw:
    PASS
    feature_tests/ads.html:1334:7 The extension 'amp-analytics' was found on this page, but is unused (no 'amp-analytics' tag seen). This may become an error in the future. [DEPRECATION]
        at ValidatorTestCase.run (/amphtml/validator/dist/validator_test_minified.js:948:398)
        at Object.<anonymous> (//amphtml/validator/dist/validator_test_minified.js:949:248)

3802 specs, 1 failure
```

**Comment by rsimha-amp** [comment]
@honeybadgerdontcare, using `TRAVIS=true` or `TRAVIS=false` in your environment has the same effect, and runs tests as if you were on a Travis VM. You'll need to `unset TRAVIS` to restore local development behavior.

In the past, the validator tests were printing hundreds of lines in the passing case, when there were zero errors. That's what we ended up having to silence on Travis.

If you print your error messages to `logging.ERROR`, you should be able to see them on Travis.

**Comment by honeybadgerdontcare** [comment]
@rsimha-amp ah, yes, forgot it's really just checking for the existence of `TRAVIS`.

I wasn't aware of the passing case producing output, I'll look into that.

**Comment by rsimha-amp** [comment]
@honeybadgerdontcare The verbose output in the passing case was silenced in #10823. Look at the changes to `validator/build.py` and `validator/webui/build.py` in https://github.com/ampproject/amphtml/pull/10823/files to see what I had to do to silence them.

**Comment by honeybadgerdontcare** [comment]
I see that `gulp validator` silences all the jasmine output and only displays the python error (`subprocess.CalledProcessError: Command '['node', 'dist/test_runner']' returned non-zero exit status 1`).

However, `cd validator && python build.py` preserves the jasmine output (validator test failure message) and also suppresses the `build.py` `logging.info` output when `TRAVIS` is present.

So maybe the issue is the change for pr-check.js to use `gulp validator` instead of `cd validator && python build.py`...or find a way for `gulp validator` to preserve the jasmine output.

**Comment by rsimha-amp** [comment]
@honeybadgerdontcare, your latest comment helped me narrow down the problem! The version of `execSync` that the `gulp validator` wrapper originally used was silently suppressing the Jasmine output.

I've sent you #11280 with a fix. All should be well after this.

**Comment by rsimha-amp** [comment]
You should be good once you sync past #11280

**Comment by honeybadgerdontcare** [comment]
@rsimha-amp thank you!
