### ISSUE TITLE
Custom element does not have document

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#11339]
```
Error: Cannot read property 'document' of null
    at document (https://raw.githubusercontent.com/ampproject/amphtml/1505341213754/src/custom-element.js:1115:20)
    at dispatchCustomEvent (https://raw.githubusercontent.com/ampproject/amphtml/1505341213754/src/custom-element.js:1284:10)
```

assigning to @dvoytenko, since I assume it's a PWA issue

**Comment by dvoytenko** [comment]
@jridgewell How frequent is this error? This is typical for racy destruction when an iframe's window is killed. We get this kind of errors in those cases, but they are usually very rare.

**Comment by jridgewell** [comment]
We've had 1,179 reports in the last day

**Comment by jridgewell** [comment]
Closing as a dupe of https://github.com/ampproject/amphtml/issues/9870.
