### ISSUE TITLE
A4A: Cannot call method 'bind' of undefined

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#11392]
New Canary error:

```
Error: Cannot call method 'bind' of undefined
    at bind (https://raw.githubusercontent.com/ampproject/amphtml/1506043780363/ads/google/a4a/performance.js:165:44)
    at Number (https://raw.githubusercontent.com/ampproject/amphtml/1506043780363/ads/google/a4a/google-data-reporter.js:68:31)
    at https://raw.githubusercontent.com/ampproject/amphtml/1506043780363/extensions/amp-ad/0.1/amp-ad.js:102:19
    at https://raw.githubusercontent.com/ampproject/amphtml/1506043780363/node_modules/promise-pjs/promise.js:422:19
    at https://raw.githubusercontent.com/ampproject/amphtml/1506043780363/node_modules/promise-pjs/promise.js:456:6
```

**Comment by jridgewell** [comment]
Reports are coming from Android 4.X
