### ISSUE TITLE
extensions/amp-access/0.1/test/test-amp-access.js fails when run under chai 4

### ISSUE THREAD

**Issue by rsimha-amp** [ampproject/amphtml#11398]
Chai 4 isn't checked in yet, but I'm going to have to disable part of this test to let the rest continue to run after the chai upgrade.
```
  AccessService authorization
     
      ● "after each" hook for "should resolve first-authorization promise after success"
        Chrome 61.0.3163 (Linux 0.0.0)
      Unexpected call: tick(ol) at Performance.onload_ (/tmp/src/service/performance-impl.js:162:9 <- /tmp/3008a22d1d6f37c7d1bb3d774814a546.browserify:186955:10)
      Expectation met: tick(aaa) once
      Expectation met: tickSinceVisible(aaav) once
      ExpectationError: Unexpected call: tick(ol) at Performance.onload_ (/tmp/src/service/performance-impl.js:162:9 <- /tmp/3008a22d1d6f37c7d1bb3d774814a546.browserify:186955:10)
      Expectation met: tick(aaa) once
      Expectation met: tickSinceVisible(aaav) once
          at Object.fail (/tmp/node_modules/sinon/lib/sinon/mock-expectation.js:281:0 <- /tmp/3008a22d1d6f37c7d1bb3d774814a546.browserify:150525:25)
          at Object.verify (/tmp/node_modules/sinon/lib/sinon/mock.js:106:0 <- /tmp/3008a22d1d6f37c7d1bb3d774814a546.browserify:150640:29)
          at Context.<anonymous> (/tmp/extensions/amp-access/0.1/test/test-amp-access.js:560:20 <- /tmp/3008a22d1d6f37c7d1bb3d774814a546.browserify:31860:21)
```
See #11390

**Comment by rsimha-amp** [comment]
@dvoytenko, assigning to you based on the `git log` of this file. Please reassign if needed.
