### ISSUE TITLE
test/functional/inabox/test-inabox-viewport.js fails when run under chai 4

### ISSUE THREAD

**Issue by rsimha-amp** [ampproject/amphtml#11397]
Chai 4 isn't checked in yet, but I'm going to have to disable part of this test to let the rest continue to run after the chai upgrade. 

```
  inabox-viewport
     
      ● should work for size, layoutRect and position observer
        Chrome 61.0.3163 (Linux 0.0.0)
      TypeError: Cannot read property 'forEach' of undefined
          at ViewportBindingInabox.remeasureAllElements_ (/tmp/src/inabox/inabox-viewport.js:244:29 <- /tmp/292639589e3de1bb8f213f8bd0399990.browserify:44319:29)
          at ViewportBindingInabox.updateBoxRect_ (/tmp/src/inabox/inabox-viewport.js:229:11 <- /tmp/292639589e3de1bb8f213f8bd0399990.browserify:44300:12)
          at /tmp/src/inabox/inabox-viewport.js:161:15 <- /tmp/292639589e3de1bb8f213f8bd0399990.browserify:44223:14
          at Context.<anonymous> (/tmp/test/functional/inabox/test-inabox-viewport.js:147:4 <- /tmp/292639589e3de1bb8f213f8bd0399990.browserify:73256:5)
```

See #11390

**Comment by rsimha-amp** [comment]
@zhouyx, assigning to you based on the `git log` of this file. Please reassign if needed.
