### ISSUE TITLE
A4A: Crypto Bug

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#11394]
```
Error: Signing service error for google: Failed to import key ({"alg":"RS256","e":"AQAB","ext":true,"kid":"1","kty":"RSA","n":"z43rjaJ9PLk1FHMEL31_ILXGtUTN03rxJ9amD9y3BRDpbTA-GkUKiQM07xAd8OXPUZRqcjvXQfc7b1RCEtwrcfx9oBRdF78QMA4tLLCqSHP0tSuqYF0fA7-GyTFWDcYzey90jRFNNWxjzKrvSazacE0TvJ8S_AVP4EV67VdbByCC1tpBzLhhy7RFHp2cXGTpWYUqZUAVUdJoeBuCho_zQz2au7c6sDaLiF-uYL9Td9MrZ6tSLo3MeMIZia4WgWqjTDICR0h-zlbHUd0K9CoXbGTt5nvkebXHmbKd99ma6zRYVlYNJTuSqsRCBNYtCTFVHIZeBlkjHKsQ46HTZPexZw"}): Member JsonWebKey.kty is required and must be an instance of DOMString
    at message (https://raw.githubusercontent.com/ampproject/amphtml/1506043780363/src/log.js:490:22)
    at https://raw.githubusercontent.com/ampproject/amphtml/1506043780363/src/log.js:220:43
    at https://raw.githubusercontent.com/ampproject/amphtml/1506043780363/src/log.js:234:36
    at https://raw.githubusercontent.com/ampproject/amphtml/1506043780363/extensions/amp-a4a/0.1/signature-verifier.js:445:6
```

Seems to be new to Safari 11.

/cc @ampproject/a4a

**Comment by taymonbeal** [comment]
Have reproduced. Preferential rendering is flat-out broken on Safari 11; it spews various console errors and then falls back to one of the delayed modes. The problem is also independent of the crypto verifier experiment. Should we bump to P0?

**Comment by jridgewell** [comment]
If this causes no ad to display, then I'd say P0 (we'll patch prod and canary). If this just causes delayed fetch, I'd say P1 (will patch canary, goes to prod next week).

**Comment by taymonbeal** [comment]
The ad does display.

**Comment by taymonbeal** [comment]
@jridgewell, what do we need to do to get this cherry-picked?
