### ISSUE TITLE
Yarn error while installing dependency plugin

### ISSUE THREAD

**Issue by tea3** [ampproject/amphtml#11977]
Hi there , Thank you for wonderful plugin.

I'm developing [hexo-generator-amp](https://github.com/tea3/hexo-generator-amp). hexo-generator-amp is depending on [amphtml-validator for node.js](https://www.npmjs.com/package/amphtml-validator). Please tell me how to solve installation error of yarn. When install hexo-generator-amp , the following error occur.   

hexo-generator-amp | Cannot use yarn to install in windows 10
https://github.com/tea3/hexo-generator-amp/issues/33

```
error C:\Users\Administrator\Documents\blog\node_modules\amphtml-validator: Command failed.
Exit code: 1
Command: \bin\sh -c "exit 0" 2> postinstall.DELETEME && rm postinstall.DELETEME || node postinstall-windows.js
Arguments:
Directory: C:\Users\Administrator\Documents\blog\node_modules\amphtml-validator
Output:
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:489:7)
    at Object.<anonymous> (C:\Users\Administrator\Documents\blog\node_modules\amphtml-validator\postinstall-windows.js:43:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

However it seems that it will work if installed with npm.  
Please give me advice.

**Comment by rsimha-amp** [comment]
There's nothing in yarn that should block `hexo-generator-amp` from being installed. This works for me with the following command. Can you check if this works on your set up?

```
rsimha@bobdylan (master):~/src/amphtml$ yarn add --dev --exact hexo-generator-amp
yarn add v1.2.0
$ node build-system/check-package-manager.js
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
success Saved 79 new dependencies.
├─ @types/node@8.0.51
├─ amphtml-validator@1.0.21
├─ asap@2.0.6
├─ async-foreach@0.1.3
├─ boolbase@1.0.0
├─ camel-case@3.0.0
├─ character-parser@2.2.0
├─ cheerio@1.0.0-rc.2
├─ clean-css@4.1.9
├─ constantinople@3.1.0
├─ css-parse@1.7.0
├─ css-select@1.2.0
├─ css-what@2.1.0
├─ doctypes@1.1.0
├─ dom-serializer@0.1.0
├─ domelementtype@1.3.0
├─ domhandler@2.4.1
├─ domutils@1.5.1
├─ ejs@2.5.7
├─ entities@1.1.1
├─ follow-redirects@1.2.5
├─ gaze@1.1.2
├─ get-caller-file@1.0.2
├─ globule@1.2.0
├─ graceful-readlink@1.0.1
├─ hasha@3.0.0
├─ he@1.1.1
├─ hexo-fs@0.2.2
├─ hexo-generator-amp@3.0.12
├─ hexo-util@0.6.2
├─ highlight.js@9.12.0
├─ html-entities@1.2.1
├─ html-minifier@3.5.6
├─ htmlparser2@3.9.2
├─ image-size@0.6.1
├─ in-publish@2.0.0
├─ invert-kv@1.0.0
├─ is-expression@3.0.0
├─ js-stringify@1.0.2
├─ jstransformer@1.0.0
├─ lcid@1.0.0
├─ lodash.mergewith@4.6.0
├─ log-util@1.2.0
├─ ncname@1.0.0
├─ nib@1.1.2
├─ no-case@2.3.2
├─ node-gyp@3.6.2
├─ node-sass@4.6.1
├─ nth-check@1.0.1
├─ os-locale@1.4.0
├─ param-case@2.1.1
├─ promise@7.1.1
├─ pug-attrs@2.0.2
├─ pug-code-gen@2.0.0
├─ pug-error@1.3.2
├─ pug-filters@2.1.5
├─ pug-lexer@3.1.0
├─ pug-linker@3.0.3
├─ pug-load@2.0.9
├─ pug-parser@4.0.0
├─ pug-runtime@2.0.3
├─ pug-strip-comments@1.0.2
├─ pug-walk@1.1.5
├─ pug@2.0.0-rc.4
├─ relateurl@0.2.7
├─ require-directory@2.1.1
├─ require-main-filename@1.0.1
├─ sass-graph@2.2.4
├─ scss-tokenizer@0.2.3
├─ stdout-stream@1.4.0
├─ striptags@2.2.1
├─ stylus@0.54.5
├─ token-stream@0.0.1
├─ which-module@1.0.0
├─ with@5.1.1
├─ wrap-ansi@2.1.0
├─ xml-char-classes@1.0.0
├─ y18n@3.2.1
└─ yargs-parser@5.0.0
Done in 10.37s.
```

**Comment by rsimha-amp** [comment]
@tea3, another thing to note is that we recommend the use of node v6 for amphtml development. Can you updated your node version and see if the error persists?

**Comment by tea3** [comment]
@rsimha-amp 
Thank you for your suggestion. Because I'm not using Yarn and Windows 10 (see https://github.com/tea3/hexo-generator-amp/issues/33) , I can't  check this suggestion. But this advice think to be helpful.
