### ISSUE TITLE
[amp-story] Failed to play media element with src .

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#12806]
Error: Failed to play media element with src .
    at Error (https://raw.githubusercontent.com/ampproject/amphtml/1515617716922/src/log.js:489:16)
    at apply (https://raw.githubusercontent.com/ampproject/amphtml/1515617716922/src/log.js:219:20)
    at apply (https://raw.githubusercontent.com/ampproject/amphtml/1515617716922/src/log.js:233:18)
    at error (https://raw.githubusercontent.com/ampproject/amphtml/1515617716922/extensions/amp-story/0.1/amp-story-page.js:368:8)

**Comment by erwinmombay** [comment]
need to catch/user.error/user.log this

**Comment by newmuis** [comment]
This code path was deleted in https://github.com/ampproject/amphtml/pull/12604/files#diff-db95079f23946983423c72c9352c46e3L369
