### ISSUE TITLE
Null promise in layoutCallback

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#12874]
```
Error: Null promise in layoutCallback
    at message (https://raw.githubusercontent.com/ampproject/amphtml/1515455265699/src/log.js:490:22)
    at https://raw.githubusercontent.com/ampproject/amphtml/1515455265699/src/log.js:220:43
    at https://raw.githubusercontent.com/ampproject/amphtml/1515455265699/src/log.js:234:36
    at TAG (https://raw.githubusercontent.com/ampproject/amphtml/1515455265699/extensions/amp-a4a/0.1/amp-a4a.js:87:12)
    at https://raw.githubusercontent.com/ampproject/amphtml/1515455265699/extensions/amp-a4a/0.1/amp-a4a.js:953:11
    at https://raw.githubusercontent.com/ampproject/amphtml/1515455265699/extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js:872:13
    at https://raw.githubusercontent.com/ampproject/amphtml/1515455265699/extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js:883:10
    at https://raw.githubusercontent.com/ampproject/amphtml/1515455265699/src/service/resources-impl.js:1559:12
```

@keithwrightbos @bradfrizzell can anyone look at this? seems like this is a known issue.
https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/0.1/amp-a4a.js#L968

**Comment by keithwrightbos** [comment]
I no longer see this in error logs.  Please re-open with updated stacktrace if still present.  Thanks!
