### ISSUE TITLE
amp-story drop-in animation preset causes JS error

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#13031]
web-animations.js:133 Uncaught (in promise) DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
        at https://cdn.ampproject.org/rtv/001516850240342/v0/amp-animation-0.1.js:72:153
        at Array.map (<anonymous>)
        at Ab.push.f.u.init (https://cdn.ampproject.org/rtv/001516850240342/v0/amp-animation-0.1.js:72:44)
        at Ab.push.f.u.start (https://cdn.ampproject.org/rtv/001516850240342/v0/amp-animation-0.1.js:72:344)
        at https://cdn.ampproject.org/v0/amp-story-0.1.js:43:430

**Comment by alanorozco** [comment]
Occurs when:

1. Element size == 0.
2. Using a preset with dynamic positioning.
