### ISSUE TITLE
Only first 8 videos in story are playable

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#13231]
JS error is thrown once 9th video is played:

```
TypeError: Cannot read property 'length' of undefined
    at J (https://cdn.ampproject.org/v0/amp-story-0.1.js:15:1932)
    at Ae (https://cdn.ampproject.org/v0/amp-story-0.1.js:153:394)
    at Yb.push.f.f.getElementDistance [as Ba] (https://cdn.ampproject.org/v0/amp-story-0.1.js:154:41)
    at https://cdn.ampproject.org/v0/amp-story-0.1.js:47:222
    at Array.sort (native)
    at ac (https://cdn.ampproject.org/v0/amp-story-0.1.js:47:199)
    at ec (https://cdn.ampproject.org/v0/amp-story-0.1.js:50:289)
    at Yb.push.f.f.preload (https://cdn.ampproject.org/v0/amp-story-0.1.js:52:254)
    at https://cdn.ampproject.org/v0/amp-story-0.1.js:72:465
    at https://cdn.ampproject.org/v0/amp-story-0.1.js:72:310
```

**Comment by newmuis** [comment]
Caused by losing the context here: https://github.com/ampproject/amphtml/blob/6cb71974e10e67fc2f85668929660abf2efe81ca/extensions/amp-story/0.1/media-pool.js#L803
