### ISSUE TITLE
Builds fail with "TypeError: Cannot read property 'value' of undefined"

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#13981]
Only affects "integration_tests" shard which fails during run of integration tests on SL:

> 14 03 2018 00:56:39.808:ERROR [karma]: TypeError: Cannot read property 'value' of undefined
    at /home/travis/build/ampproject/amphtml/node_modules/wd/lib/webdriver.js:134:85
    at Request._callback (/home/travis/build/ampproject/amphtml/node_modules/wd/lib/http-utils.js:88:7)
    at Request.self.callback (/home/travis/build/ampproject/amphtml/node_modules/wd/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/travis/build/ampproject/amphtml/node_modules/wd/node_modules/request/request.js:1081:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/travis/build/ampproject/amphtml/node_modules/wd/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Appears to have started with merge of #13957: https://travis-ci.org/ampproject/amphtml/builds/353073491

/cc @erwinmombay

**Comment by choumx** [comment]
Rollback (#13975) doesn't fix it: https://travis-ci.org/ampproject/amphtml/jobs/353123579

Top line on stack trace is this: 
```js
err = new Error('The environment you requested was unavailable.' + ((jsonData && jsonData.value) ? ('\n' + jsonData.value.message) : ''));
```
https://github.com/admc/wd/blob/724dd5566e8d27de7a54af7d5fec5992ad486537/lib/webdriver.js#L134

Looks like a Selenium misconfiguration. Current guess is that launching one of the SL browsers is failing.

**Comment by choumx** [comment]
Same failure also happens when running tests locally with Sauce Connect.

**Comment by choumx** [comment]
Isolated it to the `SL_iOS_9_1` SL configuration. Now to figure out why it's fubared.

**Comment by choumx** [comment]
For posterity: https://wiki.saucelabs.com/display/DOCS/2018/02/09/End-of-Life+for+iOS+versions+9.2+and+below+on+Simulators

Other notes:
- `wd` fixed the "Cannot read property 'value' of undefined" bug about one week ago in version 1.6.1. Not sure why it doesn't receive the environment config data for output though, which would've made isolating this bug a lot easier.
- Our SL configurations are quite different from the recommended ones generated from their product configurator tool. Might be worth updating.

/cc @rsimha
