### ISSUE TITLE
Ads not working on wapo with third party cookies disabled

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#14007]
When having third party cookies disabled. All ads on cached wapo page are blank slots.

To reproduce: 
Disable third party cookies with your browser
Search for wapo news, and open in search carousel. 
You'll see all ad slots empty. 

Related Error:
```
remote.min.js:5 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at new t (https://cdn.krxd.net/amp/v1/remote.min.js:5:7905)
    at new t (https://cdn.krxd.net/amp/v1/remote.min.js:5:851)
    at Object.<anonymous> (https://cdn.krxd.net/amp/v1/remote.min.js:5:391)
    at e (https://cdn.krxd.net/amp/v1/remote.min.js:5:150)
    at https://cdn.krxd.net/amp/v1/remote.min.js:5:274
    at https://cdn.krxd.net/amp/v1/remote.min.js:5:279
```

cc @jasti

**Comment by jasti** [comment]
Reached out to WaPo folks over email pointing to this. Thanks Yuxuan.
