### ISSUE TITLE
build-system/tasks/check-links.js fails on node v8.9.3

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#14980]
```
@2018-04-30 13:55:29:~/Development/amphtml$ gulp
/usr/local/google/home/dinghongfei/Development/amphtml/build-system/tasks/check-links.js:143
  filteredMarkdown = filteredMarkdown.replace(/<code>(.*?)<\/code>/gs, '');
                                              ^

SyntaxError: Invalid regular expression flags
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/google/home/dinghongfei/Development/amphtml/build-system/tasks/index.js:20:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)

```

It works fine in v8.11.1. Node might have started support regex better in 8.11? Should we change our package.json to force node version ^8.11.1?

@rsimha

**Comment by rsimha** [comment]
... and I just realized you were talking about forcing the min version to `^8.11.1`. Agreed!

**Comment by rsimha** [comment]
@lannka With #14995, we no longer need to force users to upgrade from `node` `^8.0.0` to `8.11.1`

And with #14983, we'll have a mechanism in place to suggest the latest LTS version of `node` and the stable version of `yarn` to users (warning mode only)
