### ISSUE TITLE
amp4ads-host-v0.js: b.postMessage is not a function error msg

### ISSUE THREAD

**Issue by rokerkony** [ampproject/amphtml#15007]
## What's the issue?
AMP is poluting our application logs in bugsnag. See more here:
![screen shot 2018-05-02 at 14 27 00](https://user-images.githubusercontent.com/156132/39523589-7322aaee-4e16-11e8-8839-9bf026e8f3eb.png)

## How do we reproduce the issue?
Unfortunatelly I don't know.

## What browsers are affected?
![screen shot 2018-05-02 at 14 37 02](https://user-images.githubusercontent.com/156132/39523562-5f1a4bec-4e16-11e8-9b6a-84962bc2e9bb.png)

Is there something we could do? Our app has no intention to be on AMP :( at least for now

**Comment by aghassemi** [comment]
/to @lannka Looks like an in-a-box issue.

**Comment by lannka** [comment]
Might be cause by this [code](https://github.com/ampproject/amphtml/blob/master/ads/inabox/inabox-host.js#L72).

Pending messages are from external scripts. They might be passing wrong message data.

If so, this is legitimate errors we should bring up to ad networks who send those wrong messages.

Which ad network is your application using? Is it doubleclick?

**Comment by rokerkony** [comment]
any progress here?

**Comment by twhid** [comment]
I'm also seeing the same errors. According to New Relic, it's 90.16% of my errors over the last 3 days and it's overwhelmingly Safari (both desktop and iOS). It's creating a lot of noise.

This is the script:
https://cdn.ampproject.org/rtv/011535566825959/amp4ads-host-v0.js

It doesn't appear to be a problem with the message, the error is that `b.postMessage` is undefined. Perhaps the handle on the  iframe (which I assume is `b`) is being lost?

We're using doubleclick.

**Comment by lvillanne** [comment]
I'm also seeing same errors with users on safari/ios and chrome/ios.

We're using doubleclick.

**Comment by voidzone** [comment]
Getting a plethora of these too.

![image](https://user-images.githubusercontent.com/2574525/47223125-0fd8b300-d37e-11e8-8e6c-4a7beb523c88.png)

**Comment by cramforce** [comment]
@lannka Independent of the ad networks we should probably be robust against the null `b` value and if this is too spammy switch to a warning.

**Comment by iMontes** [comment]
Any progress?

**Comment by lvillanne** [comment]
This bug affect :
- All browser on IOS (Safari Mobile, Chrome Mobile, ...)
- Safari on Mac OS

In my case, this error is more than 90% of my javascript errors.

**Comment by cgdev332** [comment]
Is there an update for this...

**Comment by himberjack** [comment]
Watching...

**Comment by lannka** [comment]
looked at code now, we have already added message validation (#15020) and try catch during message processing (#17749) long time ago. that said, we shouldn't expect the `b.postMessage` error as posted originally. 

If this is still a problem, @himberjack @cgdev332 @lvillanne @iMontes could you provide a new stack trace to assist debugging?

**Comment by ababbdev** [comment]
We are still getting this as recent as 30 minutes ago.

`TypeError: b.postMessage is not a function. (In 'b.postMessage(R("position",a.sentinel,d),c)', 'b.postMessage' is undefined)
  at qa(https://raw.githubusercontent.com/ampproject/amphtml/1812261943070/ads/inabox/inabox-messaging-host.js:182:5)
  at ? (https://raw.githubusercontent.com/ampproject/amphtml/1812261943070/ads/inabox/inabox-messaging-host.js:169:11)
  at ? (https://raw.githubusercontent.com/ampproject/amphtml/1812261943070/ads/inabox/position-observer.js:73:7)
  at fire(https://raw.githubusercontent.com/ampproject/amphtml/1812261943070/src/observable.js:84:7)
  at ? (https://raw.githubusercontent.com/ampproject/amphtml/1812261943070/ads/inabox/position-observer.js:64:9)
  at d(https://raw.githubusercontent.com/ampproject/amphtml/1812261943070/src/utils/rate-limit.js:39:5)
  at ? (https://raw.githubusercontent.com/ampproject/amphtml/1812261943070/src/utils/rate-limit.js:57:7)
  at i(/assets/nuxt/dist/client/b78b33b548ee8452d790.js:2:381376)
  at getBoundingClientRect([native code])
  at value(/assets/nuxt/dist/client/cc2ea795cfa25cdd712a.js:2:15605)
  at value(/assets/nuxt/dist/client/cc2ea795cfa25cdd712a.js:2:15665)
  at ? (/assets/nuxt/dist/client/cc2ea795cfa25cdd712a.js:2:22633)
  at forEach([native code])
  at value(/assets/nuxt/dist/client/cc2ea795cfa25cdd712a.js:2:22554)
  at value([native code])
  at s(/assets/nuxt/dist/client/cc2ea795cfa25cdd712a.js:2:18487)
  at ? (/assets/nuxt/dist/client/cc2ea795cfa25cdd712a.js:2:18500)
  at i(/assets/nuxt/dist/client/b78b33b548ee8452d790.js:2:381376)`

Thanks for your attention to this matter.

**Comment by oguzhanaslan** [comment]
progress?

**Comment by alaa-awartany** [comment]
Thanks for your efforts, watching...
