### ISSUE TITLE
`gulp dist` fails on a new Macbook due to missing Java 8

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#15119]
Looks like we need to update our dev docs with a section on how to get our closure compiler to work with the out-of-box version of Java found on new Macbooks.

Running `gulp dist` yields the error:
```
Compiler error for v0.js:
No Java runtime present, requesting install.
```

Installing Java from [here](https://support.apple.com/kb/DL1572?locale=en_US) and rerunning `gulp dist` yields the error:
```
Compiler error for v0.js:
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/ampproject/AmpCommandLineRunner : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
```

There is a Java install on the path:
```
~/src/amphtml$ which java
/usr/bin/java
```

And here is the version info:
```
~/src/amphtml$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
```

**Comment by erwinmombay** [comment]
I believe new macbooks come with java9, which isn't compatible with how we compile runner.jar. If anyone is familiar with maven, some help in converting the ant file into maven

**Comment by rsimha** [comment]
@erwinmombay Yeah, that'd be good. I'm still unable to do a `dist` on my laptop.

**Comment by rsimha** [comment]
This is obsolete. We already have instructions in our dev docs for installing the prerequisite version of the JRE (version 8): https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server

**Comment by Enriqe** [comment]
Ran into this issue. Solved it by installing Java 8 JDK and updating the `JAVA_HOME` variable.

1. Install Java 8 SDK: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
2. Open a new command line window and verify you have Java 8 installed
```
$ /usr/libexec/java_home -V
    1.8.0_181, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
```

3. Update `JAVA_HOME` on your bash profile / zshrc: 

```export JAVA_HOME=`/usr/libexec/java_home -v 1.8```

That should work

**Comment by rsimha** [comment]
@Enriqe Was the `JAVA_HOME` workaround essential to get things to work on your laptop? If so, could you add that to the developer docs?

**Comment by Enriqe** [comment]
Sure, I'll send out a PR.
