### ISSUE TITLE
[IE10] High volume exception "Error: Unspecified error."

### ISSUE THREAD

**Issue by adelinamart** [ampproject/amphtml#16069]
Error: Unspecified error.
at (https://raw.githubusercontent.com/ampproject/amphtml/1528841168349/src/service/fixed-layer.js:197)
at getOffsetFromParent (https://raw.githubusercontent.com/ampproject/amphtml/1528841168349/src/service/layers-impl.js:798)
at (https://raw.githubusercontent.com/ampproject/amphtml/1528841168349/extensions/amp-ad/0.1/amp-ad-3p-impl.js:308)
at measureIframeLayoutBox_ (https://raw.githubusercontent.com/ampproject/amphtml/1528841168349/extensions/amp-ad/0.1/amp-ad-3p-impl.js:276)
at (https://raw.githubusercontent.com/ampproject/amphtml/1528841168349/src/service/resource.js:676)
at layoutCallback (https://raw.githubusercontent.com/ampproject/amphtml/1528841168349/src/base-element.js:465)

User agent	
Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.0; Trident/6.0; IEMobile/10.0; ARM; Touch; NOKIA; Lumia 625) 
Service	
default-cdn-1p 
Version	
011528841168349

**Comment by adelinamart** [comment]
@aghassemi I assigned it to you because I think is connect to the last change you approved at https://github.com/ampproject/amphtml/pull/15850
Please reroute to a different person if that's not the case.

**Comment by adelinamart** [comment]
Getting lots of occurrences on this. @choumx can someone look into this asap. Thanks.

**Comment by choumx** [comment]
Can you post the pantheon ID?

**Comment by choumx** [comment]
The deobfuscated stack trace is fubar'ed. 

Deobfuscated:
```
Error: Unspecified error.
at (https://raw.githubusercontent.com/ampproject/amphtml/1528841168349/src/service/fixed-layer.js:197)
at getOffsetFromParent (https://raw.githubusercontent.com/ampproject/amphtml/1528841168349/src/service/layers-impl.js:798)
at (https://raw.githubusercontent.com/ampproject/amphtml/1528841168349/extensions/amp-ad/0.1/amp-ad-3p-impl.js:308)
at measureIframeLayoutBox_ (https://raw.githubusercontent.com/ampproject/amphtml/1528841168349/extensions/amp-ad/0.1/amp-ad-3p-impl.js:276)
at (https://raw.githubusercontent.com/ampproject/amphtml/1528841168349/src/service/resource.js:676)
at layoutCallback (https://raw.githubusercontent.com/ampproject/amphtml/1528841168349/src/base-element.js:465)
```

Minified:
```
Error: Unspecified error.
   at getLayoutRect (https://cdn.ampproject.org/rtv/011528841168349/v0.js:401:33)
   at getLayoutRect (https://cdn.ampproject.org/rtv/011528841168349/v0.js:426:102)
   at rc (https://cdn.ampproject.org/rtv/011528841168349/v0/amp-ad-0.1.js:96:36)
   at onLayoutMeasure (https://cdn.ampproject.org/rtv/011528841168349/v0/amp-ad-0.1.js:95:146)
   at updateLayoutBox (https://cdn.ampproject.org/rtv/011528841168349/v0.js:227:421)
   at measure (https://cdn.ampproject.org/rtv/011528841168349/v0.js:207:400)
   at gk (https://cdn.ampproject.org/rtv/011528841168349/v0.js:346:495)
   at h (https://cdn.ampproject.org/rtv/011528841168349/v0.js:357:304)
   at setState (https://cdn.ampproject.org/rtv/011528841168349/v0.js:320:494)
   at doPass (https://cdn.ampproject.org/rtv/011528841168349/v0.js:341:29
```

**Comment by choumx** [comment]
Looks like it's an IE 10 bug that throws up on this `getBoundingClientRect()`:

https://github.com/ampproject/amphtml/blob/b1495f0f7cc7e124d8fde2f584346142dd15223e/src/service/viewport/viewport-binding-natural.js#L209-L210

**Comment by choumx** [comment]
> This is how Internet Explorer (not just IE 10) handles the issue of trying to call getBoundingClientRect on an element that has not been added do your document yet. Chrome and FF just return 0, but IE throws.

https://github.com/dart-lang/sdk/issues/19065#issuecomment-108436331
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/106812/

@keithwrightbos I think this throws if `this.xOriginIframeHandler_.iframe` is not attached to the DOM:

https://github.com/ampproject/amphtml/blob/b1495f0f7cc7e124d8fde2f584346142dd15223e/extensions/amp-ad/0.1/amp-ad-3p-impl.js#L308-L309

 Naive fix is to check `isConnected` first.

**Comment by choumx** [comment]
Appears to have started with RTV 1528841168349 but after some brief searching I'm not sure which PR could've caused this. 

/to @lannka For fixing the ads code. 
/cc @keithwrightbos @zhouyx

**Comment by choumx** [comment]
I tried loading one of the repro URLs on IE10 and I see a lot of console errors (not just this one) and don't see any ads. Ads appear to load on IE11.

Do we officially support doubleclick ads on IE10?

**Comment by choumx** [comment]
FWIW not sure this is P0 considering it appears to only affect IE10.

**Comment by keithwrightbos** [comment]
We do not, only IE11 or later:
https://support.google.com/dfp_premium/answer/188087?hl=en

**Comment by zhouyx** [comment]
Downgrade this issue since we do not officially support IE10. 

> @lannka I think this throws if this.xOriginIframeHandler_.iframe is not attached to the DOM:

If that's the case we should have `this.xOriginIframeHandler_.iframe` defined only after the iframe has been added to the document. 

However I don't know why the error stack all mentioned the `getOffsetFromParent ` function. Can we reproduce this?

**Comment by lannka** [comment]
thanks folks. i'm trying to reproduce on SauceLabs

**Comment by lannka** [comment]
BTW, I don't know that AMP still support IE10 :-o
Also, surprised that IE10 bug can cause such a spike

**Comment by lannka** [comment]
Saw many other errors in IE10, but not the one here:

<img width="834" alt="screen shot 2018-06-15 at 5 03 34 pm" src="https://user-images.githubusercontent.com/8496897/41493644-2ea259d0-70be-11e8-9d6c-6b6fb8cdec03.png">

**Comment by choumx** [comment]
@zhouyx The unminified stack is incorrect, you should ignore it.

**Comment by choumx** [comment]
@jridgewell Do we have a sense of how many deobfuscated traces are unreliable?

**Comment by lannka** [comment]
Not seeing them anymore.
