### ISSUE TITLE
Error: preconnect without defaultView

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#16105]
Error: preconnect without defaultView
    at Error (https://raw.githubusercontent.com/ampproject/amphtml/1529035559569/src/log.js:505:16)
    at apply (https://raw.githubusercontent.com/ampproject/amphtml/1529035559569/src/log.js:221:20)
    at apply (https://raw.githubusercontent.com/ampproject/amphtml/1529035559569/src/log.js:234:18)
    at https://raw.githubusercontent.com/ampproject/amphtml/1529035559569/src/service/resource.js:680:4
    at https://raw.githubusercontent.com/ampproject/amphtml/1529035559569/src/service/resources-impl.js:2153:50

`go/ampe/CKq96aOviLGGPw` and `go/ampe/CK7DhJOXr4_lvwE`

@choumx @jridgewell

**Comment by choumx** [comment]
Context: #15993

**Comment by jridgewell** [comment]
Demoting to P2. We should look at what other times are being triggered without a `defaultView`.

**Comment by rcebulko** [comment]
Bumping this as a top error
