### ISSUE TITLE
Datepicker tests flaking on master (windows Chrome)

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#16179]
On Windows Chrome specifically. 
Failing build: https://travis-ci.org/ampproject/amphtml/jobs/394644244

Stacktrace: 
```
DESCRIBE => amp-date-picker
  DESCRIBE => picker.today
    DESCRIBE =>  
      IT => sets the current date to today
        ✗ Error: Timeout waiting for wait for attribute date on AMP-DATE-PICKER
            at poll (/tmp/testing/iframe.js:418:17 <- /tmp/dc9d1f09163ff9b3f829ccdda6df04d8.browserify:100650:18)
●
      IT => sets the current date to today with an offset
        ✗ Error: Timeout waiting for wait for attribute date on AMP-DATE-PICKER
            at poll (/tmp/testing/iframe.js:418:17 <- /tmp/dc9d1f09163ff9b3f829ccdda6df04d8.browserify:100650:18)
●
      IT => sets the current date to today with a negative offset
        ✗ Error: Timeout waiting for wait for attribute date on AMP-DATE-PICKER
            at poll (/tmp/testing/iframe.js:418:17 <- /tmp/dc9d1f09163ff9b3f829ccdda6df04d8.browserify:100650:18)
●
  DESCRIBE => picker.startToday
    DESCRIBE =>  
      IT => sets the current start date to today
        ✗ Error: Timeout waiting for wait for attribute start-date on AMP-DATE-PICKER
            at poll (/tmp/testing/iframe.js:418:17 <- /tmp/dc9d1f09163ff9b3f829ccdda6df04d8.browserify:100650:18)
●
      IT => sets the current start date to today with an offset
        ✗ Error: Timeout waiting for wait for attribute start-date on AMP-DATE-PICKER
            at poll (/tmp/testing/iframe.js:418:17 <- /tmp/dc9d1f09163ff9b3f829ccdda6df04d8.browserify:100650:18)
●
      IT => sets the current start date to today with a negative offset
        ✗ Error: Timeout waiting for wait for attribute start-date on AMP-DATE-PICKER
            at poll (/tmp/testing/iframe.js:418:17 <- /tmp/dc9d1f09163ff9b3f829ccdda6df04d8.browserify:100650:18)
●
  DESCRIBE => picker.endToday
    DESCRIBE =>  
      IT => sets the current end date to today
        ✗ Error: Timeout waiting for wait for attribute end-date on AMP-DATE-PICKER
            at poll (/tmp/testing/iframe.js:418:17 <- /tmp/dc9d1f09163ff9b3f829ccdda6df04d8.browserify:100650:18)
●●
      IT => sets the current end date to today with a negative offset
        ✗ Error: Timeout waiting for wait for attribute end-date on AMP-DATE-PICKER
            at poll (/tmp/testing/iframe.js:418:17 <- /tmp/dc9d1f09163ff9b3f829ccdda6df04d8.browserify:100650:18)
```

**Comment by aghassemi** [comment]
if we skip, let's just skip for `skipOldChrome` unless it flakes in other platforms
