### ISSUE TITLE
gulp test --coverage --files ... throws errors

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#16396]
Code coverage appear to not be working

`gulp test --coverage --files=extensions/amp-subscriptions/0.1/test/*.js`

(passing tests output omitted)
```
26 06 2018 13:16:00.358:ERROR [coverage]: TypeError: Cannot read property 'text' of undefined
    at /usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/report/html.js:239:52
    at Array.forEach (<anonymous>)
    at annotateFunctions (/usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/report/html.js:224:26)
    at HtmlReport.writeDetailPage (/usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/report/html.js:427:9)
    at /usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/report/html.js:489:26
    at SyncFileWriter.writeFile (/usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/util/file-writer.js:57:9)
    at FileWriter.writeFile (/usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/util/file-writer.js:147:23)
    at /usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/report/html.js:488:24
    at Array.forEach (<anonymous>)
    at HtmlReport.writeFiles (/usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/report/html.js:482:23)
    at /usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/report/html.js:484:22
    at Array.forEach (<anonymous>)
    at HtmlReport.writeFiles (/usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/report/html.js:482:23)
    at HtmlReport.writeReport (/usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/report/html.js:566:14)
    at writeReport (/usr/local/google/home/jpettitt/amp/amphtml/node_modules/karma-coverage/lib/reporter.js:68:16)
    at /usr/local/google/home/jpettitt/amp/amphtml/node_modules/karma-coverage/lib/reporter.js:297:11
26 06 2018 13:16:00.552:ERROR [coverage]: TypeError: Cannot read property 'text' of undefined
    at /usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/report/html.js:239:52
    at Array.forEach (<anonymous>)
    at annotateFunctions (/usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/report/html.js:224:26)
    at HtmlReport.writeDetailPage (/usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/report/html.js:427:9)
    at /usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/report/html.js:489:26
    at SyncFileWriter.writeFile (/usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/util/file-writer.js:57:9)
    at FileWriter.writeFile (/usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/util/file-writer.js:147:23)
    at /usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/report/html.js:488:24
    at Array.forEach (<anonymous>)
    at HtmlReport.writeFiles (/usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/report/html.js:482:23)
    at /usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/report/html.js:484:22
    at Array.forEach (<anonymous>)
    at HtmlReport.writeFiles (/usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/report/html.js:482:23)
    at HtmlReport.writeReport (/usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/report/html.js:566:14)
    at LcovReport.writeReport (/usr/local/google/home/jpettitt/amp/amphtml/node_modules/istanbul/lib/report/lcov.js:55:19)
    at writeReport (/usr/local/google/home/jpettitt/amp/amphtml/node_modules/karma-coverage/lib/reporter.js:68:16)
```

**Comment by rsimha** [comment]
Adding @jonkeller who implemented `--coverage`

**Comment by rsimha** [comment]
Looks like this is due to https://github.com/gotwarlost/istanbul/issues/602. Looking for a fix.

**Comment by jonkeller** [comment]
Thanks, @rsimha! I'm no longer on the AMP team, but still pretty close by. Please let me know if I can answer any questions!
