### ISSUE TITLE
Error: Untrusted viewer referrer override

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#17346]
Error: Untrusted viewer url override: https://www.pinterest.com/pin/519391769509165494/ at null
    at Error (https://raw.githubusercontent.com/ampproject/amphtml/1533253141109/src/log.js:528:16)
    at apply (https://raw.githubusercontent.com/ampproject/amphtml/1533253141109/src/log.js:244:20)
    at apply (https://raw.githubusercontent.com/ampproject/amphtml/1533253141109/src/log.js:257:18)
    at https://raw.githubusercontent.com/ampproject/amphtml/1533253141109/src/service/jank-meter.js:97:8

**Comment by rsimha** [comment]
This is in the top 10 errors this week: go/ampe/CPeBn8Skwq7tEw?project=amp-error-reporting

**Comment by adelinamart** [comment]
Bugs should always be assigned. @choumx please reassign to the appropriate person if needed.

**Comment by calebcordry** [comment]
This is still going on ~32k errors in trailing 7 days.

**Comment by choumx** [comment]
Same as #7520. We should make this an expected error.
