### ISSUE TITLE
Visual tests sometimes fail due to non-unique test names

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#17512]
See https://travis-ci.org/ampproject/amphtml/jobs/416145788#L623-L639

```
[23:26:15] StatusCodeError: 400 - {"errors":[{"status":"bad_request"},{"source":{"pointer":"/data/attributes/base"},"detail":"The name of each snapshot must be unique, and this name already exists in the build: 'amp-lightbox-gallery - article (prod)' -- You can fix this by passing a 'name' param when creating the snapshot. See the docs for more info on identifying snapshots for your specific client: https://percy.io/docs"}]}
    at new StatusCodeError (/home/travis/build/ampproject/amphtml/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/travis/build/ampproject/amphtml/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/travis/build/ampproject/amphtml/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/travis/build/ampproject/amphtml/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/travis/build/ampproject/amphtml/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/travis/build/ampproject/amphtml/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by danielrozenberg** [comment]
This seems to have only happened once in the past two weeks. I tried restarting the above build to see if this reproduces, but I'm getting a Git related error instead. Since I can't reproduce this and it doesn't seem to repeat, I'm going to close this issue. If this happens again, we can revisit

**Comment by danielrozenberg** [comment]
This happened to me, reopening and will investigate soon
