### ISSUE TITLE
Invalid resize values

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#17944]
```
AMP-DOUBLECLICK-SAFEFRAME: Invalid resize values.
    at wa (https://cdn.ampproject.org/rtv/011535579255907/v0.js:9:169)
    at ta.f.Ja (https://cdn.ampproject.org/rtv/011535579255907/v0.js:4:197)
    at ta.f.error (https://cdn.ampproject.org/rtv/011535579255907/v0.js:4:307)
    at Zd.push.f.g.processMessage (https://cdn.ampproject.org/rtv/011535579255907/v0/amp-ad-network-doubleclick-impl-0.1.js:154:462)
    at Yd (https://cdn.ampproject.org/rtv/011535579255907/v0/amp-ad-network-doubleclick-impl-0.1.js:144:1001)
```

One of our top errors now.

go/ampe/CI2e5dSShvzWKg

**Comment by bradfrizzell** [comment]
hey sorry I missed this, looking into it now.
