### ISSUE TITLE
Error: undefined is not an object (evaluating 'a.nodeType')

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#18490]
Error: undefined is not an object (evaluating 'a.nodeType')
at (https://raw.githubusercontent.com/ampproject/amphtml/1809142227020/node_modules/document-register-element/build/document-register-element.patched.js:477)
at o (https://raw.githubusercontent.com/ampproject/amphtml/1809142227020/node_modules/document-register-element/build/document-register-element.patched.js:584)
at getRaf_ (https://raw.githubusercontent.com/ampproject/amphtml/1809142227020/src/service/vsync-impl.js:431)
at (https://raw.githubusercontent.com/ampproject/amphtml/1809142227020/src/service/vsync-impl.js:422)

go/ampe/CLDygoLu8ouOKw

**Comment by jridgewell** [comment]
```
Error: null is not an object (evaluating 'a.nodeType')
    at nodeType (https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/service.js:348:6)
    at elementOrAmpDoc (https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/service.js:247:27)
    at https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/extensions/amp-link-rewriter/0.1/amp-link-rewriter.js:36:49
    at https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/custom-element.js:261:38
    at https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/custom-element.js:138:6
    at https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/custom-element.js:101:13
    at https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/polyfills/custom-elements.js:425:6
    at upgradeSelf_ (https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/polyfills/custom-elements.js:447:4)
    at connectedCallback_ (https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/polyfills/custom-elements.js:561:8)
    at handleRecords_ (https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/polyfills/custom-elements.js:493:17)
```

http://go/ampe/CLmZv5WMxoGh_wE
