### ISSUE TITLE
Some AmpAnimation tests fail when run in strict mode

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#18612]
We're upgrading `babel` to version 7 and enforcing strict mode during unit testing. This has exposed a couple of AmpAnimation test failures due to code in `node_modules/web-animations-js/web-animations.install.js`.

Logs:
```
DESCRIBE => AmpAnimation
  DESCRIBE =>  
    DESCRIBE => in FIE
      DESCRIBE =>  
        IT => should find target in the embed only via selector
          ✗ TypeError: Cannot set property 'true' of undefined
              at /tmp/node_modules/web-animations-js/web-animations.install.js:2149:1
              at exports.installWebAnimations (/tmp/node_modules/web-animations-js/web-animations.install.js:2150:1)
              at installWebAnimationsIfNecessary (/tmp/extensions/amp-animation/0.1/web-animations-polyfill.js:28:5)
              at AmpAnimation.createRunner_ (/tmp/extensions/amp-animation/0.1/amp-animation.js:457:5)
              at _callee24$ (/tmp/extensions/amp-animation/0.1/test/test-amp-animation.js:741:19)
              at tryCatch (/tmp/node_modules/regenerator-runtime/runtime.js:62:1)
              at Generator.invoke [as _invoke] (/tmp/node_modules/regenerator-runtime/runtime.js:296:1)
              at Generator.prototype.(anonymous function) [as next] (/tmp/node_modules/regenerator-runtime/runtime.js:114:1)
              at step (/tmp/testing/yield.js:48:17)
              at _next (/tmp/testing/yield.js:63:7)
●
        IT => should find target in the embed only via target
          ✗ TypeError: Cannot set property 'true' of undefined
              at /tmp/node_modules/web-animations-js/web-animations.install.js:2149:1
              at exports.installWebAnimations (/tmp/node_modules/web-animations-js/web-animations.install.js:2150:1)
              at installWebAnimationsIfNecessary (/tmp/extensions/amp-animation/0.1/web-animations-polyfill.js:28:5)
              at AmpAnimation.createRunner_ (/tmp/extensions/amp-animation/0.1/amp-animation.js:457:5)
              at _callee25$ (/tmp/extensions/amp-animation/0.1/test/test-amp-animation.js:759:19)
              at tryCatch (/tmp/node_modules/regenerator-runtime/runtime.js:62:1)
              at Generator.invoke [as _invoke] (/tmp/node_modules/regenerator-runtime/runtime.js:296:1)
              at Generator.prototype.(anonymous function) [as next] (/tmp/node_modules/regenerator-runtime/runtime.js:114:1)
              at step (/tmp/testing/yield.js:48:17)
              at _next (/tmp/testing/yield.js:63:7)

```

**Comment by aghassemi** [comment]
Seem related to https://github.com/web-animations/web-animations-js/issues/46 

@rsimha Is there a way to opt-out tests from strict mode? The code throwing here is a 3P.

**Comment by rsimha** [comment]
I see. I found several code bugs when I enabled strict mode. But this is a legitimate case where that should be overridden. Will try to take care of it when we patch `web-animations-js`.
