### ISSUE TITLE
XCode is now a dependency to build on Mac?

### ISSUE THREAD

**Issue by jonkeller** [ampproject/amphtml#19048]
Rebased to master today and tried to build, got the following error.  Seems to be a Brotli library used as a transitive dependency of bundlesize.
This should at least be documented at https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md but would be better if this dependency could be removed / if the normal install steps would install a pre-built binary. This is a pain, given that I just want to write one completely unrelated unit test :(
```
 jonkeller@jonkeller-macbookpro  ~/workspace/reportWhen/amphtml   reportWhen ●  gulp build
[14:51:17] Using gulpfile ~/workspace/reportWhen/amphtml/gulpfile.js
[14:51:17] Starting 'update-packages'...
[14:51:18] Installed lint rules from build-system/eslint-rules
[14:51:19] WARNING: The packages in node_modules do not match package.json.
yarn check v1.12.1
success Folder in sync.
✨  Done in 7.93s.
[14:51:28] Running yarn to update packages...
yarn install v1.12.1
$ node build-system/check-package-manager.js
Detected node version v10.13.0 (latest LTS).
Detected gulp version 3.9.1.
Detected yarn version 1.12.1 (stable). Installing packages...
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
info google-closure-compiler-linux@20180910.0.1: The platform "darwin" is incompatible with this module.
info "google-closure-compiler-linux@20180910.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] 🔗  Linking dependencies...
warning " > fetch-mock@7.0.7" has unmet peer dependency "node-fetch@*".
warning " > karma-babel-preprocessor@7.0.0" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
warning " > sinon-chai@3.2.0" has incorrect peer dependency "sinon@>=4.0.0 <7.0.0".
warning " > tsickle@0.33.0" has incorrect peer dependency "typescript@git://github.com/mprobst/TypeScript.git#5456479a4a".
[5/5] 📃  Building fresh packages...
[-/10] ⡀ waiting...
[2/10] ⡀ puppeteer
[3/10] ⡀ iltorb
[-/10] ⡀ waiting...
error /Users/jonkeller/workspace/reportWhen/amphtml/node_modules/iltorb: Command failed.
Exit code: 1
Command: detect-libc prebuild-install || node-gyp rebuild
Arguments:
Directory: /Users/jonkeller/workspace/reportWhen/amphtml/node_modules/iltorb
Output:
prebuild-install WARN install No prebuilt binaries found (target=10.13.0 runtime=node arch=x64 platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.13.0 | darwin | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/Users/jonkeller/workspace/reportWhen/amphtml/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jonkeller/workspace/reportWhen/amphtml/node_modules/iltorb/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jonkeller/workspace/reportWhen/amphtml/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jonkeller/.node-gyp/10.13.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/jonkeller/.node-gyp/10.13.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/jonkeller/workspace/reportWhen/amphtml/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/jonkeller/.node-gyp/10.13.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/jonkeller/workspace/reportWhen/amphtml/node_modules/iltorb',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/jonkeller/workspace/reportWhen/amphtml/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/jonkeller/.nvm/versions/node/v10.13.0/bin/node" "/Users/jonkeller/workspace/reportWhen/amphtml/node_modules/iltorb/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/jonkeller/workspace/reportWhen/amphtml/node_modules/iltorb
```

(Edited: typo)

**Comment by jridgewell** [comment]
We've got to back to `bundlesize: 0.15.3` if we want to avoid. @rsimha

**Comment by kristoferbaxter** [comment]
We could also build our own version of this check and use the `emscriptem` port of `brotli` until support for this compression is added to node core.

`emscriptem` brotli – https://www.npmjs.com/package/brotli

**Comment by rsimha** [comment]
Assigning to @danielrozenberg who is working on a bundle-size app.

**Comment by danielrozenberg** [comment]
Since I don't have a mac, I can't test this or fix this. Reassigning to you ;)

**Comment by alabiaga** [comment]
We should definitely update the docs as I spent some time trying to figure this out.

**Comment by rsimha** [comment]
I believe we no longer need the `bundlesize` package to be installed on dev machines. If #20776 works, we should get rid of the xcode dependency.
