### ISSUE TITLE
test-friendly-iframe-embed.js fails when run alone

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#19650]
```
FAILED TESTS:
  friendly-iframe-embed
    ● should follow main install steps
      Chrome 71.0.3578 (Mac OS X 10.13.6)
    Error: Uncaught TypeError: Illegal constructor (/var/folders/y6/nk1w6dh132b_41x39sry2s9c003wtn/T/node_modules/document-register-element/build/document-register-element.patched.js:1420:10 <- /var/folders/y6/nk1w6dh132b_41x39sry2s9c003wtn/T/c6811a693755df70c0f7ecc8ec733e81.browserify:9357)
        at /var/folders/y6/nk1w6dh132b_41x39sry2s9c003wtn/T/node_modules/document-register-element/build/document-register-element.patched.js:1413:38
        at installCustomElements (/var/folders/y6/nk1w6dh132b_41x39sry2s9c003wtn/T/node_modules/document-register-element/build/document-register-element.patched.js:1407:8)
        at installPolyfillsInChildWindow (Users/dinghongfei/Development/projects/amphtml/src/service/extensions-impl.js:695:5)
        at Extensions.installExtensionsInChildWindow (Users/dinghongfei/Development/projects/amphtml/src/service/extensions-impl.js:432:5)
        at http://localhost:9876/Users/dinghongfei/Development/projects/amphtml/src/friendly-iframe-embed.js:212:16

    ● "after each" hook for "should install extensions"
      Chrome 71.0.3578 (Mac OS X 10.13.6)
    ExpectationError: Expected installExtensionsInChildWindow(match(undefined), ["amp-test"], undefined) once (never called)
    Expectation met: preloadExtension(amp-test) once
        at Object.fail (node_modules/sinon/pkg/lib/sinon/mock-expectation.js:309:1)
        at Object.verify (node_modules/sinon/pkg/lib/sinon/mock.js:116:1)
        at Context.<anonymous> (Users/dinghongfei/Development/projects/amphtml/test/functional/test-friendly-iframe-embed.js:57:20)

  ● "before each" hook for "should install extensions"
    Chrome 71.0.3578 (Mac OS X 10.13.6)
  TypeError: Attempted to wrap info which is already wrapped
      at checkWrappedMethod (node_modules/sinon/pkg/lib/sinon/util/core/wrap-method.js:39:1)
      at wrapMethod (node_modules/sinon/pkg/lib/sinon/util/core/wrap-method.js:87:1)
      at stub (node_modules/sinon/pkg/lib/sinon/stub.js:72:1)
      at Sandbox.stub (node_modules/sinon/pkg/lib/sinon/sandbox.js:291:1)
      at maybeStubConsoleInfoLogWarn (Users/dinghongfei/Development/projects/amphtml/test/_init_tests.js:363:19)
      at Context.<anonymous> (Users/dinghongfei/Development/projects/amphtml/test/_init_tests.js:404:3)
  --------------
  Error: Stack Trace for original
      at wrapMethod (node_modules/sinon/pkg/lib/sinon/util/core/wrap-method.js:112:1)
      at stub (node_modules/sinon/pkg/lib/sinon/stub.js:72:1)
      at Sandbox.stub (node_modules/sinon/pkg/lib/sinon/sandbox.js:291:1)
      at maybeStubConsoleInfoLogWarn (Users/dinghongfei/Development/projects/amphtml/test/_init_tests.js:363:19)
      at Context.<anonymous> (Users/dinghongfei/Development/projects/amphtml/test/_init_tests.js:404:3)
```

The test is accessing global window, and might have some dependency on other tests to initialize.

**Comment by powerivq** [comment]
Re-enabled test. Issue is now closed.
