### ISSUE TITLE
test-amp-video.js is failing when run alone

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#19664]
Likely get skipped when running all tests.

```
SUMMARY:
● 18 tests completed
● 4 tests failed

FAILED TESTS:
  amp-video

      blurred image placeholder
        ● should only fade out blurry image placeholders
          Chrome 71.0.3578 (Mac OS X 10.13.6)
        Error: Uncaught Error: Layout not supported: container. The element did not specify a layout attribute. Check https://www.ampproject.org/docs/guides/responsive/control_layout and the respective element documentation for details.​​​ (/Users/dinghongfei/Development/projects/amphtml/src/custom-element.js:439:8 <- /var/folders/y6/nk1w6dh132b_41x39sry2s9c003wtn/T/ceaa5d01f09b80d05766cd3ebf69c838.browserify:25821)
            at getVideoWithBlur (Users/dinghongfei/Development/projects/amphtml/extensions/amp-video/0.1/test/test-amp-video.js:509:16)
            at Context.<anonymous> (Users/dinghongfei/Development/projects/amphtml/extensions/amp-video/0.1/test/test-amp-video.js:518:18)

    ● "after each" hook for "should only fade out blurry image placeholders"
      Chrome 71.0.3578 (Mac OS X 10.13.6)
    TypeError: Cannot read property 'customElements' of undefined
        at AmpFixture.teardown (Users/dinghongfei/Development/projects/amphtml/testing/describes.js:796:13)
        at http://localhost:9876/Users/dinghongfei/Development/projects/amphtml/testing/describes.js:348:19
        at Array.forEach (<anonymous>)
        at Context.<anonymous> (Users/dinghongfei/Development/projects/amphtml/testing/describes.js:347:37)

    ● "after each" hook for "should only fade out blurry image placeholders"
      Chrome 71.0.3578 (Mac OS X 10.13.6)
    TypeError: Cannot read property 'call' of undefined

  ● "before each" hook
    Chrome 71.0.3578 (Mac OS X 10.13.6)
  TypeError: Cannot read property 'fullTitle' of undefined
      at Context.<anonymous> (Users/dinghongfei/Development/projects/amphtml/test/_init_tests.js:402:31)
```

Notice that there are 30 tests in this file. The mocha only gets to run 22 of them.

**Comment by aghassemi** [comment]
Closing. No point in tracking this as an issue.
