### ISSUE TITLE
Travis integration tests cannot find `build-browser-scripts.js`

### ISSUE THREAD

**Issue by estherkim** [ampproject/amphtml#19825]
Running `gulp test --integration --nobuild --coverage` throws this error in Travis

> [15:45:34] Starting 'test'...
[15:45:34] Webserver started at http://localhost:31862
[15:45:34] Started test responses server on localhost:31862
internal/modules/cjs/loader.js:583
    throw err;
    ^
Error: Cannot find module '/home/travis/build/ampproject/amphtml/node_modules/wd/scripts/build-browser-scripts.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
[15:45:35] Running tests locally...

**Comment by cvializ** [comment]
I think that `yarn add wd` fixes this error message. It must have been added to the code but not added as a dependency in `package.json`

**Comment by estherkim** [comment]
Closing - duplicate of #19889
