### ISSUE TITLE
Tracking: LGTM.com check is broken

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#19924]
LGTM.com checks for incoming pull requests at http://github.com/ampproject/amphtml/ have been failing in the recent past.

[Here](https://lgtm.com/projects/g/ampproject/amphtml/logs/rev/pr-2a92eed00c0272ae4932ebdaa03811ed8fdc1cca/lang:javascript/stage:Build%20master%20(3ccbcc0)) is an example. The logs show the following error:

```
> Missing unknown 3ccbcc061a7dafd691abccdec52cf8e4e2c565b2
[2018-12-17 19:15:42] [DEBUG] Stack trace:
                              com.semmle.util.exception.UserError: Commit does not exist: 3ccbcc061a7dafd691abccdec52cf8e4e2c565b2
                              > Missing unknown 3ccbcc061a7dafd691abccdec52cf8e4e2c565b2
                              	at com.semmle.odasa.actions.PollGit.checkCommit(PollGit.java:446)
                              	at com.semmle.odasa.actions.PollGit.tagRequiredRefs(PollGit.java:411)
                              	at com.semmle.odasa.actions.PollGit.runApi(PollGit.java:244)
                              	at com.semmle.util.process.CliCommand.run(CliCommand.java:61)
                              	at com.semmle.util.process.CliCommand.safeRun(CliCommand.java:80)
                              	at com.semmle.util.process.VerbCliTool.runImpl(VerbCliTool.java:162)
                              	at com.semmle.util.process.VerbCliTool.run(VerbCliTool.java:67)
                              	at com.semmle.worker.tools.WorkerTools.main(WorkerTools.java:33)
                              Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 3ccbcc061a7dafd691abccdec52cf8e4e2c565b2
                              	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:163)
                              	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:234)
                              	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:859)
                              	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:772)
                              	at com.semmle.odasa.actions.PollGit.checkCommit(PollGit.java:441)
                              	... 7 common frames omitted
```

However, I can see that the commit 3ccbcc061a7dafd691abccdec52cf8e4e2c565b2 is a valid one.

I've reached out to the LGTM folks via email to see if they're aware of it.

**Comment by sjvs** [comment]
Thanks for pinging me. This should be resolved now. Let me know if it persists!

**Comment by rsimha** [comment]
@sjvs thanks for the update!

Is there a way we can enable just JS analysis for our repo, and disable Python? (There's very little Python code, and it's analysed via other checks.)

**Comment by rsimha** [comment]
@samlanning Thanks! Everything looks good now.
