### ISSUE TITLE
Can't run gulp pr-check --nobuild

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#20275]
All my software (node/gulp/yarn) is up to date and I'm on an up to date master branch.

When trying to run `gulp pr-check --nobuild`, I get the following error:

```
$ gulp pr-check --nobuild
[12:42:16] Using gulpfile ~/amphtml/gulpfile.js
[12:42:16] Starting 'pr-check'...

pr-check.js: Running pr-check.js...
<path>/amphtml/build-system/git.js:54
  return sha.substr(0, 7);
             ^

TypeError: Cannot read property 'substr' of undefined
    at exports.shortSha (<path>/amphtml/build-system/git.js:54:14)
    at printChangeSummary (<path>/amphtml/build-system/pr-check.js:111:19)
    at main (<path>/amphtml/build-system/pr-check.js:594:5)
    at Object.<anonymous> (<path>/amphtml/build-system/pr-check.js:723:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
```

Please let me know if I can help in any way!

**Comment by rsimha** [comment]
@danielrozenberg recently changed this in #20256

**Comment by danielrozenberg** [comment]
Taking a look…
