### ISSUE TITLE
Error: "Unspecified error" on getBoundingClientRect() on disconnected elements [IE]

### ISSUE THREAD

**Issue by adelinamart** [ampproject/amphtml#20438]
Error: Unspecified error.
at setupDone_ (https://raw.githubusercontent.com/ampproject/amphtml/1901081935550/src/service/viewport/viewport-binding-ios-embed-sd.js:213)
at size_ (https://raw.githubusercontent.com/ampproject/amphtml/1901081935550/src/service/layers-impl.js:481)
at (https://raw.githubusercontent.com/ampproject/amphtml/1901081935550/extensions/amp-ad/0.1/amp-ad-3p-impl.js:306)
at measureIframeLayoutBox_ (https://raw.githubusercontent.com/ampproject/amphtml/1901081935550/extensions/amp-ad/0.1/amp-ad-3p-impl.js:274)
at (https://raw.githubusercontent.com/ampproject/amphtml/1901081935550/src/service/resource.js:862)
at type (https://raw.githubusercontent.com/ampproject/amphtml/1901081935550/src/service/action-impl.js:1201)
at removeResource_ (https://raw.githubusercontent.com/ampproject/amphtml/1901081935550/src/service/resources-impl.js:660)
at marginChange (https://raw.githubusercontent.com/ampproject/amphtml/1901081935550/src/service/resources-impl.js:1294)
at (https://raw.githubusercontent.com/ampproject/amphtml/1901081935550/src/service/history-impl.js:503)
at rebuildDomWhenReady (https://raw.githubusercontent.com/ampproject/amphtml/1901081935550/src/service/resources-impl.js:276)

go/ampe/CNPXxaLgnI3ILg

**Comment by choumx** [comment]
Actual stack trace:
```
Error: Unspecified error.
at f.getLayoutRect (https://cdn.ampproject.org/v0.js:467:33)
at f.getLayoutRect (https://cdn.ampproject.org/v0.js:488:102)
at Sb (https://cdn.ampproject.org/v0/amp-ad-0.1.js:92:36)
at m.onLayoutMeasure (https://cdn.ampproject.org/v0/amp-ad-0.1.js:91:146)
at b.prototype.updateLayoutBox (https://cdn.ampproject.org/v0.js:200:147)
at f.measure (https://cdn.ampproject.org/v0.js:176:388)
at Vj (https://cdn.ampproject.org/v0.js:337:495)
at h (https://cdn.ampproject.org/v0.js:348:304)
at sj.prototype.setState (https://cdn.ampproject.org/v0.js:309:494)
at f.doPass (https://cdn.ampproject.org/v0.js:331:12)
```

**Comment by choumx** [comment]
At this line: https://github.com/ampproject/amphtml/blob/304b48b7244af453e1bbbb1a1507612189f66bf2/src/service/viewport/viewport-binding-natural.js#L225

Looks like an IE-only error when calling `getBoundingClientRect()` on a disconnected element: https://github.com/dart-lang/sdk/issues/19065#issuecomment-108436331

**Comment by choumx** [comment]
Called from `amp-ad` here: https://github.com/ampproject/amphtml/blob/304b48b7244af453e1bbbb1a1507612189f66bf2/extensions/amp-ad/0.1/amp-ad-3p-impl.js#L306-L307

Since it doesn't seem to be a deeper issue (e.g. resources laying out disconnected elements), just guarding against this in `getLayoutRect()` should suffice.

**Comment by choumx** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/106812/

> Created: Apr 27, 2014

😄
