### ISSUE TITLE
Saucelabs dies with "No server available to handle this request" 

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#20492]
Saucelabs status is green, but build still fails with error saying "No server is available to handle this request." It's pretty painful for a build to fail if all the VMs run except for Windows/Edge, since we just wasted 4/5 other builds. 

```
23 01 2019 22:31:58.158:ERROR [SaucelabsLauncher]: { WebDriverError: <html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
    at parseHttpResponse (/home/travis/build/ampproject/amphtml/node_modules/selenium-webdriver/lib/http.js:559:11)
    at Executor.execute (/home/travis/build/ampproject/amphtml/node_modules/selenium-webdriver/lib/http.js:468:26)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'WebDriverError', remoteStacktrace: '' }
23 01 2019 22:31:58.611:ERROR [SaucelabsLauncher]: { WebDriverError: <html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
    at parseHttpResponse (/home/travis/build/ampproject/amphtml/node_modules/selenium-webdriver/lib/http.js:559:11)
    at Executor.execute (/home/travis/build/ampproject/amphtml/node_modules/selenium-webdriver/lib/http.js:468:26)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'WebDriverError', remoteStacktrace: '' }
23 01 2019 22:31:58.911:ERROR [SaucelabsLauncher]: { WebDriverError: Invalid message: <html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
```

*Meant this as a bug for SL, not for the tooling team.

**Comment by choumx** [comment]
Looks like they've noticed.

> Investigating - Tests are not starting in our Virtual Cloud. We are investigating. 
Jan 23, 14:43 PST

https://status.saucelabs.com/

**Comment by rsimha** [comment]
Things seem to have settled down over the past few months.
