### ISSUE TITLE
Error: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#20530]
This error came up on the 1% canary:

`Error: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.`

[go/ampe/CP2m1Ynq777zZw](http://go/ampe/CP2m1Ynq777zZw)

**Comment by choumx** [comment]
Stack trace:
```
TypeError: Failed to execute \'removeChild\' on \'Node\': parameter 1 is not of type \'Node\'.
    at TypeError (native)
    at ge (https://cdn.ampproject.org/rtv/001901242049580/v0.js:84:748)
    at amp-ad.b.xf (https://cdn.ampproject.org/rtv/001901242049580/v0.js:213:360)
    at https://cdn.ampproject.org/rtv/001901242049580/v0.js:189:343
    at mutate (https://cdn.ampproject.org/rtv/001901242049580/v0.js:316:185)
    at ym (https://cdn.ampproject.org/rtv/001901242049580/v0.js:504:228)
    at um.f.lh (https://cdn.ampproject.org/rtv/001901242049580/v0.js:503:268)
    at Yg.Ac (https://cdn.ampproject.org/rtv/001901242049580/v0.js:178:585)
    at Yg.jg (https://cdn.ampproject.org/rtv/001901242049580/v0.js:178:270)
    at https://cdn.ampproject.org/rtv/001901242049580/v0.js:356:767
```

**Comment by choumx** [comment]
Happens on `removeChild` in this function: https://github.com/ampproject/amphtml/blob/54ecd842c675c6acaf93170eb880188fa91d8399/src/static-template.js#L51-L63

Invoked from `prepareLoading_()` in custom-element.js: https://github.com/ampproject/amphtml/blob/54ecd842c675c6acaf93170eb880188fa91d8399/src/custom-element.js#L1600-L1602

We have a `devAssert` but those get stripped in prod. Looks like we need a graceful exit.

**Comment by choumx** [comment]
Dupe of #18212.
