### ISSUE TITLE
Single pass is intermittently failing on PR builds

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#21070]
https://travis-ci.org/ampproject/amphtml/jobs/498507626#L730-L742

```
.(node:8170) UnhandledPromiseRejectionWarning: Error: Cannot find module 'babel-plugin-transform-es2015-modules-commonjs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:32:19)
    at Object.exports.getGraph (/home/travis/build/ampproject/amphtml/build-system/single-pass.js:296:19)
    at Object.exports.getFlags (/home/travis/build/ampproject/amphtml/build-system/single-pass.js:142:18)
    at exports.singlePassCompile (/home/travis/build/ampproject/amphtml/build-system/single-pass.js:510:18)
    at compile (/home/travis/build/ampproject/amphtml/build-system/tasks/compile.js:150:12)
    at start (/home/travis/build/ampproject/amphtml/build-system/tasks/compile.js:48:7)
    at next (/home/travis/build/ampproject/amphtml/build-system/tasks/compile.js:67:22)
    at /home/travis/build/ampproject/amphtml/build-system/tasks/compile.js:55:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:8170) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

```

**Comment by rsimha** [comment]
This was related to Travis caching, and has since been fixed.
