### ISSUE TITLE
[amp-ad-custom] Cannot read property 'split' of null

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#21314]
```
Error: Cannot read property 'split' of null
    at https://raw.githubusercontent.com/ampproject/amphtml/1902271810270/node_modules/document-register-element/build/document-register-element.patched.js:501:6
    at call (https://raw.githubusercontent.com/ampproject/amphtml/1902271810270/node_modules/document-register-element/build/document-register-element.patched.js:773:14)
    at invoke_ (https://raw.githubusercontent.com/ampproject/amphtml/1902271810270/src/service/action-impl.js:561:2)
    at getRootNode (https://raw.githubusercontent.com/ampproject/amphtml/1902271810270/src/service/action-impl.js:708:19)
    at https://raw.githubusercontent.com/ampproject/amphtml/1902271810270/src/service/action-impl.js:758:4
    at https://raw.githubusercontent.com/ampproject/amphtml/1902271810270/src/service/action-impl.js:749:26
    at fetchJson (https://raw.githubusercontent.com/ampproject/amphtml/1902271810270/extensions/amp-ad/0.1/amp-ad-custom.js:91:8)
    at implementation_ (https://raw.githubusercontent.com/ampproject/amphtml/1902271810270/src/custom-element.js:598:12)
    at https://raw.githubusercontent.com/ampproject/amphtml/1902271810270/src/utils/promise.js:75:12
```

example page:
https://ewn.co.za/2019/03/07/shepherd-bushiri-visits-alexandra-after-blaze/amp

**Comment by erwinmombay** [comment]
looks like this is https://github.com/ampproject/amphtml/blob/1903070012530/src/url.js#L191 when `getCorsUrl` url parameter is `null`

seems to be coming from an `amp-ad` and when amp-a4a.js is able to retrieve the `adUrl`

**Comment by zhouyx** [comment]
Thank you @erwinmombay for the investigation. I checked the code looks like the `this.adUrl_`
is the `url` param that get passed to `appendEncodeParamStringToUrl`. 

https://github.com/ampproject/amphtml/blob/33c8b2da226d4644e9acd9498897821278e931c3/extensions/amp-a4a/0.1/amp-a4a.js#L1326-L1328

What I don't understand is that there is check for `this.adUrl_` beforehand.

**Comment by aghassemi** [comment]
This is happening way too often. Let's investigate. setting to P1

**Comment by jridgewell** [comment]
This is coming from https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad/0.1/amp-ad-custom.js#L90-L91

The issue is the `fullUrl` is null. From the test page, this happens when the element has neither a `data-slot` nor `data-url` attribute. We should add another user assertion that either a `data-url` or a `data-slot` is provided.
