### ISSUE TITLE
Cannot read property 'descriptionText' of undefined at descriptionText

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#21367]
```
Error: Cannot read property 'descriptionText' of undefined at descriptionText (https://raw.githubusercontent.com/ampproject/amphtml/1903070012530/extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js:418:21) at https://raw.githubusercontent.com/ampproject/amphtml/1903070012530/extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js:661:6 at showControls_ (https://raw.githubusercontent.com/ampproject/amphtml/1903070012530/extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js:643:8) at https://raw.githubusercontent.com/ampproject/amphtml/1903070012530/src/event-helper-listen.js:48:13
```

**Comment by erwinmombay** [comment]
dupe
