### ISSUE TITLE
[validator] Transformed AMP validation fails for amp-video-iframe and amp-image-slider

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#21941]
I'm currently [working on getting AMP Optimizer to produce valid optimized AMP](https://github.com/ampproject/amp-toolbox/pull/291). I've taken our samples from amp.dev as a test set. 

For two components I got validation errors. The same validation errors happen when loading the pages via the AMP Cache.

1. amp-image-slider ([example](https://validator.ampproject.org/#url=https%3A%2F%2Famp-toolbox.glitch.me%2Famp-img-slider.html))
```
Optimizer produces valid AMP amp-image-slider.html
  - Failed: Invalid AMP amp-image-slider.html

   [
    {
      "severity": "ERROR",
      "line": 49,
      "col": 161,
      "message": "Tag 'i-amphtml-sizer' is disallowed as child of tag 'amp-image-slider'. Child tag must be one of ['amp-img', 'div'].",
      "specUrl": "https://www.ampproject.org/docs/reference/components/amp-image-slider",
      "category": "AMP_TAG_PROBLEM",
      "code": "DISALLOWED_CHILD_TAG_NAME",
      "params": [
        "i-amphtml-sizer",
        "amp-image-slider",
        "['amp-img', 'div']"
      ]
    },
   ...
```

2. amp-video-iframe ([example](https://validator.ampproject.org/#url=https%3A%2F%2Famp-toolbox.glitch.me%2Famp-video-iframe.html))
```
2) Optimizer produces valid AMP amp-video-iframe.html
  - Failed: Invalid AMP amp-video-iframe.html

   [
    {
      "severity": "ERROR",
      "line": 5,
      "col": 223,
      "message": "The mandatory attribute 'placeholder' is missing in tag 'AMP-VIDEO-IFRAME > [placeholder]'.",
      "specUrl": "https://www.ampproject.org/docs/reference/components/amp-video-iframe",
      "category": "DISALLOWED_HTML",
      "code": "MANDATORY_ATTR_MISSING",
      "params": [
        "placeholder",
        "AMP-VIDEO-IFRAME > [placeholder]"
      ]
    },
    {
      "severity": "ERROR",
      "line": 5,
      "col": 223,
      "message": "The tag 'i-amphtml-sizer', a child tag of 'AMP-VIDEO-IFRAME with [placeholder]', does not satisfy the reference point 'AMP-VIDEO-IFRAME > [placeholder]'.",
      "specUrl": "https://www.ampproject.org/docs/reference/components/amp-video-iframe",
      "category": "AMP_TAG_PROBLEM",
      "code": "CHILD_TAG_DOES_NOT_SATISFY_REFERENCE_POINT_SINGULAR",
      "params": [
        "i-amphtml-sizer",
        "AMP-VIDEO-IFRAME with [placeholder]",
        "AMP-VIDEO-IFRAME > [placeholder]"
      ]
    }
  ]
      at UserContext.it (/Users/sbenz/Projects/amp-toolbox/packages/optimizer/spec/valid-amp/ValidAmpSpec.js:36:9)
      at process._tickCallback (internal/process/next_tick.js:68:7)

Executed 327 of 327 specs (2 FAILED) in 4 secs.
```

//cc @honeybadgerdontcare @Gregable

**Comment by honeybadgerdontcare** [comment]
Fixed in #22032 
Should be in production in one week
