### ISSUE TITLE
test-resources is Flaky

### ISSUE THREAD

**Issue by sriramkrish85** [ampproject/amphtml#2266]
Chromium 45.0.2454 (Ubuntu 0.0.0) Resources changeHeight attemptChangeHeight rules when element is in viewport should change height when above the vp and adjust scrolling FAILED
	ExpectationError: Unexpected call: getScrollHeight()
	    Expectation met: getScrollHeight([...]) at least once
	    Expectation met: getScrollHeight([...]) once
	    at Object.fail (/tmp/1210527a8dc6f4668059389c84828b39.browserify:26595:33 <- node_modules/sinon/lib/sinon/mock.js:449:0)
	    at Object.invokeMethod (/tmp/1210527a8dc6f4668059389c84828b39.browserify:26327:35 <- node_modules/sinon/lib/sinon/mock.js:181:0)
	    at Viewport.<anonymous> (/tmp/1210527a8dc6f4668059389c84828b39.browserify:26235:43 <- node_modules/sinon/lib/sinon/mock.js:89:0)
	    at Object._this6.vsync_.run.measure (/tmp/1210527a8dc6f4668059389c84828b39.browserify:45062:69 <- /home/travis/build/ampproject/amphtml/src/service/resources-impl.js:739:60)
	    at Context.<anonymous> (/tmp/1210527a8dc6f4668059389c84828b39.browserify:64989:12 <- /home/travis/build/ampproject/amphtml/test/functional/test-resources.js:710:11)
Chromium 45.0.2454 (Ubuntu 0.0.0): Executed 630 of 1549 (1 FAILED) (0 secs / 5.113 secs)
Chromium 45.0.2454 (Ubuntu 0.0.0) Resources changeHeight "after each" hook for "should change height when above the vp and adjust scrolling" FAILED
	ExpectationError: Expected getScrollTop([...]) once (never called)
	Expectation met: getRect([...]) at least once
	Expectation met: getScrollHeight([...]) at least once
	Expectation met: getScrollHeight([...]) once
	    at Object.fail (/tmp/1210527a8dc6f4668059389c84828b39.browserify:26595:33 <- node_modules/sinon/lib/sinon/mock.js:449:0)
	    at Object.verify (/tmp/1210527a8dc6f4668059389c84828b39.browserify:26275:39 <- node_modules/sinon/lib/sinon/mock.js:129:0)
	    at Context.<anonymous> (/tmp/1210527a8dc6f4668059389c84828b39.browserify:64799:18 <- /home/travis/build/ampproject/amphtml/test/functional/test-resources.js:521:17)
Chromium 45.0.2454 (Ubuntu 0.0.0): Executed 631 of 1549 (2 FAILED) (0 secs / 5.113 secs)
Chromium 45.0.2454 (Ubuntu 0.0.0)  "after each" hook for "should change height when above the vp and adjust scrolling" FAILED
	Error: You likely forgot to restore sinon timers (installed via sandbox.useFakeTimers).
	    at Context.<anonymous> (/tmp/1210527a8dc6f4668059389c84828b39.browserify:53117:11 <- /home/travis/build/ampproject/amphtml/test/_init_tests.js:95:10)
Chromium 45.0.2454 (Ubuntu 0.0.0): Executed 632 of 1549 (3 FAILED) (0 secs / 5.113 secs)
ium 45.0.2454 (Ubuntu 0.0.0): Executed 632 of 1549 (3 FAILED) (7.45 secs / 5.113 secs)
[22:07:42] 'test' errored after 32 s
[22:07:42] Error: 1
    at formatError (/home/travis/.nvm/versions/node/v5.7.0/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/home/travis/.nvm/versions/node/v5.7.0/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:90:13)
    at Gulp.emit (events.js:182:7)
    at Gulp.Orchestrator._emitTaskDone (/home/travis/build/ampproject/amphtml/node_modules/orchestrator/index.js:264:8)
    at /home/travis/build/ampproject/amphtml/node_modules/orchestrator/index.js:275:23
    at finish (/home/travis/build/ampproject/amphtml/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/home/travis/build/ampproject/amphtml/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (/home/travis/build/ampproject/amphtml/node_modules/karma/lib/server.js:333:7)
    at Server.<anonymous> (/home/travis/build/ampproject/amphtml/node_modules/karma/lib/server.js:344:9)
    at Server.g (events.js:273:16)
    at emitNone (events.js:85:20)
    at Server.emit (events.js:179:7)
    at emitCloseNT (net.js:1527:8)
    at _combinedTickCallback (node.js:374:13)
    at process._tickCallback (node.js:401:11)

**Comment by sriramkrish85** [comment]
https://travis-ci.org/ampproject/amphtml/builds/111588897

**Comment by rudygalfi** [comment]
Closed via #2267?
