### ISSUE TITLE
test-cookie-writer failing on master

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#22694]
The tests at `extensions/amp-analytics/0.1/test/test-cookie-writer.js` are failing and blocking the canary release.

https://travis-ci.org/ampproject/amphtml/jobs/541467573

The fix should cherry picked before the Canary + 1% are shipped and promoted.

```
amp-analytics.cookie-writer value
     
      ● should write cookie with custom expiration (zero value)
        Chrome 75.0.3770 (Linux 0.0.0)
      AssertionError: expected 'aCookie=testValue; path=/; domain=example.com; expires=Mon, 01 Jan 2018 08:00:00 GMT' to equal 'aCookie=testValue; path=/; expires=Mon, 01 Jan 2018 08:00:00 GMT'
          at [...]/amphtml/extensions/amp-analytics/0.1/test/test-cookie-writer.js:377:48

      ● should write cookie with custom expiration (negative value)
        Chrome 75.0.3770 (Linux 0.0.0)
      AssertionError: expected 'aCookie=testValue; path=/; domain=example.com; expires=Mon, 25 Dec 2017 08:00:00 GMT' to equal 'aCookie=testValue; path=/; expires=Mon, 25 Dec 2017 08:00:00 GMT'
          at [...]/amphtml/extensions/amp-analytics/0.1/test/test-cookie-writer.js:398:48

```

**Comment by gmajoulet** [comment]
cc @zhouyx @calebcordry @torch2424

**Comment by zhouyx** [comment]
Thank you for reporting and thanks @calebcordry for the quick fix. 
I've restarted the build of #22696, if couldn't fix the test, we could consider revert the PR. cc @jonathantyng-amp
