### ISSUE TITLE
E2E tests are missing `chromedriver` on Travis

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#23004]
Could something have changed with how packages are updated prior to `gulp e2e`?

**Logs:** https://travis-ci.org/ampproject/amphtml/jobs/550360338#L2009 (I re-ran this job a couple of times and saw the same error)

```js
e2e-tests.js: Running gulp e2e --nobuild --headless...
[16:24:33] Using gulpfile ~/build/ampproject/amphtml/gulpfile.js
[16:24:33] Starting 'e2e'...
[16:24:35] 'e2e' errored after 1.84 s
[16:24:35] Error: Cannot find module 'chromedriver'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.require (/home/travis/build/ampproject/amphtml/build-system/tasks/e2e/describes-e2e.js:18:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module._compile (/home/travis/build/ampproject/amphtml/build-system/tasks/e2e/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.newLoader [as .js] (/home/travis/build/ampproject/amphtml/build-system/tasks/e2e/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.require (/home/travis/build/ampproject/amphtml/build-system/tasks/e2e/helper.js:18:19)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module._compile (/home/travis/build/ampproject/amphtml/build-system/tasks/e2e/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.newLoader [as .js] (/home/travis/build/ampproject/amphtml/build-system/tasks/e2e/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at e2e (/home/travis/build/ampproject/amphtml/build-system/tasks/e2e/index.js:100:23)
    at taskWrapper (/home/travis/build/ampproject/amphtml/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:402:14)
    at runBound (domain.js:415:12)
    at asyncRunner (/home/travis/build/ampproject/amphtml/node_modules/async-done/index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
The command "unbuffer node build-system/pr-check/e2e-tests.js" exited with 1.
```

**Comment by cvializ** [comment]
I was getting a similar error for where the `puppeteer` module was missing when the visual diff task ran. Could there be a race condition between the modules getting installed and the task running?

**Comment by rsimha** [comment]
This is affecting all recent builds on `master` ([1](https://travis-ci.org/ampproject/amphtml/jobs/550355699#L1974), [2](https://travis-ci.org/ampproject/amphtml/jobs/550359045#L1974), [3](https://travis-ci.org/ampproject/amphtml/jobs/550362864#L1974), [4](https://travis-ci.org/ampproject/amphtml/jobs/550373961#L1974), [5](https://travis-ci.org/ampproject/amphtml/jobs/550382507#L1974)). Bumping to P1.

**Comment by cvializ** [comment]
I noticed the version in `package.json` is 74, but latest Chrome verison is 75 and they need to match. Maybe bumping the chromedriver version would fix it?

https://github.com/ampproject/amphtml/blob/d7a0dde9159a76ac63daa27dc813ac4001fa0136/build-system/tasks/e2e/package.json#L9

**Comment by cvializ** [comment]
`WebDriverError: unknown error: Chrome failed to start: exited abnormally`

https://travis-ci.org/ampproject/amphtml/jobs/550408597

**Comment by cvializ** [comment]
Tests are passing locally, I'm not sure why they'd fail in Travis

**Comment by rsimha** [comment]
> Tests are passing locally, I'm not sure why they'd fail in Travis @rsimha @estherkim

You could print any errors from `installPackages_()` as described in https://github.com/ampproject/amphtml/pull/23005#pullrequestreview-254157628

**Comment by cvializ** [comment]
I tried that but there are no errors and it installs correctly, but there are errors at runtime

**Comment by cvializ** [comment]
@rsimha or @estherkim can you take a look from here?
