### ISSUE TITLE
Flakiness in Saucelabs tests

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#2349]
Canary built just failed with a timeout error

```
$ gulp test --saucelabs --integration --compiled --fortesting
...
...
 Edge 12.10240.0 (Windows 10 0.0.0) Old Opacity Boilerplate should show the body when opacity boilerplate is used FAILED
    Error: Timeout waiting for expect body to become visible
       at poll (/tmp/6535654a054c86cdefe68960acbd1f1f.browserify:17735:11 <- /home/travis/build/ampproject/amphtml/testing/iframe.js:274:10)

...
...

Chrome Mobile 39.0.0 (Android 5.1.0): Executed 38 of 52 (skipped 14) SUCCESS (29.289 secs / 18.221 secs)
TOTAL: 1 FAILED, 263 SUCCESS
[22:01:30] 'test' errored after 1.65 min
[22:01:30] Error: 1
    at formatError (/home/travis/.nvm/versions/node/v5.7.0/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/home/travis/.nvm/versions/node/v5.7.0/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:90:13)
    at Gulp.emit (events.js:182:7)
    at Gulp.Orchestrator._emitTaskDone (/home/travis/build/ampproject/amphtml/node_modules/orchestrator/index.js:264:8)
    at /home/travis/build/ampproject/amphtml/node_modules/orchestrator/index.js:275:23
    at finish (/home/travis/build/ampproject/amphtml/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/home/travis/build/ampproject/amphtml/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners [as _onTimeout] (/home/travis/build/ampproject/amphtml/node_modules/karma/lib/server.js:333:7)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by cramforce** [comment]
The right way to debug something like this. Actually measure how long it usually takes, see if this is really a timeout. In that case we can basically only increase the timeout.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
