### ISSUE TITLE
Flakiness in tests - timeout exceeded

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#2354]
```
...
Chromium 45.0.2454 (Ubuntu 0.0.0) XHR Native should redirect fetch FAILED
	Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
Chromium 45.0.2454 (Ubuntu 0.0.0): Executed 1141 of 1607 (1 FAILED) (0 secs / 13.023 secs)
..
..
[00:23:02] 'test' errored after 1.28 min
[00:23:02] Error: 1
    at formatError (/home/travis/.nvm/versions/node/v5.7.0/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/home/travis/.nvm/versions/node/v5.7.0/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:90:13)
    at Gulp.emit (events.js:182:7)
    at Gulp.Orchestrator._emitTaskDone (/home/travis/build/ampproject/amphtml/node_modules/orchestrator/index.js:264:8)
    at /home/travis/build/ampproject/amphtml/node_modules/orchestrator/index.js:275:23
    at finish (/home/travis/build/ampproject/amphtml/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/home/travis/build/ampproject/amphtml/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (/home/travis/build/ampproject/amphtml/node_modules/karma/lib/server.js:333:7)
    at Server.<anonymous> (/home/travis/build/ampproject/amphtml/node_modules/karma/lib/server.js:344:9)
    at Server.g (events.js:273:16)
    at emitNone (events.js:85:20)
    at Server.emit (events.js:179:7)
    at emitCloseNT (net.js:1527:8)
    at _combinedTickCallback (node.js:374:13)
    at process._tickCallback (node.js:401:11)
The command "gulp test --compiled --fortesting" exited with 1.

```

**Comment by cramforce** [comment]
@dvoytenko: Can we switch away from https://httpbin.org
Maybe build a simple nodejs server https://github.com/ampproject/amphtml/blob/master/build-system/server.js#L50

**Comment by dvoytenko** [comment]
Yes - it'd be fine if we can find a good one. The key goal is for our polyfills to test against the CORS endpoints. We can also question the need of the end-to-end test here, but originally it was rather useful.

**Comment by mkhatib** [comment]
This is also related to #3101
