### ISSUE TITLE
Test state leakage due to the use of Object.defineProperty w/o restore

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#23689]
```
gulp unit --nobuild --headless --files={test/unit/test-viewport.js,test/unit/test-dom.js}
```

Running the above 2 tests on master branch will fail some tests:

```
FAILED TESTS:
  DOM

      ● isConnectedNode
        HeadlessChrome 76.0.3809 (Mac OS X 10.14.5)
      TypeError: a.attachShadow is not a function
          at Context.<anonymous> (Users/dinghongfei/Development/projects/amphtml/test/unit/test-dom.js:82:22)

      ● isConnectedNode (no Node.p.isConnected)
        HeadlessChrome 76.0.3809 (Mac OS X 10.14.5)
      TypeError: a.attachShadow is not a function
          at Context.<anonymous> (Users/dinghongfei/Development/projects/amphtml/test/unit/test-dom.js:111:24)
```

issue is first found here: https://github.com/ampproject/amphtml/pull/23671#issuecomment-518346305

**Comment by lannka** [comment]
Culprit is here:
https://github.com/ampproject/amphtml/blob/c7604ffa65b6ea70a85886229d18b67c601de4ea/test/unit/test-viewport.js#L1686-L1689

You might ask: but this is not changing the global window.Element 
It actually is:
https://github.com/ampproject/amphtml/blob/c7604ffa65b6ea70a85886229d18b67c601de4ea/testing/fake-dom.js#L54

**Comment by lannka** [comment]
We have other 40 usages of `Object.defineProperty` in tests. Most of them don't restore properly. Will clean up in follow-up PRs.

**Comment by lannka** [comment]
Let's clean the remaining Object.defineProperty and ban the usage.
