### ISSUE TITLE
Error: undefined is not an object (evaluating 'b.color')

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#24612]
This is the most common error seen in the RC build from the week of Sep 9-14:

```
Error: undefined is not an object (evaluating 'b.color')
    at https://raw.githubusercontent.com/ampproject/amphtml/1909141409590/extensions/amp-loader/0.1/amp-loader.js:177:12
    at https://raw.githubusercontent.com/ampproject/amphtml/1909141409590/extensions/amp-loader/0.1/amp-loader.js:411:4
    at element (https://raw.githubusercontent.com/ampproject/amphtml/1909141409590/src/loader.js:100:4)
```

**Comment by rsimha** [comment]
@sparhami, tagging you since you've updated `extensions/amp-loader/0.1/amp-loader.js` most often. Is this an issue that you're familiar with? Does it qualify as a release blocker?

**Comment by rsimha** [comment]
Here is a webpage on which this repros: https://www-stylecraze-com.cdn.ampproject.org/v/s/www.stylecraze.com/articles/how-to-choose-hair-color-for-brown-eyes/?amp=1&amp_js_v=0.1&usqp=mq331AQCKAE%3D

**Comment by rsimha** [comment]
Chatted with @sparhami and confirmed this isn't a release blocker.
