### ISSUE TITLE
Re-enable flaky story analytics integration tests

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#24639]
https://travis-ci.org/ampproject/amphtml/jobs/587116429
```
      IT => should send analytics event when navigating
        ✗ AssertionError: expected 'page-1' to equal 'page-2'
            at _callee2$ (home/travis/build/ampproject/amphtml/test/integration/test-amp-story-analytics.js:143:35)
            at tryCatch (home/travis/build/ampproject/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
            at Generator.invoke [as _invoke] (home/travis/build/ampproject/amphtml/node_modules/regenerator-runtime/runtime.js:303:22)
            at Generator.prototype.<computed> [as next] (home/travis/build/ampproject/amphtml/node_modules/regenerator-runtime/runtime.js:117:21)
            at asyncGeneratorStep (/tmp/637d6ae55d488af8c723bc9ffe1cea60.browserify.js:99961:103)
            at _next (/tmp/637d6ae55d488af8c723bc9ffe1cea60.browserify.js:99963:194)
```

https://travis-ci.org/ampproject/amphtml/jobs/587121381
```
DESCRIBE => amp-story analytics
  DESCRIBE => amp-story analytics
    DESCRIBE =>  
      IT => should send analytics event when entering bookend
        ✗ AssertionError: expected 'false' to equal 'true'
            at _callee3$ (home/travis/build/ampproject/amphtml/test/integration/test-amp-story-analytics.js:154:36)
            at tryCatch (home/travis/build/ampproject/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
            at Generator.invoke [as _invoke] (home/travis/build/ampproject/amphtml/node_modules/regenerator-runtime/runtime.js:303:22)
            at Generator.prototype.<computed> [as next] (home/travis/build/ampproject/amphtml/node_modules/regenerator-runtime/runtime.js:117:21)
            at asyncGeneratorStep (/tmp/d871b543b0ca58abfa25877e17f239cc.browserify.js:99961:103)
            at _next (/tmp/d871b543b0ca58abfa25877e17f239cc.browserify.js:99963:194)
```

**Comment by Enriqe** [comment]
Closed by #24644
