### ISSUE TITLE
Integration test `BTF within friendly frame or safe frame` flaking

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#24657]
Timing out on failures:

```
DESCRIBE => AMPHTML ad on non-AMP page (inabox)
  DESCRIBE => BTF within friendly frame or safe frame
    DESCRIBE =>  
      IT => should layout amp-img, amp-pixel, amp-analytics within friendly frame
        ✗ Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

Examples: [one](https://travis-ci.org/ampproject/amphtml/jobs/587220011#L2158), [two](https://travis-ci.org/ampproject/amphtml/jobs/587116429#L2111)

**Comment by rsimha** [comment]
This is happening on other platrforms too. Edge, for example: https://travis-ci.org/ampproject/amphtml/jobs/587583287#L2151

**Comment by rsimha** [comment]
More failures today:

```
DESCRIBE => AMPHTML ad on AMP Page
  DESCRIBE => BTF
    DESCRIBE =>  
      IT => should layout amp-img, amp-pixel, amp-analytics
        ✗ expected 1572571999563 to be below 1572571999387
        Error
           at AssertionError (node_modules/chai/chai.js:9449:7)
           at Assertion.prototype.assert (node_modules/chai/chai.js:239:7)
           at assertBelow (node_modules/chai/chai.js:1755:7)
           at methodWrapper (node_modules/chai/chai.js:7824:5)
           at Anonymous function (/home/travis/build/ampproject/amphtml/test/integration/test-amphtml-ads.js:407:5 <- /tmp/50a459a9b5d5963177cc2f7c0eb2eeb4.browserify.js:102328:5)
           at run (/home/travis/build/ampproject/amphtml/node_modules/core-js/modules/es6.promise.js:75:13 <- /tmp/50a459a9b5d5963177cc2f7c0eb2eeb4.browserify.js:27303:13)
           at Anonymous function (/home/travis/build/ampproject/amphtml/node_modules/core-js/modules/es6.promise.js:92:30 <- /tmp/50a459a9b5d5963177cc2f7c0eb2eeb4.browserify.js:27324:7)
           at flush (/home/travis/build/ampproject/amphtml/node_modules/core-js/modules/_microtask.js:18:9 <- /tmp/50a459a9b5d5963177cc2f7c0eb2eeb4.browserify.js:24372:9)
```

**Comment by zombifier** [comment]
Best way forward is to change them to e2e tests, but it requires #22270 to be implemented. As a bonus we also don't have to maintain separate test cases for amp-ad and inabox.

**Comment by lannka** [comment]
As now we have RequestBank in e2e, @powerivq do you think it's a good time to migrate these integration tests to e2e?
