### ISSUE TITLE
Issues implementing "dirty AMP" while using next.js

### ISSUE THREAD

**Issue by iliran11** [ampproject/amphtml#24679]
Hi,
I am using Next.js to build my AMP site using the feature that allows building [AMP hybrid](https://nextjs.org/docs#hybrid-amp-page) website.

I've been to google workshop and it was recommended to use "Dirty amp". Continue using amp components on non-AMP pages.

However, I can't use amp-components when using the hybrid feature on next.js, on the non-AMP page.

opened an issue on `next.js` but was refused that it's not a standard thing to do, contrary to what I was told in google workshop.

the issue in next.js:
https://github.com/zeit/next.js/issues/8548

Please your help.

**Comment by sebastianbenz** [comment]
Thanks for raising this @iliran11! I'll reply to your question in the next.js issue.

**Comment by skptricks** [comment]
AMP feature in next.js is not working. I have tried below source code :

import 'isomorphic-fetch'
import React from 'react'
import Link from 'next/link'

import { useAmp } from 'next/amp'
export const config = { amp: true };

const app = ({ stars }) => (

dddddddddddddssssssssssssssssssssss

First Post
) export default app
Error Message : ---
Cannot read property '__html' of undefined
TypeError: Cannot read property '__html' of undefined
at D:\sumitprojects\NextSimpleStarter.next\server\static\development\pages_document.js:819:76
at Array.map ()
at Head.render (D:\sumitprojects\NextSimpleStarter.next\server\static\development\pages_document.js:819:27)
at processChild (D:\sumitprojects\NextSimpleStarter\node_modules\react-dom\cjs\react-dom-server.node.development.js:3171:18)
at resolve (D:\sumitprojects\NextSimpleStarter\node_modules\react-dom\cjs\react-dom-server.node.development.js:3013:5)
at ReactDOMServerRenderer.render (D:\sumitprojects\NextSimpleStarter\node_modules\react-dom\cjs\react-dom-server.node.development.js:3436:22)
at ReactDOMServerRenderer.read (D:\sumitprojects\NextSimpleStarter\node_modules\react-dom\cjs\react-dom-server.node.development.js:3395:29)
at Object.renderToStaticMarkup (D:\sumitprojects\NextSimpleStarter\node_modules\react-dom\cjs\react-dom-server.node.development.js:3969:27)
at renderDocument (D:\sumitprojects\NextSimpleStarter\node_modules\next-server\dist\server\render.js:89:18)
at Object.renderToHTML (D:\sumitprojects\NextSimpleStarter\node_modules\next-server\dist\server\render.js:299:16)
