### ISSUE TITLE
Error: Cannot read property 'removeAttribute' of null

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#25377]
May be related to https://github.com/ampproject/amphtml/issues/22533?

```
Error: Cannot read property 'removeAttribute' of null
    at removeAttribute (https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/style.js:235:4)
    at https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js:1041:8
    at https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/service/resources-impl.js:632:8
    at https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/service/vsync-impl.js:470:16
    at callTask_ (https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/service/vsync-impl.js:426:8)

**Comment by jridgewell** [comment]
http://go/ampe/CPGmtuuw-8ybVw
