### ISSUE TITLE
Error: null is not an object (evaluating 'a.getBoundingClientRect')

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#25379]
```
Error: null is not an object (evaluating 'a.getBoundingClientRect')
    at getBoundingClientRect (https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/service/viewport/viewport-binding-ios-embed-wrapper.js:252:23)
    at https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/service/viewport/viewport-impl.js:311:11
    at https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/service/resources-impl.js:844:38
    at state (https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/service/vsync-impl.js:470:25)
    at tasks (https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/service/vsync-impl.js:418:23)

**Comment by jridgewell** [comment]
http://ampe/COqZxY35pNOLUg
