### ISSUE TITLE
Error: undefined is not an object (evaluating 'this.implementation_.prerenderAllowed')

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#25381]
I think this is because of accessing services in the component's constructor, when it's not yet possible to get. It an error happens in the constructor, then the implementation won't be set.

```
Error: undefined is not an object (evaluating 'this.implementation_.prerenderAllowed')
    at prerenderAllowed (https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/custom-element.js:1013:13)
    at https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/service/resource.js:652:11
    at https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/service/resources-impl.js:416:4
    at buildOrScheduleBuildForResource_ (https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/service/resources-impl.js:1229:8)
    at discoverWork_ (https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/service/resources-impl.js:1895:36)
    at https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/finite-state-machine.js:72:6
    at https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/service/resources-impl.js:827:42
    at https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/service/resources-impl.js:158:42
    at https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/pass.js:109:4
    at https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/pass.js:55:6
    at https://raw.githubusercontent.com/ampproject/amphtml/1910302211460/src/service/timer-impl.js:83:8

**Comment by jridgewell** [comment]
http://go/ampe/CM_o6sDawNfppgE
