### ISSUE TITLE
Fix all tests in `extensions/amp-a4a/0.1/test/test-amp-a4a.js` that rely on a global `sinon` sandbox

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#25548]
In #23842 and #25587, we're eliminating the use of the global `sinon` sandbox in our tests. The new way to access the sandbox is via `window.sandbox` for legacy `describe` tests, and via `env.sandbox` for `describes` tests. (There's a new presubmit check to enforce this.)

When the cleanup was done for `extensions/amp-a4a/0.1/test/test-amp-a4a.js`, a few tests are no longer passing, likely because they depended on the presence of a global `sinon` sandbox in some indirect way. These tests will be skipped by #25587.

This issue is to make sure the tests are fixed and unskipped.
 
/cc @ampproject/wg-ads

**Comment by jeffkaufman** [comment]
Is the AMP approach that the people working on the migration will fix and unskip the tests?  Or that people who care about the code will fix them?

**Comment by rsimha** [comment]
> Is the AMP approach that the people working on the migration will fix and unskip the tests? Or that people who care about the code will fix them?

The typical approach is for whoever is doing the migration (me) to make an honest effort to fix all tests affected by the migration. In this case, those efforts failed because the failing tests seem to be relying on a global sandbox with no readily apparent root cause. The original authors of the tests are in a better position to figure out what's going on here.

**Comment by rsimha** [comment]
**Failure logs:**

```
rsimha@bobdylan (2019-11-14-GlobalSinon):~/src/amphtml$ gulp unit --headless --files extensions/amp-a4a/0.1/test/test-amp-a4a.js
[14:41:19] Using gulpfile ~/src/amphtml/gulpfile.js
[14:41:19] Starting 'unit'...
[14:41:19] Run gulp help to see a list of all test flags.
[14:41:19] ⤷ Use --nohelp to silence these messages.
[14:41:19] ⤷ Use --local_changes to run unit tests from files commited to the local branch.
[14:41:19] Running tests against minified code.
[14:41:19] --headless: Running tests in a headless Chrome window.
[14:41:19] --files: Running tests in the file(s): extensions/amp-a4a/0.1/test/test-amp-a4a.js
[14:41:19] All packages in node_modules are up to date.
[14:41:21] Recompiled all CSS files into build/ (2.308 s)
[14:41:22] Compiled Jison parsers into build/parsers/ (518 ms)
[14:41:22] Started AMP Test Server at http://localhost:8081
[14:41:22] Running gulp unit. Press Ctrl + C to cancel...
Deprecated private createPreprocessor() API
[14:41:22] Running tests locally...

START:
[14:41:24] Transforming tests with browserify...
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

[14:41:50] Done. Running tests...


[14:41:50] HeadlessChrome 78.0.3904 (Linux 0.0.0): STARTED
  amp-a4a
    ● should set height/width on iframe matching header value
    ads are visible
      ● for SafeFrame rendering case
      ● for ios defaults to SafeFrame rendering
      ● for cached content iframe rendering case
      ● populates postAdResponseExperimentFeatures
      ● for A4A friendly iframe rendering case
      ● detachedCallback should destroy FIE and detach frame
      ● for A4A layout should resolve once FIE is created
      ● should fire amp-analytics triggers for lifecycle events (skipped)
      ● should update embed visibility
      ● for requests from insecure HTTP pages
      ● should fire amp-analytics triggers (skipped)
      ● should not fire amp-analytics triggers without config
      ● should insert an amp-analytics element
      ● should not insert an amp-analytics element if config is null
    layoutCallback cancels properly
      ● when unlayoutCallback called after adPromise
      ● when unlayoutCallback called before renderAmpCreative_
    cross-domain rendering
      #renderViaIframeGet
        ● should attach a client cached iframe when set
        ● should apply sandbox when sandboxHTMLCreativeFrame is true
        ● should not apply sandbox when sandboxHTMLCreativeFrame false
        ● should set feature policy for sync-xhr
      illegal render mode value
        ● should render via cached iframe
        ● should fire amp-analytics triggers for illegal render modes
      #renderViaNameFrame
        ● should attach a NameFrame when header is set
        ● should make only one NameFrame even if onLayoutMeasure called multiple times
        ● should apply sandbox when sandboxHTMLCreativeFrame is true
        ● should not apply sandbox when sandboxHTMLCreativeFrame false
        ● should not attach a NameFrame when header is 
        ● should not attach a NameFrame when header is client_cache
        ● should not attach a NameFrame when header is safeframe
        ● should not attach a NameFrame when header is some_random_thing
        ● should fire amp-analytics triggers for lifecycle stages
      #renderViaSafeFrame
        ● should attach a SafeFrame when header is set
        ● should use safeframe version header value
        ● should make only one SafeFrame even if onLayoutMeasure called multiple times
        ● should apply sandbox when sandboxHTMLCreativeFrame is true
        ● should not apply sandbox when sandboxHTMLCreativeFrame false
        ● should not attach a SafeFrame when header is 
        ● should not attach a SafeFrame when header is client_cache
        ● should not attach a SafeFrame when header is nameframe
        ● should not attach a SafeFrame when header is some_random_thing
        ● should reset state to null on unlayoutCallback
        ● should fire amp-analytics triggers for lifecycle stages
    cross-domain vs A4A
      ● should not use nameframe if creative is A4A
      ● should not use nameframe even if onLayoutMeasure called multiple times
      ● should not use safeframe if creative is A4A
      ● should not use safeframe even if onLayoutMeasure called multiple times
    #onLayoutMeasure
      ● resumeCallback calls onLayoutMeasure
      ● resumeCallback does not call onLayoutMeasure for FIE
      ● resumeCallback w/ measure required no onLayoutMeasure
      ● should run end-to-end and render in friendly iframe
      ● should update priority for non AMP if in experiment
      ● should prefetch amp images
      ● must not be position:fixed
      ● does not initialize promise chain 0 height/width
      ● #layoutCallback valid AMP
      ● #layoutCallback not valid AMP
      ● #layoutCallback AMP render fail, recover non-AMP
      ● should run end-to-end in the presence of an XHR error
ERROR: 'Assertion failed'
    The test "amp-a4a #onLayoutMeasure should use adUrl from onNetworkFailure" resulted in a call to console.error. (See above line.)
    ⤷ If the error is not expected, fix the code that generated the error.
    ⤷ If the error is expected (and synchronous), use the following pattern to wrap the test code that generated the error:
        'allowConsoleError(() => { <code that generated the error> });'
    ⤷ If the error is expected (and asynchronous), use the following pattern at the top of the test:
        'expectAsyncConsoleError(<string or regex>[, <number of times the error message repeats>]);'
ERROR: '[amp-a4a] Error: amp-a4a: adsense: Assertion failed'
    The test "amp-a4a #onLayoutMeasure should use adUrl from onNetworkFailure" resulted in a call to console.error. (See above line.)
    ⤷ If the error is not expected, fix the code that generated the error.
    ⤷ If the error is expected (and synchronous), use the following pattern to wrap the test code that generated the error:
        'allowConsoleError(() => { <code that generated the error> });'
    ⤷ If the error is expected (and asynchronous), use the following pattern at the top of the test:
        'expectAsyncConsoleError(<string or regex>[, <number of times the error message repeats>]);'
      ● should use adUrl from onNetworkFailure
ERROR: 'Assertion failed'
    The test "amp-a4a #onLayoutMeasure should not execute frame GET if disabled via onNetworkFailure" resulted in a call to console.error. (See above line.)
    ⤷ If the error is not expected, fix the code that generated the error.
    ⤷ If the error is expected (and synchronous), use the following pattern to wrap the test code that generated the error:
        'allowConsoleError(() => { <code that generated the error> });'
    ⤷ If the error is expected (and asynchronous), use the following pattern at the top of the test:
        'expectAsyncConsoleError(<string or regex>[, <number of times the error message repeats>]);'
      ● should not execute frame GET if disabled via onNetworkFailure
      ● should handle XHR error when resolves before layoutCallback
      ● should handle XHR error when resolves after layoutCallback
      ● should collapse 204
      ● should collapse 500
      ● should collapse empty body
      ● should collapse no fill header
      ● should process safeframe version header properly
      ● should ignore invalid safeframe version header
      delay request experiment
        ● should delay request until within renderOutsideViewport
        ● should delay request until numeric value
    #preconnectCallback
      ● validate
    #getAmpAdMetadata
      ● should parse metadata
      ● should parse metadata with wrong opening tag
      ● should return null if metadata opening tag is (truly) wrong
      ● should return null if missing ampRuntimeUtf16CharOffsets
      ● should return null if invalid extensions
      ● should return null if non-array stylesheets
      ● should return null if invalid stylesheet object
      ● should not include amp images if not an array
      ● should tolerate missing images
      ● should limit to 5 images
      ● should throw due to missing CTA type
      ● should not throw due to missing outlink
      ● should set appropriate attributes and return metadata object
    #maybeValidateAmpCreative
      ● should pass verification with story ad
      ● should throw due to invalid AMP creative with story ad
    #renderOutsideViewport
      ● should return false if throttled
      ● should return true if throttled, but AMP creative
      ● should return 1.25 if prefer-viewability-over-views
    #renderAmpCreative_
      ● should render correctly
      ● should render correctly in ampdoc-fie mode
    #getLayoutPriority
      with shadow AmpDoc
         
          ● should return priority of 1
      with single AmpDoc
         
          ● should return priority of 2
    #unlayoutCallback
      ● verify state reset
      ● attemptChangeSize reverts
      ● verify cancelled promise
      consent integration
        ● should delay ad url by getConsentPolicyState
        ● should not wait on consent if no policy
        ● should pass consent state to getAdUrl
ERROR: '[amp-a4a] Error determining consent string Error: consent err!'
    The test "amp-a4a #unlayoutCallback consent integration should return UNKNOWN if consent exception" resulted in a call to console.error. (See above line.)
    ⤷ If the error is not expected, fix the code that generated the error.
    ⤷ If the error is expected (and synchronous), use the following pattern to wrap the test code that generated the error:
        'allowConsoleError(() => { <code that generated the error> });'
    ⤷ If the error is expected (and asynchronous), use the following pattern at the top of the test:
        'expectAsyncConsoleError(<string or regex>[, <number of times the error message repeats>]);'
        ● should return UNKNOWN if consent exception
      protectFunctionWrapper
        ● works properly with no error
        ● handles error properly
        ● returns undefined if error thrown in error handler
    error handler
      ● should rethrow cancellation
      ● should create an error if needed
      ● should configure ignoreStack when specified
      ● should route error to user.error in dev mode
      ● should route error to user.warn in prod mode
      ● should send an expected error in prod mode with sampling
      ● should NOT send an expected error in prod mode with sampling
    #assignAdUrlToError
      ● should attach info to error correctly
      ● should not modify if no query string
    #extractSize
      ● should return a size
      ● should return no size
    refresh
      ● should effectively reset the slot and invoke given callback
      ● should fire an analytics event when refreshing
      ● should fail gracefully if race conditions nullify adPromise
    buildCallback
      ● should set isSinglePageStoryAd to false
      ● should set isSinglePageStoryAd to true
    canonical AMP
      ● shouldPreferentialRenderWithoutCrypto returns false by default
      preferential rendering
        ● by default not allowed if crypto signature present but no SSL
        ● allowed if crypto signature present, no SSL, and overrided shouldPreferentialRenderWithoutCrypto
        ● not allowed if no crypto signature present
  AmpA4a-RTC
     
      #tryExecuteRealTimeConfig
        ● should not execute if RTC never imported
        ● should log user error if RTC Config set but RTC not supported
      #getCustomRealTimeConfigMacros_
        ● should return empty object
      #inNonAmpPreferenceExp
        ● {}
        ● {"type":"doubleclick","prefVal":true,"expected":true}
        ● {"type":"adsense","prefVal":true,"expected":true}
        ● {"type":"adsense","prefVal":"true","expected":true}
        ● {"type":"doubleclick","prefVal":false}
        ● {"type":"adsense","prefVal":false}
        ● {"type":"doubleclick"}
        ● {"type":"doubleclick","prefVal":""}
        ● {"type":"otherNetwork","prefVal":true}
      single pass experiments
        ● should add single pass id
        ● should add multi pass id
        ● should not add any single pass experiment ids


[14:42:00] HeadlessChrome 78.0.3904 (Linux 0.0.0): Executed 137 of 139 (Skipped 2) 8 FAILED


Finished in 9.451 secs / 5.311 secs @ 14:42:00 GMT-0500 (Eastern Standard Time)

SUMMARY:
● 129 tests completed
○ 2 tests skipped
● 8 tests failed

FAILED TESTS:
  amp-a4a
    cross-domain rendering
      illegal render mode value
        ● should render via cached iframe
          HeadlessChrome 78.0.3904 (Linux 0.0.0)
        AssertionError: expected triggerAnalyticsEvent to have been called with arguments <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>, ad-request-start, { time: typeOf("number") }
        Call 1:
        <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>
        ad-request-start
        { time: 29 } { time: typeOf("number") } 
        Call 2:
        <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>
        ad-response-end ad-request-start 
        { time: 29 } { time: typeOf("number") } 
        Call 3:
        <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>
        ad-render-start ad-request-start 
        { time: 29 } { time: typeOf("number") } 
        Call 4:
        <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>
        ad-render-end ad-request-start 
        { time: 31 } { time: typeOf("number") } 
        Call 5:
        <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>
        ad-iframe-loaded ad-request-start 
        { time: 46 } { time: typeOf("number") } 
            at http://localhost:9876/usr/local/google/home/rsimha/src/amphtml/extensions/amp-a4a/0.1/test/test-amp-a4a.js:350:48
            at Array.forEach (<anonymous>)
            at verifyA4aAnalyticsTriggersWereFired (usr/local/google/home/rsimha/src/amphtml/extensions/amp-a4a/0.1/test/test-amp-a4a.js:349:8)
            at _callee23$ (usr/local/google/home/rsimha/src/amphtml/extensions/amp-a4a/0.1/test/test-amp-a4a.js:755:9)
            at tryCatch (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
            at Generator.invoke [as _invoke] (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:303:22)
            at Generator.prototype.<computed> [as next] (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:117:21)
            at tryCatch (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
            at invoke (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:155:20)
            at http://localhost:9876/usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:165:13

        ● should fire amp-analytics triggers for illegal render modes
          HeadlessChrome 78.0.3904 (Linux 0.0.0)
        AssertionError: expected triggerAnalyticsEvent to have been called with arguments <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>, ad-request-start, { time: typeOf("number") }
        Call 1:
        <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>
        ad-request-start
        { time: 10 } { time: typeOf("number") } 
        Call 2:
        <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>
        ad-response-end ad-request-start 
        { time: 10 } { time: typeOf("number") } 
        Call 3:
        <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>
        ad-render-start ad-request-start 
        { time: 11 } { time: typeOf("number") } 
        Call 4:
        <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>
        ad-render-end ad-request-start 
        { time: 13 } { time: typeOf("number") } 
        Call 5:
        <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>
        ad-iframe-loaded ad-request-start 
        { time: 29 } { time: typeOf("number") } 
            at http://localhost:9876/usr/local/google/home/rsimha/src/amphtml/extensions/amp-a4a/0.1/test/test-amp-a4a.js:350:48
            at Array.forEach (<anonymous>)
            at verifyA4aAnalyticsTriggersWereFired (usr/local/google/home/rsimha/src/amphtml/extensions/amp-a4a/0.1/test/test-amp-a4a.js:349:8)
            at _callee24$ (usr/local/google/home/rsimha/src/amphtml/extensions/amp-a4a/0.1/test/test-amp-a4a.js:768:16)
            at tryCatch (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
            at Generator.invoke [as _invoke] (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:303:22)
            at Generator.prototype.<computed> [as next] (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:117:21)
            at tryCatch (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
            at invoke (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:155:20)
            at http://localhost:9876/usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:165:13

      #renderViaNameFrame
        ● should fire amp-analytics triggers for lifecycle stages
          HeadlessChrome 78.0.3904 (Linux 0.0.0)
        AssertionError: expected triggerAnalyticsEvent to have been called with arguments <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>, ad-request-start, { time: typeOf("number") }
        Call 1:
        <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>
        ad-request-start
        { time: 10 } { time: typeOf("number") } 
        Call 2:
        <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>
        ad-response-end ad-request-start 
        { time: 10 } { time: typeOf("number") } 
        Call 3:
        <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>
        ad-render-start ad-request-start 
        { time: 11 } { time: typeOf("number") } 
        Call 4:
        <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>
        ad-render-end ad-request-start 
        { time: 13 } { time: typeOf("number") } 
        Call 5:
        <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>
        ad-iframe-loaded ad-request-start 
        { time: 33 } { time: typeOf("number") } 
            at http://localhost:9876/usr/local/google/home/rsimha/src/amphtml/extensions/amp-a4a/0.1/test/test-amp-a4a.js:350:48
            at Array.forEach (<anonymous>)
            at verifyA4aAnalyticsTriggersWereFired (usr/local/google/home/rsimha/src/amphtml/extensions/amp-a4a/0.1/test/test-amp-a4a.js:349:8)
            at _callee30$ (usr/local/google/home/rsimha/src/amphtml/extensions/amp-a4a/0.1/test/test-amp-a4a.js:863:16)
            at tryCatch (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
            at Generator.invoke [as _invoke] (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:303:22)
            at Generator.prototype.<computed> [as next] (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:117:21)
            at tryCatch (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
            at invoke (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:155:20)
            at http://localhost:9876/usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:165:13

      #renderViaSafeFrame
        ● should fire amp-analytics triggers for lifecycle stages
          HeadlessChrome 78.0.3904 (Linux 0.0.0)
        AssertionError: expected triggerAnalyticsEvent to have been called with arguments <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>, ad-request-start, { time: typeOf("number") }
        Call 1:
        <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>
        ad-request-start
        { time: 12 } { time: typeOf("number") } 
        Call 2:
        <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>
        ad-response-end ad-request-start 
        { time: 12 } { time: typeOf("number") } 
        Call 3:
        <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>
        ad-render-start ad-request-start 
        { time: 13 } { time: typeOf("number") } 
        Call 4:
        <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>
        ad-render-end ad-request-start 
        { time: 15 } { time: typeOf("number") } 
        Call 5:
        <amp-a4a width="200" height="50" type="adsense"><div fallback=""><di[...]</amp-a4a>
        ad-iframe-loaded ad-request-start 
        { time: 41 } { time: typeOf("number") } 
            at http://localhost:9876/usr/local/google/home/rsimha/src/amphtml/extensions/amp-a4a/0.1/test/test-amp-a4a.js:350:48
            at Array.forEach (<anonymous>)
            at verifyA4aAnalyticsTriggersWereFired (usr/local/google/home/rsimha/src/amphtml/extensions/amp-a4a/0.1/test/test-amp-a4a.js:349:8)
            at _callee38$ (usr/local/google/home/rsimha/src/amphtml/extensions/amp-a4a/0.1/test/test-amp-a4a.js:983:16)
            at tryCatch (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
            at Generator.invoke [as _invoke] (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:303:22)
            at Generator.prototype.<computed> [as next] (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:117:21)
            at tryCatch (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
            at invoke (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:155:20)
            at http://localhost:9876/usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:165:13

    #onLayoutMeasure
      ● should run end-to-end and render in friendly iframe
        HeadlessChrome 78.0.3904 (Linux 0.0.0)
      AssertionError: expected spy to have been called exactly once, but it was called 0 times
          at _callee46$ (usr/local/google/home/rsimha/src/amphtml/extensions/amp-a4a/0.1/test/test-amp-a4a.js:1276:7)
          at tryCatch (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
          at Generator.invoke [as _invoke] (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:303:22)
          at Generator.prototype.<computed> [as next] (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:117:21)
          at tryCatch (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
          at invoke (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:155:20)
          at http://localhost:9876/usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:165:13

      ● #layoutCallback valid AMP
        HeadlessChrome 78.0.3904 (Linux 0.0.0)
      AssertionError: expected spy to have been called exactly once, but it was called 0 times
          at executeLayoutCallbackTest$ (usr/local/google/home/rsimha/src/amphtml/extensions/amp-a4a/0.1/test/test-amp-a4a.js:1457:9)
          at tryCatch (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
          at Generator.invoke [as _invoke] (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:303:22)
          at Generator.prototype.<computed> [as next] (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:117:21)
          at tryCatch (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
          at invoke (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:155:20)
          at http://localhost:9876/usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:165:13

      ● should use adUrl from onNetworkFailure
        HeadlessChrome 78.0.3904 (Linux 0.0.0)
      AssertionError: http://iframe.localhost:9876/test/fixtures/served/iframe.html?args&__amp_source_origin=about%3Asrcdoc: expected false to be true
          at _callee52$ (usr/local/google/home/rsimha/src/amphtml/extensions/amp-a4a/0.1/test/test-amp-a4a.js:1543:7)
          at tryCatch (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
          at Generator.invoke [as _invoke] (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:303:22)
          at Generator.prototype.<computed> [as next] (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:117:21)
          at tryCatch (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
          at invoke (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:155:20)
          at http://localhost:9876/usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:165:13

      ● should not execute frame GET if disabled via onNetworkFailure
        HeadlessChrome 78.0.3904 (Linux 0.0.0)
      AssertionError: expected <iframe src="http://iframe.localhost:9876/test/fixtures/served/iframe.html?args&amp;__amp_source_origin=about%3Asrcdoc" name="{&quot;width&quot;:200,&quot;height&quot;:50,&quot;_context&quot;:{&quot;ampcontextVersion&quot;:&quot;$internalRuntimeVersion$&quot;,&quot;ampcontextFilepath&quot;:&quot;https://3p.ampproject.net/$internalRuntimeVersion$/ampcontext-v0.js&quot;,&quot;sourceUrl&quot;:&quot;about:srcdoc&quot;,&quot;referrer&quot;:&quot;&quot;,&quot;canonicalUrl&quot;:&quot;about:srcdoc&quot;,&quot;pageViewId&quot;:&quot;315&quot;,&quot;location&quot;:{&quot;href&quot;:&quot;http://localhost:9876/context.html&quot;},&quot;startTime&quot;:1573760516664,&quot;tagName&quot;:&quot;AMP-A4A&quot;,&quot;mode&quot;:{&quot;localDev&quot;:true,&quot;development&quot;:false,&quot;minified&quot;:false,&quot;lite&quot;:false,&quot;test&quot;:true,&quot;version&quot;:&quot;$internalRuntimeVersion$&quot;,&quot;rtvVersion&quot;:&quot;$internalRuntimeVersion$&quot;},&quot;canary&quot;:false,&quot;hidden&quot;:false,&quot;initialLayoutRect&quot;:{&quot;left&quot;:0,&quot;top&quot;:0,&quot;width&quot;:200,&quot;height&quot;:50},&quot;initialIntersection&quot;:null,&quot;domFingerprint&quot;:&quot;600900211&quot;,&quot;experimentToggles&quot;:{},&quot;sentinel&quot;:&quot;1-2517607743578434400&quot;}}" height="50" width="200" data-amp-3p-sentinel="1-2517607743578434400" allow="sync-xhr 'none';" frameborder="0" allowfullscreen="" allowtransparency="" scrolling="no" marginwidth="0" marginheight="0" sandbox="allow-top-navigation-by-user-activation allow-popups-to-escape-sandbox allow-forms allow-modals allow-pointer-lock allow-popups allow-same-origin allow-scripts" class="i-amphtml-fill-content"></iframe> to be falsy
          at _callee53$ (usr/local/google/home/rsimha/src/amphtml/extensions/amp-a4a/0.1/test/test-amp-a4a.js:1576:7)
          at tryCatch (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
          at Generator.invoke [as _invoke] (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:303:22)
          at Generator.prototype.<computed> [as next] (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:117:21)
          at tryCatch (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
          at invoke (usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:155:20)
          at http://localhost:9876/usr/local/google/home/rsimha/src/amphtml/node_modules/regenerator-runtime/runtime.js:165:13

[14:42:00] Stopped server at http://localhost:8081
[14:42:00] ERROR: Karma test failed with exit code 1
[14:42:00] Finished 'unit' after 41 s
rsimha@bobdylan (2019-11-14-GlobalSinon):~/src/amphtml$ 
```

**Comment by rsimha** [comment]
Found a fix. Some tests were using a global matcher in addition to the global sandbox object. There's nothing left to do.
