### ISSUE TITLE
Fix all tests in `test/unit/test-pass.js` that rely on a global `sinon` sandbox

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#25592]
In #23842 and #25587, we're eliminating the use of the global `sinon` sandbox in our tests. The new way to access the sandbox is via `window.sandbox` for legacy `describe` tests, and via `env.sandbox` for `describes` tests. (There's a new presubmit check to enforce this.)

When the cleanup was done for `test/unit/test-pass.js` tests, a suite of tests is no longer passing, likely because it depended on the presence of a global `sinon` sandbox in some indirect way. These tests will be skipped by #25587.

This issue is to make sure the tests are fixed and unskipped.
 
/cc @ampproject/wg-runtime

**Comment by rsimha** [comment]
**Failure logs:**

```
rsimha@bobdylan (2019-11-14-GlobalSinon):~/src/amphtml$ gulp unit --headless --files test/unit/test-pass.js
[14:51:03] Using gulpfile ~/src/amphtml/gulpfile.js
[14:51:03] Starting 'unit'...
[14:51:03] Run gulp help to see a list of all test flags.
[14:51:03] ⤷ Use --nohelp to silence these messages.
[14:51:03] ⤷ Use --local_changes to run unit tests from files commited to the local branch.
[14:51:03] Running tests against minified code.
[14:51:03] --headless: Running tests in a headless Chrome window.
[14:51:03] --files: Running tests in the file(s): test/unit/test-pass.js
[14:51:03] All packages in node_modules are up to date.
[14:51:06] Recompiled all CSS files into build/ (2.641 s)
[14:51:07] Compiled Jison parsers into build/parsers/ (568 ms)
[14:51:07] Started AMP Test Server at http://localhost:8081
[14:51:07] Running gulp unit. Press Ctrl + C to cancel...
Deprecated private createPreprocessor() API
[14:51:07] Running tests locally...

START:
[14:51:09] Transforming tests with browserify...
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

[14:51:33] Done. Running tests...


[14:51:34] HeadlessChrome 78.0.3904 (Linux 0.0.0): STARTED
  Pass
    ● handler called
ERROR: 'ExpectationError: Unexpected call: delay(function () {}, 30000)'
    The test "Pass handler called" resulted in a call to console.error. (See above line.)
    ⤷ If the error is not expected, fix the code that generated the error.
    ⤷ If the error is expected (and synchronous), use the following pattern to wrap the test code that generated the error:
        'allowConsoleError(() => { <code that generated the error> });'
    ⤷ If the error is expected (and asynchronous), use the following pattern at the top of the test:
        'expectAsyncConsoleError(<string or regex>[, <number of times the error message repeats>]);'
    ● "after each" hook for "handler called"


[14:51:36] HeadlessChrome 78.0.3904 (Linux 0.0.0): Executed 2 of 2 (Skipped 0) 2 FAILED


Finished in 2.152 secs / 2.139 secs @ 14:51:36 GMT-0500 (Eastern Standard Time)

SUMMARY:
● 0 tests completed
● 2 tests failed

FAILED TESTS:
  Pass
    ● handler called
      HeadlessChrome 78.0.3904 (Linux 0.0.0)
    ExpectationError: Unexpected call: delay(function () {}, 0)
        Expected delay(match(undefined), 0) once (never called)
        at Object.fail (/tmp/node_modules/sinon/lib/sinon/mock-expectation.js:309:1)
        at Object.invokeMethod (/tmp/node_modules/sinon/lib/sinon/mock.js:196:1)
        at Timer.delay (/tmp/node_modules/sinon/lib/sinon/mock.js:72:1)
        at Pass.schedule (usr/local/google/home/rsimha/src/amphtml/src/pass.js:94:37)
        at Context.<anonymous> (usr/local/google/home/rsimha/src/amphtml/test/unit/test-pass.js:52:10)

    ● "after each" hook for "handler called"
      HeadlessChrome 78.0.3904 (Linux 0.0.0)
    Unexpected call: delay(function () {}, 0) at Pass.schedule (http://localhost:9876/usr/local/google/home/rsimha/src/amphtml/src/pass.js:94:37)
    Unexpected call: delay(function () {}, 30000) at Pass.schedule (http://localhost:9876/usr/local/google/home/rsimha/src/amphtml/src/pass.js:94:37)
    Expected delay(match(undefined), 0) once (never called)
    ExpectationError: Unexpected call: delay(function () {}, 0) at Pass.schedule (usr/local/google/home/rsimha/src/amphtml/src/pass.js:94:37)
    Unexpected call: delay(function () {}, 30000) at Pass.schedule (usr/local/google/home/rsimha/src/amphtml/src/pass.js:94:37)
    Expected delay(match(undefined), 0) once (never called)
        at Object.fail (/tmp/node_modules/sinon/lib/sinon/mock-expectation.js:309:1)
        at Object.verify (/tmp/node_modules/sinon/lib/sinon/mock.js:114:1)
        at Context.<anonymous> (usr/local/google/home/rsimha/src/amphtml/test/unit/test-pass.js:36:15)

[14:51:36] Stopped server at http://localhost:8081
[14:51:36] ERROR: Karma test failed with exit code 1
[14:51:36] Finished 'unit' after 33 s
rsimha@bobdylan (2019-11-14-GlobalSinon):~/src/amphtml$ 
```

**Comment by rsimha** [comment]
Found a fix. Some tests were using a global matcher in addition to the global sandbox object. There's nothing left to do.
