### ISSUE TITLE
A4A `cross-domain rendering` test failing on Travis

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#25690]
Failures from today:

https://travis-ci.org/ampproject/amphtml/jobs/614351495#L1721
https://travis-ci.org/ampproject/amphtml/jobs/614351770#L1721
https://travis-ci.org/ampproject/amphtml/jobs/614351918#L1721
https://travis-ci.org/ampproject/amphtml/jobs/614352145#L1710
https://travis-ci.org/ampproject/amphtml/jobs/614359578#L1710
https://travis-ci.org/ampproject/amphtml/jobs/614592363#L1710

```
DESCRIBE => AmpDocService
  DESCRIBE => amp-a4a
    DESCRIBE => cross-domain rendering
      DESCRIBE => #renderViaNameFrame
        IT => should not attach a NameFrame when header is safeframe
          ✗ AssertionError: expected error to not have been called
              at _callee29$ (home/travis/build/ampproject/amphtml/extensions/amp-a4a/0.1/test/test-amp-a4a.js:839:15)
              at tryCatch (home/travis/build/ampproject/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
              at Generator.invoke [as _invoke] (home/travis/build/ampproject/amphtml/node_modules/regenerator-runtime/runtime.js:303:22)
              at Generator.prototype.<computed> [as next] (home/travis/build/ampproject/amphtml/node_modules/regenerator-runtime/runtime.js:117:21)
              at tryCatch (home/travis/build/ampproject/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
              at invoke (home/travis/build/ampproject/amphtml/node_modules/regenerator-runtime/runtime.js:155:20)
              at http://localhost:9876/home/travis/build/ampproject/amphtml/node_modules/regenerator-runtime/runtime.js:165:13
HeadlessChrome 78.0.3904 (Linux 0.0.0) AmpDocService amp-a4a cross-domain rendering #renderViaNameFrame should not attach a NameFrame when header is safeframe FAILED
	AssertionError: expected error to not have been called
	    at _callee29$ (home/travis/build/ampproject/amphtml/extensions/amp-a4a/0.1/test/test-amp-a4a.js:839:15)
	    at tryCatch (home/travis/build/ampproject/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
	    at Generator.invoke [as _invoke] (home/travis/build/ampproject/amphtml/node_modules/regenerator-runtime/runtime.js:303:22)
	    at Generator.prototype.<computed> [as next] (home/travis/build/ampproject/amphtml/node_modules/regenerator-runtime/runtime.js:117:21)
	    at tryCatch (home/travis/build/ampproject/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
	    at invoke (home/travis/build/ampproject/amphtml/node_modules/regenerator-runtime/runtime.js:155:20)
	    at http://localhost:9876/home/travis/build/ampproject/amphtml/node_modules/regenerator-runtime/runtime.js:165:13
```

**Comment by jeffkaufman** [comment]
Do we know which PR broke this?

**Comment by calebcordry** [comment]
looks like it starting failing with #66918 I haven't investigated but it seems like the new closure version is a reasonable suspect.

**Comment by rsimha** [comment]
#25601 is only used by validator code and isn't consumed by `amphtml` in any way, so I'll be surprised if it's the cause.

**Comment by zombifier** [comment]
Agree that #25601 is not the culprit, since the tests pass on a local build at HEAD. Maybe something changed on Travis' side?
