### ISSUE TITLE
`amp-sidebar` tests are flaky (potential bug?)

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#28206]
Probably related to #28145.

Multiple failing runs over the past few days have this signature:

```
DESCRIBE => amp-sidebar
  DESCRIBE => sidebar focus
    DESCRIBE =>  
      IT => should not change scroll position after close
        ✗ Error: Timeout waiting for wait for sidebar to open
            at poll (/tmp/testing/iframe.js:439:18)
      IT => should not change scroll position after close
        ✗ Error: Timeout waiting for wait for sidebar to open
            at poll (/tmp/testing/iframe.js:439:18)
```

**Comment by rsimha** [comment]
@ampproject/wg-ui-and-a11y for triage

/cc @ampproject/build-cop
