### ISSUE TITLE
Frequently failing `ad choices` and `amp-bind` e2e tests

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#28391]
Seeing many of these of late. Example: https://travis-ci.org/github/ampproject/amphtml/jobs/686700022#L2340

```
  1) ad choices
       chrome
          AMPHTML ads inabox friendly frame environment 
           "before each" hook for "interactions":
     Error: Server terminated early with status 1
      at /home/travis/build/ampproject/amphtml/build-system/tasks/e2e/node_modules/selenium-webdriver/remote/index.js:251:52
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  2) ad choices
       chrome
          AMPHTML ads inabox friendly frame environment 
           "after each" hook for "interactions":
     Error: Server terminated early with status 1
      at /home/travis/build/ampproject/amphtml/build-system/tasks/e2e/node_modules/selenium-webdriver/remote/index.js:251:52
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  3) ad choices
       chrome
          AMPHTML ads inabox safeframe environment 
           "before each" hook for "interactions":
     Error: Server terminated early with status 1
      at /home/travis/build/ampproject/amphtml/build-system/tasks/e2e/node_modules/selenium-webdriver/remote/index.js:251:52
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  4) ad choices
       chrome
          AMPHTML ads inabox safeframe environment 
           "after each" hook for "interactions":
     Error: Server terminated early with status 1
      at /home/travis/build/ampproject/amphtml/build-system/tasks/e2e/node_modules/selenium-webdriver/remote/index.js:251:52
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  5) amp-bind
       chrome
          Standalone environment 
           "before each" hook for "should support binding to data-account":
     Error: Server terminated early with status 1
      at /home/travis/build/ampproject/amphtml/build-system/tasks/e2e/node_modules/selenium-webdriver/remote/index.js:251:52
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  6) amp-bind
       chrome
          Standalone environment 
           "after each" hook for "should support binding to data-account":
     Error: Server terminated early with status 1
      at /home/travis/build/ampproject/amphtml/build-system/tasks/e2e/node_modules/selenium-webdriver/remote/index.js:251:52
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  7) amp-bind
       chrome
          Viewer environment 
           "before each" hook for "should support binding to data-account":
     Error: Server terminated early with status 1
      at /home/travis/build/ampproject/amphtml/build-system/tasks/e2e/node_modules/selenium-webdriver/remote/index.js:251:52
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  8) amp-bind
       chrome
          Viewer environment 
           "after each" hook for "should support binding to data-account":
     Error: Server terminated early with status 1
      at /home/travis/build/ampproject/amphtml/build-system/tasks/e2e/node_modules/selenium-webdriver/remote/index.js:251:52
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  9) amp-bind
       chrome
          Shadow environment 
           "before each" hook for "should support binding to data-account":
     Error: Server terminated early with status 1
      at /home/travis/build/ampproject/amphtml/build-system/tasks/e2e/node_modules/selenium-webdriver/remote/index.js:251:52
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  10) amp-bind
       chrome
          Shadow environment 
           "after each" hook for "should support binding to data-account":
     Error: Server terminated early with status 1
      at /home/travis/build/ampproject/amphtml/build-system/tasks/e2e/node_modules/selenium-webdriver/remote/index.js:251:52
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
Executed 439 of 478 (Skipped 49) 10 FAILED 
```

/cc @ampproject/build-cop

**Comment by rsimha** [comment]
Hello, @ampproject/wg-ads, these tests have been flaking fairly often recently. Before I set out to skip them, would someone like to take a look to see if there's an easy fix?

https://travis-ci.org/github/ampproject/amphtml/jobs/692751359#L2384

**Comment by powerivq** [comment]
@rsimha Thanks for letting us know!

```
Error: Server terminated early with status 1
 at /home/travis/build/ampproject/amphtml/build-system/tasks/e2e/node_modules/selenium-webdriver/remote/index.js:251:52
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Do you know if that is a timeout?
