### ISSUE TITLE
🚨 Error: [Failed to execute 'observe' on 'PerformanceObserver': required member entryTypes is undefined.]

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#29399]
Details
---

**Error report:** [link](go/ampe/CJq-0s3GyurFiAE)
**First seen:** Jul 6, 2020 
**Frequency:** ~ 97 /day

Stacktrace
---
```
Error: Failed to execute 'observe' on 'PerformanceObserver': required member entryTypes is undefined.
    at processEntry (https://raw.githubusercontent.com/ampproject/amphtml/2007102309001/src/service/performance-impl.js:407:65)
    at fpTime (https://raw.githubusercontent.com/ampproject/amphtml/2007102309001/src/service/performance-impl.js:571:44)
    at https://raw.githubusercontent.com/ampproject/amphtml/2007102309001/src/service.js:402:12
    at win (https://raw.githubusercontent.com/ampproject/amphtml/2007102309001/src/service.js:199:21)
    at getService (https://raw.githubusercontent.com/ampproject/amphtml/2007102309001/src/services.js:382:66)
    at a (https://raw.githubusercontent.com/ampproject/amphtml/2007102309001/src/chunk.js:200:6)
    at t (https://raw.githubusercontent.com/ampproject/amphtml/2007102309001/src/chunk.js:414:6)
    at this (https://raw.githubusercontent.com/ampproject/amphtml/2007102309001/src/chunk.js:327:8)
```

/cc @ampproject/release-on-duty

**Comment by rcebulko** [comment]
This appears to occur almost exclusively on ESM builds

**Comment by erwinmombay** [comment]
taking this on right now. seeing an uptick on this
