### ISSUE TITLE
🐛 Fix Flaky Carousel Tests

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#30562]
```
 DESCRIBE => isAtEnd
      IT => should return false when at not at end for RTL
        ✗ AssertionError: expected true to be false
            at _callee5$ (/tmp/extensions/amp-base-carousel/0.1/test/test-carousel.js:170:7)
            at tryCatch (/tmp/node_modules/fetch-mock/es5/client-bundle.js:1656:41)
            at Generator.invoke [as _invoke] (/tmp/node_modules/fetch-mock/es5/client-bundle.js:1890:23)
            at Generator.prototype.<computed> [as next] (/tmp/node_modules/fetch-mock/es5/client-bundle.js:1708:22)
            at asyncGeneratorStep (/tmp/091011ea771c23716a5633921103c679.browserify.js:558783:103)
            at _next (/tmp/091011ea771c23716a5633921103c679.browserify.js:558785:194)
Chrome Headless 86.0.4240.75 (Linux x86_64) carousel implementation   isAtEnd should return false when at not at end for RTL FAILED
	AssertionError: expected true to be false
	    at _callee5$ (/tmp/extensions/amp-base-carousel/0.1/test/test-carousel.js:170:7)
	    at tryCatch (/tmp/node_modules/fetch-mock/es5/client-bundle.js:1656:41)
	    at Generator.invoke [as _invoke] (/tmp/node_modules/fetch-mock/es5/client-bundle.js:1890:23)
	    at Generator.prototype.<computed> [as next] (/tmp/node_modules/fetch-mock/es5/client-bundle.js:1708:22)
	    at asyncGeneratorStep (/tmp/091011ea771c23716a5633921103c679.browserify.js:558783:103)
	    at _next (/tmp/091011ea771c23716a5633921103c679.browserify.js:558785:194)
●●●●
    DESCRIBE => isAtStart
      IT => should return true when at start for RTL
        ✗ AssertionError: expected false to be true
            at _callee9$ (/tmp/extensions/amp-base-carousel/0.1/test/test-carousel.js:220:7)
            at tryCatch (/tmp/node_modules/fetch-mock/es5/client-bundle.js:1656:41)
            at Generator.invoke [as _invoke] (/tmp/node_modules/fetch-mock/es5/client-bundle.js:1890:23)
            at Generator.prototype.<computed> [as next] (/tmp/node_modules/fetch-mock/es5/client-bundle.js:1708:22)
            at asyncGeneratorStep (/tmp/091011ea771c23716a5633921103c679.browserify.js:558783:103)
            at _next (/tmp/091011ea771c23716a5633921103c679.browserify.js:558785:194)
Chrome Headless 86.0.4240.75 (Linux x86_64) carousel implementation   isAtStart should return true when at start for RTL FAILED
	AssertionError: expected false to be true
	    at _callee9$ (/tmp/extensions/amp-base-carousel/0.1/test/test-carousel.js:220:7)
	    at tryCatch (/tmp/node_modules/fetch-mock/es5/client-bundle.js:1656:41)
	    at Generator.invoke [as _invoke] (/tmp/node_modules/fetch-mock/es5/client-bundle.js:1890:23)
	    at Generator.prototype.<computed> [as next] (/tmp/node_modules/fetch-mock/es5/client-bundle.js:1708:22)
	    at asyncGeneratorStep (/tmp/091011ea771c23716a5633921103c679.browserify.js:558783:103)
	    at _next (/tmp/091011ea771c23716a5633921103c679.browserify.js:558785:194)
```

@ampproject/wg-ui-and-a11y

**Comment by rcebulko** [comment]
Related: https://github.com/ampproject/amphtml/issues/30661

**Comment by zhouyx** [comment]
Close and track in #30661
