### ISSUE TITLE
Saucelabs Integration Tests are super Flaky

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3139]
Last bunch of `master` builds saucelab integration tests failed. The errors seem to be inconsistent between each run. This is an example of failure of [this build](https://travis-ci.org/ampproject/amphtml/builds/128404710#L3991).

``` sh
06 05 2016 21:15:37.291:WARN [web-server]: 404: /base/dist/v0/sample-0.1.js
Edge 13.10586.0 (Windows 10 0.0.0) Rendering of one ad should create an iframe loaded FAILED
    Unable to get property 'document' of undefined or null reference (/tmp/97f5bdd8514fe7d1d1ab23a5040deef6.browserify:26948 <- /home/travis/build/ampproject/amphtml/test/integration/test-amp-ad-doubleclick.js:91:8)
    Error: Unable to get property 'document' of undefined or null reference (/tmp/97f5bdd8514fe7d1d1ab23a5040deef6.browserify:26948 <- /home/travis/build/ampproject/amphtml/test/integration/test-amp-ad-doubleclick.js:91:8)
Edge 13.10586.0 (Windows 10 0.0.0) Rendering of amp-img "before each" hook FAILED
    Unable to get property 'document' of undefined or null reference (/tmp/97f5bdd8514fe7d1d1ab23a5040deef6.browserify:26948 <- /home/travis/build/ampproject/amphtml/test/integration/test-amp-ad-doubleclick.js:91:8)
    Error: Unable to get property 'document' of undefined or null reference (/tmp/97f5bdd8514fe7d1d1ab23a5040deef6.browserify:26948 <- /home/travis/build/ampproject/amphtml/test/integration/test-amp-ad-doubleclick.js:91:8)
Edge 13.10586.0 (Windows 10 0.0.0) Old Opacity Boilerplate should show the body when opacity boilerplate is used FAILED
    TypeError: Unable to get property 'win' of undefined or null reference
       at Anonymous function (/tmp/97f5bdd8514fe7d1d1ab23a5040deef6.browserify:27352:5 <- /home/travis/build/ampproject/amphtml/test/integration/test-boilerplates.js:34:4)
Edge 13.10586.0 (Windows 10 0.0.0) Rendering of amp-img "before each" hook for "should be present" FAILED
    TypeError: Unable to get property 'call' of undefined or null reference
Edge 13.10586.0 (Windows 10 0.0.0) New Visibility Boilerplate "before each" hook FAILED
    Unable to get property 'document' of undefined or null reference (/tmp/97f5bdd8514fe7d1d1ab23a5040deef6.browserify:26948 <- /home/travis/build/ampproject/amphtml/test/integration/test-amp-ad-doubleclick.js:91:8)
    Error: Unable to get property 'document' of undefined or null reference (/tmp/97f5bdd8514fe7d1d1ab23a5040deef6.browserify:26948 <- /home/travis/build/ampproject/amphtml/test/integration/test-amp-ad-doubleclick.js:91:8)
Edge 13.10586.0 (Windows 10 0.0.0) New Visibility Boilerplate should show the body in boilerplate test FAILED
    TypeError: Unable to get property 'win' of undefined or null reference
       at Anonymous function (/tmp/97f5bdd8514fe7d1d1ab23a5040deef6.browserify:27368:5 <- /home/travis/build/ampproject/amphtml/test/integration/test-boilerplates.js:52:4)
Edge 13.10586.0 (Windows 10 0.0.0) example "before each" hook FAILED
    Unable to get property 'document' of undefined or null reference (/tmp/97f5bdd8514fe7d1d1ab23a5040deef6.browserify:26948 <- /home/travis/build/ampproject/amphtml/test/integration/test-amp-ad-doubleclick.js:91:8)
    Error: Unable to get property 'document' of undefined or null reference (/tmp/97f5bdd8514fe7d1d1ab23a5040deef6.browserify:26948 <- /home/travis/build/ampproject/amphtml/test/integration/test-amp-ad-doubleclick.js:91:8)
Edge 13.10586.0 (Windows 10 0.0.0): Executed 7 of 75 (7 FAILED) (skipped 14) ERROR (1.566 secs / NaN secs)
06 05 2016 21:15:37.605:ERROR [reporter.sauce]: ✖ Test Errored
Edge 13.10586.0 (Windows 10 0.0.0) ERROR
  Unable to get property 'document' of undefined or null reference
  at /tmp/97f5bdd8514fe7d1d1ab23a5040deef6.browserify:26948 <- /home/travis/build/ampproject/amphtml/test/integration/test-amp-ad-doubleclick.js:91:8
Edge 13.10586.0 (Windows 10 0.0.0): Executed 7 of 75 (7 FAILED) (skipped 14) ERROR (1.574 secs / NaN secs)
06 05 2016 21:15:37.612:ERROR [reporter.sauce]: ✖ Test Errored
Edge 13.10586.0 (Windows 10 0.0.0) ERROR
  Unable to get property 'document' of undefined or null reference
  at /tmp/97f5bdd8514fe7d1d1ab23a5040deef6.browserify:26948 <- /home/travis/build/ampproject/amphtml/test/integration/test-amp-ad-doubleclick.js:91:8
Edge 13.10586.0 (Windows 10 0.0.0): Executed 7 of 75 (7 FAILED) (skipped 14) ERROR (1.576 secs / NaN secs)
06 05 2016 21:15:37.614:ERROR [reporter.sauce]: ✖ Test Errored
....................
Safari 8.0.8 (Mac OS X 10.10.5): Executed 56 of 75 (skipped 19) SUCCESS (28.969 secs / 15.545 secs)
```

**Comment by mkhatib** [comment]
Related to #2349

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
