### ISSUE TITLE
[amp-story-player] Certain stories fail to 'show()' at load time 

### ISSUE THREAD

**Issue by pshihn** [ampproject/amphtml#31445]
## What's the issue?

I am creating a player with `n` stories. Under some cases I do not want the first story to be played first, but some other story in the list. say, the third story. 

When the player is **ready**, I call  `show()` on the story I want to play. For some stories it works for others it does not. 

e.g. https://jsfiddle.net/qdn9h7L8/54/

In this fiddle, I have the following stories
```html
<amp-story-player style="width: 360px; height: 600px;">
      <a href="https://preview.amp.dev/documentation/examples/introduction/stories_in_amp/">Stories in AMP - Hello World</a>
      <a href="https://web-player-cards-carousel.web.app/examples/amp-story/AMPFestPlayerDemo/s4/index.html"></a>
      <a href="https://stories-staging.slickstream.com/preet1/d/webstory/legra">Legra</a>
      <a href="https://web-player-cards-carousel.web.app/examples/amp-story/AMPFestPlayerDemo/s3/index.html"></a>
</amp-story-player>
```

If I call `show()` on the 4th story on ready, it all works
If I call `show()` on the 2nd story on ready, it does not work with a render timeout error
If I call `show()` on the 3rd story on ready, it does not work with an error:
```
reason: TypeError: Cannot read property 'then' of undefined at Yb (https://cdn.ampproject.org/amp-story-player-v0.js:69:36) at https://cdn.ampproject.org/amp-story-player-v0.js:76:163
message: "Cannot read property 'then' of undefined"
stack: "TypeError: Cannot read property 'then' of undefined↵    at Yb (https://cdn.ampproject.org/am
```

## How do we reproduce the issue?

Go to https://jsfiddle.net/qdn9h7L8/54/

In the code, update the `storyToStart` to one of the urls that do not work. (Commented out code)

## What browsers are affected?

All

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 2011200012001

**Comment by processprocess** [comment]
cc @Enriqe

**Comment by tarun7886** [comment]
@pshihn @Enriqe 
Any update on this issue? 
I am getting this error

Error: _"TypeError: Cannot read property 'then' of undefined at Yb (https://cdn.ampproject.org/amp-story-player-v0.js:69:36) at https://cdn.ampproject.org/amp-story-player-v0.js:76:163"_
Error Log: "_reason: "Cancelling previous story load."_"

After loading the player with some stories, I unmounted the component, now if I move to different stories using show method, I am getting the above error and it logs for the number of stories I skipped.

**Comment by Enriqe** [comment]
Just sent a proposed fix for this, hopefully will be fixed soon.
