### ISSUE TITLE
[amp-next-page] Request replaceHistory failed console error on viewer

### ISSUE THREAD

**Issue by dmanek** [ampproject/amphtml#32455]
## What's the issue?

When viewing a page on AMP viewer that loads next pages via the amp-next-page, there are the following console errors:
```
//history-impl.js:289
Uncaught (in promise) History: failed to execute a task:: Request replaceHistory failed: sb
    at wb.push.f.m.Ga (https://cdn.ampproject.org/rtv/012012301722001/v0/amp-viewer-integration-0.1.js:56:367)
    at https://cdn.ampproject.org/rtv/012012301722001/v0/amp-viewer-integration-0.1.js:54:686
```

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Open google.com in mobile view. Search for "cnet electric eels"
2. Click on the first result on SERP
3. Scroll down to let the next page load. View the console in CDT.

## What browsers are affected?

All

## Which AMP version is affected?

Version 2101230412003

**Comment by dmanek** [comment]
@nainar want your input here. We're not able to replace the history entry on the viewer for obvious reasons. But we do update it on origin. I propose we disable it on the viewer to fix this error. WDYT?

**Comment by dmanek** [comment]
@nainar is ok with not updating the URL in the viewer.

However, upon further investigation it seems like this might be an issue on the viewer, not with amp-next-page. Working with them to resolve this issue.

**Comment by panlee821** [comment]
Hi @dmanek, I would like to ask if this error will affect any other feature like `variable substitutions` (`READER_ID`)
Inside viewer, I have noticed the READER_ID rendered is empty on the next page's amp-access auth endpoint
It is working fine outside viewer.
just checking if it is related or it should be another issue, thanks

**Comment by panlee821** [comment]
> Hi @dmanek, I would like to ask if this error will affect any other feature like `variable substitutions` (`READER_ID`)
> Inside viewer, I have noticed the READER_ID rendered is empty on the next page's amp-access auth endpoint
> It is working fine outside viewer.
> just checking if it is related or it should be another issue, thanks

@dmanek, just double checking the example you posted ("cnet electric eels"), the `CLIENT_ID` (`&vid=CLIENT_ID(AMP_ECID_GOOGLE,,_ga)`) is also empty in the next article, I think there is a problem on the AMP viewer, just not sure if it is related to this issue

**Comment by Javidelmoral** [comment]
Hi @dmanek, I would like to know how is this issue going... We are having this issue in our production site.. and like @panlee821 commented we would like to know if this issue is affecting variable substitutions on next pages. (READER_ID is empty on next-pages auth endpoint)
This issue is only failing in google CDN, if we test in our urls everything works OK.
We are thinking in remove the "amp-next-page" functionality in our pages because our subscribers users will only see correctly the first page... the next (paywalled) ones will fail because of the empty READER_ID..
Thank you!
