### ISSUE TITLE
Automatic npm updates causes esbuild to fail when it upgrades

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#33364]
```
[15:01:20] Running npm install to update packages...

> amp-html@0.1.0 preinstall /Users/jridgewell/src/amphtml
> node build-system/common/check-package-manager.js

Detected node version v14.16.0 (latest LTS).
Detected gulp version 4.0.2.
Detected python version 2.7.16.
Detected npm version 6.14.11. Installing packages...

> esbuild@0.9.3 postinstall /Users/jridgewell/src/amphtml/node_modules/esbuild
> node install.js

added 1 package from 1 contributor, removed 2 packages and updated 5 packages in 20.597s
[15:01:47] Recompiled all CSS files into build/ (5.377 s)
[15:01:48] Building AMP Server at build-system/server/new-server/transforms/dist...
 > error: Cannot start service: Host version "0.8.57" does not match binary version "0.9.3"

1 error
[15:01:48] 'unit' errored after 32 s
[15:01:48] Error: The service was stopped
    at /Users/jridgewell/src/amphtml/node_modules/esbuild/lib/main.js:970:31
    at /Users/jridgewell/src/amphtml/node_modules/esbuild/lib/main.js:542:9
    at Socket.afterClose (/Users/jridgewell/src/amphtml/node_modules/esbuild/lib/main.js:520:7)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:529:15)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

This is caused because by the time we upgrade the npm packages, we've already required `esbuild`. We then upgrade `esbuild`, and it lazily starts a new server process. So we'll get an old version in memory, and server will spin up with the new version.

We should lazily import `esbuild` to avoid.

**Comment by rsimha** [comment]
With the new `amp` task runner, we can move the responsibility of updating packages from individual tasks to the runner, and make sure it happens before the task code is loaded.
