### ISSUE TITLE
❄️ Flaky test: amp-animation

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#33438]
Flaky test in `amp-animation`

```
  1) amp-animation
       chrome
          AMPHTML ads FIE environment 
            
             transparency animation should pause and restart:

      AssertionError: expected '0' to equal '1'
      + expected - actual

      -0
      +1
      
      at valueSatisfiesExpectation (build-system/tasks/e2e/expect.js:376:18)
      at conditionValue (build-system/tasks/e2e/selenium-webdriver-controller.js:121:22)
      at _callee$ (build-system/tasks/e2e/selenium-webdriver-controller.js:86:46)
      at tryCatch (build-system/tasks/e2e/node_modules/babel-regenerator-runtime/runtime.js:61:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (build-system/tasks/e2e/node_modules/babel-regenerator-runtime/runtime.js:329:22)
      at GeneratorFunctionPrototype.prototype.<computed> [as next] (build-system/tasks/e2e/node_modules/babel-regenerator-runtime/runtime.js:94:21)
      at asyncGeneratorStep (build-system/tasks/e2e/selenium-webdriver-controller.js:11:103)
      at _next (build-system/tasks/e2e/selenium-webdriver-controller.js:13:194)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

https://app.circleci.com/pipelines/github/ampproject/amphtml/5263/workflows/eebdd85b-86fc-448b-a3b9-3f33af6a0e6f/jobs/71532

@ampproject/wg-components

**Comment by alanorozco** [comment]
cc @ampproject/wg-monetization (deals with FIE)
