### ISSUE TITLE
🐛 Test unable to run due to build error?

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#33993]
Unit tests fail when trying to run `amp unit --files=extensions/amp-story/1.0/test/test-amp-story-bookend.js` on clean `main`. Seems like something to do with the build step?

Error message:
```sh
Chrome 90.0.4430.85 (Mac OS 10.15.7) ERROR
  Uncaught TypeError: Super expression must either be null or a function
  at null:null:1 <- /var/folders/9l/tw8v92zn2z1499sgm8vlp8qr00gpp7/T/20e3a4741e7583a4d495603310323949-bundle.js:78285:9

  TypeError: Super expression must either be null or a function
      at _inherits (null:null:1 <- /var/folders/9l/tw8v92zn2z1499sgm8vlp8qr00gpp7/T/20e3a4741e7583a4d495603310323949-bundle.js:78285:15)
      at null:null:1 <- /var/folders/9l/tw8v92zn2z1499sgm8vlp8qr00gpp7/T/20e3a4741e7583a4d495603310323949-bundle.js:78356:7
      at null:null:1 <- /var/folders/9l/tw8v92zn2z1499sgm8vlp8qr00gpp7/T/20e3a4741e7583a4d495603310323949-bundle.js:78548:6
      at null:null:1 <- /var/folders/9l/tw8v92zn2z1499sgm8vlp8qr00gpp7/T/20e3a4741e7583a4d495603310323949-bundle.js:6:9
      at http://localhost:9876/Users/ccordry/code/amphtml/extensions/amp-story/1.0/amp-story-open-page-attachment.js:20:1
      at null:null:1 <- /var/folders/9l/tw8v92zn2z1499sgm8vlp8qr00gpp7/T/20e3a4741e7583a4d495603310323949-bundle.js:6:9
      at http://localhost:9876/Users/ccordry/code/amphtml/extensions/amp-story/1.0/amp-story-draggable-drawer.js:32:1
      at null:null:1 <- /var/folders/9l/tw8v92zn2z1499sgm8vlp8qr00gpp7/T/20e3a4741e7583a4d495603310323949-bundle.js:6:9
      at http://localhost:9876/Users/ccordry/code/amphtml/extensions/amp-story/1.0/bookend/amp-story-bookend.js:28:1
      at null:null:1 <- /var/folders/9l/tw8v92zn2z1499sgm8vlp8qr00gpp7/T/20e3a4741e7583a4d495603310323949-bundle.js:6:9
[12:46:37] WARNING: Received a status with zero tests: {"startTime":1619207195844,"total":0,"success":0,"failed":0,"skipped":0,"totalTime":1355,"netTime":0,"error":true,"disconnected":false
```

Discovered in `amp unit --local_changes` failure when trying to merge #33884 

cc/ @ampproject/wg-stories @jridgewell @samouri

**Comment by samouri** [comment]
So it turns out this is just a part of JS eval of circular dependencies. In this case something tried to use `DraggableDrawer` before it was defined.
