### ISSUE TITLE
iframe_ is null in amp-ad in some instances

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#3632]
```js
TypeError: Cannot read property 'style' of null
    at https://cdn.ampproject.org/rtv/001465588263524/v0/amp-ad-0.1.js:48:36
    at https://cdn.ampproject.org/rtv/001465588263524/v0/amp-ad-0.1.js:25:58
    at f (https://cdn.ampproject.org/rtv/001465588263524/v0/amp-ad-0.1.js:24:301)
    at b (https://cdn.ampproject.org/rtv/001465588263524/v0/amp-ad-0.1.js:24:150)
```

```js
TypeError: Cannot read property 'name' of null
    at Array.<anonymous> (https://cdn.ampproject.org/rtv/001466016447690/v0/amp-ad-0.1.js:50:391)
    at Oe (https://cdn.ampproject.org/rtv/001466016447690/v0.js:176:310)
    at h (https://cdn.ampproject.org/rtv/001466016447690/v0.js:189:381)
    at le.setState (https://cdn.ampproject.org/rtv/001466016447690/v0.js:161:439)
    at we (https://cdn.ampproject.org/rtv/001466016447690/v0.js:175:396)
    at Rc.handler_ (https://cdn.ampproject.org/rtv/001466016447690/v0.js:161:950)
    at Rc.pass_ (https://cdn.ampproject.org/rtv/001466016447690/v0.js:59:89)
    at Rc.boundPass_ (https://cdn.ampproject.org/rtv/001466016447690/v0.js:58:654)
    at https://cdn.ampproject.org/rtv/001466016447690/v0.js:34:980
```

**Comment by erwinmombay** [comment]
investigating if this bug is in prod or just canary

**Comment by cramforce** [comment]
I could see `.name` happening as a rare-ish race condition. How often do these occur?

**Comment by erwinmombay** [comment]
confirmed this issue is in prod

**Comment by cramforce** [comment]
Ah, can also see how `.style` would happen. These should be harmless, but lets fix!

**Comment by zhouyx** [comment]
Here's what I understand, please correct me. 
 `.style` will happen if `noContentHandler_()` gets called first.
`.name` will happen if `unlayoutCallback()` gets called first.
For the fix of `.style` `this.iframe_` is null before the the return of `layoutCallback()`, what should be returned?

**Comment by jridgewell** [comment]
Both are happening because when `#noContentHandler` is called (which defers a mutation) then `#unlayoutCallback` is called (which unsets `#iframe`). The mutation will either try accessing `iframe.style` or `iframe.name` on the now `null` `#iframe` depending on whether is a fallback element or not.

**Comment by zhouyx** [comment]
I could see that happening on `iframe.name`. But the mutation never try to access `iframe.style`. `iframe.style` is only been accessed in `layoutCallback()`

**Comment by jridgewell** [comment]
Whoops, misread `this.element` for `this.iframe_`.
