### ISSUE TITLE
if localstorage does not exist, dont call getItem/setItem

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#3636]
``` js
TypeError: Failed to load store: : Cannot read property 'getItem' of null
    at https://cdn.ampproject.org/rtv/011464987951323/v0/amp-analytics-0.1.js:104:549
    at Kb.loadBlob (https://cdn.ampproject.org/rtv/011464987951323/v0/amp-analytics-0.1.js:104:505)
    at Y.getStore_ (https://cdn.ampproject.org/rtv/011464987951323/v0/amp-analytics-0.1.js:102:88)
    at Y.get (https://cdn.ampproject.org/rtv/011464987951323/v0/amp-analytics-0.1.js:101:728)
    at https://cdn.ampproject.org/rtv/011464987951323/v0/amp-user-notification-0.1.js:17:141
```

this should be in the storage-impl.js file

/to @dvoytenko for triage

**Comment by erwinmombay** [comment]
ill take this, related to https://github.com/ampproject/amphtml/issues/2759

**Comment by ericlindley-g** [comment]
@erwinmombay Assuming this goes in "next", but please correct/update as needed

**Comment by erwinmombay** [comment]
this should be fixed with our `expectedError` calls
