### ISSUE TITLE
RangeError: Maximum call stack size exceeded for amp-ad.js

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#3795]
not sure if this is related to https://github.com/ampproject/amphtml/issues/3519

```js
RangeError: Maximum call stack size exceeded
    at w (https://cdn.ampproject.org/rtv/011466185787499/v0/amp-ad-0.1.js:3:66)
    at new y (https://cdn.ampproject.org/rtv/011466185787499/v0/amp-ad-0.1.js:3:543)
    at https://cdn.ampproject.org/rtv/011466185787499/v0/amp-ad-0.1.js:8:7
    at https://cdn.ampproject.org/rtv/011466185787499/v0.js:273:369
    at Ea (https://cdn.ampproject.org/rtv/011466185787499/v0.js:14:129)
    at Fa (https://cdn.ampproject.org/rtv/011466185787499/v0.js:14:381)
    at Object.a.AMP.push (https://cdn.ampproject.org/rtv/011466185787499/v0.js:273:344)
    at https://cdn.ampproject.org/rtv/011466185787499/v0/amp-ad-0.1.js:1:33
```

user agent: `Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G920F Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36 `

page: https://cdn.ampproject.org/v/m.faz.net/aktuell/feuilleton/kino/goetz-george-der-verhinderte-kinosuperstar-14311718.amp.html?amp_js_v=5  

this is prod

**Comment by cramforce** [comment]
@erwinmombay How about adding a label for bugs created from production bug reports.

This definitely looks similarly weird. `w` is not recursive. The call where it fails is to `string.trim()`.

CC @jridgewell

**Comment by jridgewell** [comment]
What luck! I happen to have this exact phone at my desk.

**Comment by jridgewell** [comment]
But, it seems we're not reporting the hash fragment that lead us to this error. 😞

**Comment by cramforce** [comment]
Maybe we should start collecting it in error reports. But it can be
misleading as things can get transitioned by `postMessage`.

**Comment by erwinmombay** [comment]
here's another one, different stack

```js
exception: "RangeError: Maximum call stack size exceeded
    at Rb.JSCompiler_prototypeAlias.isSafari (https://cdn.ampproject.org/rtv/011466185787499/v0.js:39:376)
    at Rc (https://cdn.ampproject.org/rtv/011466185787499/v0.js:58:26)
    at Pc.url (https://cdn.ampproject.org/rtv/011466185787499/v0.js:56:494)
    at Pc.prefetch (https://cdn.ampproject.org/rtv/011466185787499/v0.js:57:120)
    at Z.preconnectCallback (https://cdn.ampproject.org/rtv/011466185787499/v0/amp-twitter-0.1.js:29:578)
    at https://cdn.ampproject.org/rtv/011466185787499/v0.js:246:312"      
```

**Comment by erwinmombay** [comment]
```js
RangeError: Maximum call stack size exceeded
    at new Nd (https://cdn.ampproject.org/rtv/011466185787499/v0.js:93:178)
    at https://cdn.ampproject.org/rtv/011466185787499/v0.js:106:374
    at C (https://cdn.ampproject.org/rtv/011466185787499/v0.js:36:415)
    at Ud (https://cdn.ampproject.org/rtv/011466185787499/v0.js:106:343)
    at Mf (https://cdn.ampproject.org/rtv/011466185787499/v0.js:221:138)
    at https://cdn.ampproject.org/rtv/011466185787499/v0.js:275:16
    at Yb (https://cdn.ampproject.org/rtv/011466185787499/v0.js:41:1207)
    at https://cdn.ampproject.org/rtv/011466185787499/v0.js:274:761
    at https://cdn.ampproject.org/rtv/011466185787499/v0.js:276:79
```

agent: `"Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G920F Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36`

page: https://cdn.ampproject.org/v/s/amp.marca.com/futbol/eurocopa/2016/06/27/57713ef1ca474104478b45ad.html?amp_js_v=5

**Comment by muxin** [comment]
```js
RangeError: Maximum call stack size exceeded
    at Pc.url (https://cdn.ampproject.org/rtv/021466185787499/v0.js:56:64)
    at Pc.prefetch (https://cdn.ampproject.org/rtv/021466185787499/v0.js:57:120)
    at https://cdn.ampproject.org/rtv/021466185787499/v0/amp-ad-0.1.js:43:237
    at Array.forEach (native)
    at Y.JSCompiler_prototypeAlias.preconnectCallback (https://cdn.ampproject.org/rtv/021466185787499/v0/amp-ad-0.1.js:43:204)
    at https://cdn.ampproject.org/rtv/021466185787499/v0.js:246:312
```

agent: Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G920F/G920FXXS3DPD2 Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36 

page: https://cdn.ampproject.org/v/internacional.elpais.com/internacional/2016/06/28/actualidad/1467141517_210077.amp.html?amp_js_v=5

**Comment by cramforce** [comment]
This seems to be a browser bug.
