### ISSUE TITLE
[HOT] 

### ISSUE THREAD

**Issue by xantos008** [ampproject/amphtml#38061]
### Description

Please help to understand, i don't know what to try more..

[20:24:03] ERROR: Error: Build failed with 1 error:
error: The entry point "./src\\bento\\components\\bento-inline-gallery\\1.0\\bento-inline-gallery.js" cannot be marked as external
    at failureErrorWithLog (C:\Users\amote\Documents\amphtml\node_modules\esbuild\lib\main.js:1493:15)
    at C:\Users\amote\Documents\amphtml\node_modules\esbuild\lib\main.js:1151:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

[20:24:03] ERROR: Error: Build failed with 1 error:
error: The entry point "./src\\bento\\components\\bento-facebook\\1.0\\bento-facebook.js" cannot be marked as external
    at failureErrorWithLog (C:\Users\amote\Documents\amphtml\node_modules\esbuild\lib\main.js:1493:15)
    at C:\Users\amote\Documents\amphtml\node_modules\esbuild\lib\main.js:1151:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

[20:24:03] ERROR: Error: Build failed with 1 error:
error: The entry point "./src\\bento\\components\\bento-mustache\\1.0\\bento-mustache.js" cannot be marked as external
    at failureErrorWithLog (C:\Users\amote\Documents\amphtml\node_modules\esbuild\lib\main.js:1493:15)
    at C:\Users\amote\Documents\amphtml\node_modules\esbuild\lib\main.js:1151:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

[20:24:03] 'build' errored after 8s
[20:24:03] Error: Could not compile bento-inline-gallery-1.0.max.js
    at handleBundleError (C:\Users\amote\Documents\amphtml\build-system\tasks\helpers.js:249:11)
    at C:\Users\amote\Documents\amphtml\build-system\tasks\helpers.js:430:5
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async esbuildCompile (C:\Users\amote\Documents\amphtml\build-system\tasks\helpers.js:429:3)
    at async doCompileJs (C:\Users\amote\Documents\amphtml\build-system\tasks\helpers.js:562:5)
    at async compileJs (C:\Users\amote\Documents\amphtml\build-system\tasks\helpers.js:565:3)
    at async buildExtensionJs (C:\Users\amote\Documents\amphtml\build-system\tasks\extension-helpers.js:834:3)
    at async buildBentoExtensionJs (C:\Users\amote\Documents\amphtml\build-system\tasks\extension-helpers.js:728:3)
    at async Promise.all (index 3)
    at async Promise.all (index 5)

### Reproduction Steps

node amp build

### Relevant Logs

```shell
[20:23:54] All packages in node_modules are up to date.
[20:23:54] Using task file Documents\amphtml\amp.js
[20:23:54] Starting 'build'...
[20:23:54] Running build. Press Ctrl + C to cancel...
[20:23:54] Building version 2204062139000 of the runtime with the prod AMP config.
[20:23:54] ⤷ Use --config={canary|prod} with your amp build command to specify which config to apply.
[20:23:54] Building all AMP extensions.
[20:23:54] ⤷ Use --core_runtime_only to build just the core runtime and skip other JS targets.
[20:23:54] ⤷ Use --noextensions to skip building extensions.
[20:23:54] ⤷ Use --extensions=amp-foo,amp-bar to choose which extensions to build.
[20:23:54] ⤷ Use --extensions=inabox to build just the extensions needed to load AMP ads.
[20:23:54] ⤷ Use --extensions_from=examples/foo.amp.html to build just the extensions needed to load foo.amp.html.
[20:23:54] Bootstrapped 3p frames into dist.3p/current/ (049 ms)
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
[20:23:55] Recompiled all CSS files into build/ (344 ms)
[20:23:55] Generated Story JSON Localization files into dist/v0 (370 ms)
[20:23:55] Compiling unminified JS...
[20:23:55] Generated AMP config (prod, localDev) for alp.max.js
[20:23:55] Generated AMP config (prod, localDev) for amp-shadow.js
[20:23:55] Generated AMP config (prod, localDev) for amp-inabox.js
[20:23:58] Compiled amp-viewer-host.max.js (3.300 s)
[20:23:59] Compiled video-iframe-integration.js (4.356 s)
[20:23:59] Compiled alp.max.js (4.368 s)
[20:23:59] Compiled amp-inabox-host.js (4.386 s)
[20:23:59] Compiled recaptcha.js (4.407 s)
[20:23:59] Compiled iframe-transport-client-lib.js (4.536 s)
[20:23:59] Compiled polyfills/index.js (4.570 s)
[20:23:59] Compiled ampcontext-lib.js (4.630 s)
[20:23:59] Compiled integration.js (4.656 s)
[20:24:00] Compiled bento.core.max.js (4.809 s)
[20:24:00] Compiled amp-story-player.js (5.447 s)
[20:24:00] Compiled amp-story-entry-point.js (5.447 s)
[20:24:00] Compiled bento.max.js → custom-elements-polyfill.max.js (5.475 s)
[20:24:00] Compiled amp-shadow.js (5.661 s)
[20:24:00] Compiled amp-inabox.js (5.672 s)
[20:24:00] Generated AMP config (prod, localDev) for amp.js
[20:24:01] Compiled amp.js (561 ms)
[20:24:01] Compiled all runtime JS files (6.236 s)
[20:24:03] ERROR: Error: Build failed with 1 error:
error: The entry point "./src\\bento\\components\\bento-inline-gallery\\1.0\\bento-inline-gallery.js" cannot be marked as external
    at failureErrorWithLog (C:\Users\amote\Documents\amphtml\node_modules\esbuild\lib\main.js:1493:15)
    at C:\Users\amote\Documents\amphtml\node_modules\esbuild\lib\main.js:1151:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

[20:24:03] ERROR: Error: Build failed with 1 error:
error: The entry point "./src\\bento\\components\\bento-facebook\\1.0\\bento-facebook.js" cannot be marked as external
    at failureErrorWithLog (C:\Users\amote\Documents\amphtml\node_modules\esbuild\lib\main.js:1493:15)
    at C:\Users\amote\Documents\amphtml\node_modules\esbuild\lib\main.js:1151:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

[20:24:03] ERROR: Error: Build failed with 1 error:
error: The entry point "./src\\bento\\components\\bento-mustache\\1.0\\bento-mustache.js" cannot be marked as external
    at failureErrorWithLog (C:\Users\amote\Documents\amphtml\node_modules\esbuild\lib\main.js:1493:15)
    at C:\Users\amote\Documents\amphtml\node_modules\esbuild\lib\main.js:1151:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

[20:24:03] 'build' errored after 8s
[20:24:03] Error: Could not compile bento-inline-gallery-1.0.max.js
    at handleBundleError (C:\Users\amote\Documents\amphtml\build-system\tasks\helpers.js:249:11)
    at C:\Users\amote\Documents\amphtml\build-system\tasks\helpers.js:430:5
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async esbuildCompile (C:\Users\amote\Documents\amphtml\build-system\tasks\helpers.js:429:3)
    at async doCompileJs (C:\Users\amote\Documents\amphtml\build-system\tasks\helpers.js:562:5)
    at async compileJs (C:\Users\amote\Documents\amphtml\build-system\tasks\helpers.js:565:3)
    at async buildExtensionJs (C:\Users\amote\Documents\amphtml\build-system\tasks\extension-helpers.js:834:3)
    at async buildBentoExtensionJs (C:\Users\amote\Documents\amphtml\build-system\tasks\extension-helpers.js:728:3)
    at async Promise.all (index 3)
    at async Promise.all (index 5)
```

### OS(s) Affected

Windows

### Device(s) Affected

Laptop

**Comment by 12csw1** [comment]
Should this issue be labeled as P3: When Possible?

We are doing research about “Issue Priority Prediction". We have developed a tool to automatically label the priority of an issue. The basic idea is to employ Bert model to encode the textual and code descriptions of the issue, and incorporate the issue’s attributes in the model, then apply multi-task learning to facilitate other information boosting the prediction performance. 
 We have conducted experiments on four GitHub projects with 21700 issues, and results show that [79 accuracy]() can be achieved.

Our tool shows that this issue has a very large possibility to be labeled as P3: When Possible 
Could you please tell us whether it should be labeled as P3: When Possible?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by xantos008** [comment]
@12csw1 yeah, np. But its simple question for developers i think :-)

**Comment by erwinmombay** [comment]
heya seems like a bento issue on our infra. Let us know and reopen this issue if you are still encountering this
