### ISSUE TITLE
action toggleChecked doesn't work without specifying `force`

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amphtml#38312]
### Description

The action `toggleChecked` doesn't work when leaving the optional parameter as default - it generates a JS error. However, specifying `force` does make it work.

@anrghg 
@jridgewell 

### Reproduction Steps

```
<!DOCTYPE html>
<html ⚡>
  <head>
    <meta charset="utf-8" />
    <title>My AMP Page</title>
    <link rel="canonical" href="self.html" />
    <meta name="viewport" content="width=device-width" />
    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
    <script async src="https://cdn.ampproject.org/v0.js"></script>
    <style amp-custom>
      h1 {
        margin: 1rem;
      }
    </style>
  </head>
  <body>
    <h1>Hello AMPHTML World!</h1>
    <button on="tap:checkbox.toggleChecked">
      toggleChecked
    </button>
    <input id=checkbox type=checkbox>
  </body>
</html>
```

Clicking on the button results in an error:

```
Uncaught TypeError: Cannot read properties of null (reading 'force')
    at standard-actions-impl.js:594:16
    at mutate (mutator-impl.js:206:9)
    at Da (vsync-impl.js:456:17)
    at i.xl (vsync-impl.js:413:9)
```

This was added in https://github.com/ampproject/amphtml/pull/35795.

**Comment by anrghg** [comment]
@zhangsu @jridgewell  My apologies.

Would https://github.com/anrghg/amphtml/blob/488697f582aa249461f9dba69313c68c713d5890/src/service/standard-actions-impl.js#L594 fix it?

**Comment by anrghg** [comment]
@zhangsu @jridgewell Please disregard. https://github.com/anrghg/amphtml/blob/84ca3c357cb0e88d46f2c4691d41d2fad2f9a48a/src/service/standard-actions-impl.js#L594 might fix it.

**Comment by jridgewell** [comment]
Agh, I didn't realize that `args` could be nullish.

@anrghg: Yes, we should change that linen to read `if (args?.['force'] !== undefined) {`

**Comment by anrghg** [comment]
@jridgewell Thanks a lot! I'm crediting you in PR #38314. 
My apologies again. I'm using `force` throughout.
