### ISSUE TITLE
https://cdn.ampproject.org/v0/validator_wasm.js - read ETIMEDOUT 

### ISSUE THREAD

**Issue by MooseSaeed** [ampproject/amphtml#38563]
### Description

I keep getting this error. I'm using `amphtml-validator` inside [@nuxtjs/amp](https://github.com/nuxt-community/amp-module) package.

```
Unable to fetch https://cdn.ampproject.org/v0/validator_wasm.js - read ETIMEDOUT

  at ClientRequest.<anonymous> (node_modules/amphtml-validator/index.js:136:11)
  at ClientRequest.emit (node:events:390:28)
  at ClientRequest.emit (node:domain:475:12)
  at TLSSocket.socketErrorListener (node:_http_client:447:9)
  at TLSSocket.emit (node:events:390:28)
  at TLSSocket.emit (node:domain:475:12)
  at emitErrorNT (node:internal/streams/destroy:157:8)
  at emitErrorCloseNT (node:internal/streams/destroy:122:3)
  at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Reproduction Steps

These errors show during compilation process. No steps taken that led to the error.

### Relevant Logs

```shell
Unable to fetch https://cdn.ampproject.org/v0/validator_wasm.js - read ETIMEDOUT

  at ClientRequest.<anonymous> (node_modules/amphtml-validator/index.js:136:11)
  at ClientRequest.emit (node:events:390:28)
  at ClientRequest.emit (node:domain:475:12)
  at TLSSocket.socketErrorListener (node:_http_client:447:9)
  at TLSSocket.emit (node:events:390:28)
  at TLSSocket.emit (node:domain:475:12)
  at emitErrorNT (node:internal/streams/destroy:157:8)
  at emitErrorCloseNT (node:internal/streams/destroy:122:3)
  at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
```


### Browser(s) Affected

_No response_

### OS(s) Affected

_No response_

### Device(s) Affected

_No response_

### AMP Version Affected

_No response_

**Comment by newmuis** [comment]
@amaltas can you take a look?

**Comment by amaltas** [comment]
This looks like http client or network issue. As I am able to fetch the endpoint https://cdn.ampproject.org/v0/validator_wasm.js

Can you please try again possibly on a different machine/network.

**Comment by erwinmombay** [comment]
Closing issue as obsolete.
