### ISSUE TITLE
amp-story-player: Blocked a frame with origin ... from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by alexmanzo** [ampproject/amphtml#38734]
### Description

Our Sentry logs started up picking an error related to `amp-story-player` on March 21.
```
Uncaught DOM Exception: Blocked a frame with origin "https://playground.amp.dev" from accessing a cross-origin frame.
```
This occurs when the story starts to play. The raw stack trace is below in relevant logs, but it is specifically occurring in the `storeAspectRatio_(story)` function on this line:
```
if (story.iframe.contentWindow.document.documentElement) {
```
We assume that this error started occurring after [this PR](https://github.com/ampproject/amphtml/pull/38672) was introduced.

### Reproduction Steps

You can see this error in the JS console on this [amp-story-player example on the AMP playground](https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fguides-and-tutorials%2Fintegrate%2Fembed-stories.example.1.html%3Fformat%3Dwebsites&_gl=1*11kcbdb*_ga*YW1wLUNFRzJQOXdZN0VmSmlqYzBVMHZmc3c.).

In Firefox, the error is slightly different:
```
Uncaught DOMException: Permission denied to access property "document" on cross-origin object
```

### Relevant Logs

```shell
SecurityError: Blocked a frame with origin "https://{domain}.com" from accessing a cross-origin frame. Protocols, domains, and ports must match.
  at _proto.storeAspectRatio_(https://raw.githubusercontent.com/ampproject/amphtml/2303151529000/src/amp-story-player/amp-story-player-impl.js:1159:22)
  at handler(https://raw.githubusercontent.com/ampproject/amphtml/2303151529000/src/amp-story-player/amp-story-player-impl.js:1216:14)
  at _proto2.handleRequest_(https://raw.githubusercontent.com/ampproject/amphtml/2303151529000/node_modules/@ampproject/viewer-messaging/messaging.js:432:21)
  at _proto2.handleMessage_(https://raw.githubusercontent.com/ampproject/amphtml/2303151529000/node_modules/@ampproject/viewer-messaging/messaging.js:319:12)
  at ? ([native code])
  at apply(https://raw.githubusercontent.com/ampproject/amphtml/2303151529000/node_modules/@ampproject/viewer-messaging/messaging.js:83:9)
  at sentryWrapped(src:///./node_modules/@sentry/browser/esm/helpers.js:73:23)
```

### Browser(s) Affected

Chrome, Firefox, Safari, Edge

### AMP Version Affected

2303151621000

**Comment by coreymasanto** [comment]
Thanks for the detailed description! @ychsieh, could you look into this issue? It appears to have been introduced by #38672.

**Comment by ychsieh** [comment]
Yeah the security is the issue. I will use the Messaging between the viewer and the story to communicate the aspect ratio instead. Thanks for the catch! Will send out a fix today or tomorrow.

**Comment by alexmanzo** [comment]
Thanks all! Appreciate you looking into it.
