### ISSUE TITLE
amphtml-validator 1.0.36 dies with "TypeError: program.usage is not a function"

### ISSUE THREAD

**Issue by derat** [ampproject/amphtml#39935]
### Description

`amphtml-validator` 1.0.36 dies with `TypeError: program.usage is not a function` whenever I run it.

### Reproduction Steps

1. Run `amphtml-validator` 1.0.36 without any arguments or with `--help`.
2. Get an error.
3. Downgrade `amphtml-validator` to 1.0.35 and run it.
4. No errors.

### Relevant Logs

```shell
% node --version
v20.12.0
% npm --version
10.5.0
% npm ls -g amphtml-validator
/home/node/node-v20.12.0-linux-x64/lib
└── amphtml-validator@1.0.36
% amphtml-validator
/home/node/node-v20.12.0-linux-x64/lib/node_modules/amphtml-validator/index.js:378
      .usage(
       ^

TypeError: program.usage is not a function
    at main (/home/node/node-v20.12.0-linux-x64/lib/node_modules/amphtml-validator/index.js:378:8)
    at Object.<anonymous> (/home/node/node-v20.12.0-linux-x64/lib/node_modules/amphtml-validator/cli.js:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.12.0
% npm install -g amphtml-validator@1.0.35

changed 5 packages in 392ms
% amphtml-validator --help
Usage: amphtml-validator [options] <fileOrUrlOrMinus...>
...
```

### OS(s) Affected

Debian 12.5

**Comment by derat** [comment]
@powerivq per #39934

**Comment by aav7fl** [comment]
@derat Hi. I opened a PR to fix this last week. 

https://github.com/ampproject/amphtml/pull/39932

Just waiting on them to either accept or request changes, and then hopefully merge it.

**Comment by erwinmombay** [comment]
we've went and merged https://github.com/ampproject/amphtml/pull/39932

**Comment by powerivq** [comment]
Updated NPM.

**Comment by derat** [comment]
I'm still seeing the same failure with 1.0.37:

```
% npm ls -g amphtml-validator
/home/node/node-v20.12.0-linux-x64/lib
└── amphtml-validator@1.0.37

% amphtml-validator
/home/node/node-v20.12.0-linux-x64/lib/node_modules/amphtml-validator/index.js:378
      .usage(
       ^

TypeError: program.usage is not a function
    at main (/home/node/node-v20.12.0-linux-x64/lib/node_modules/amphtml-validator/index.js:378:8)
    at Object.<anonymous> (/home/node/node-v20.12.0-linux-x64/lib/node_modules/amphtml-validator/cli.js:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.12.0
```

Are you sure the fix was included in 1.0.37? My installed `index.js` still includes the buggy `const program = require('commander');` line.

**Comment by derat** [comment]
(You can also see that the fix appears to be missing at <https://www.npmjs.com/package/amphtml-validator?activeTab=code>.)

**Comment by powerivq** [comment]
@derat It has been updated again.
