### ISSUE TITLE
Validator JS Promise Issue

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#4757]
Something funky is going on with our Validator tests.

```
Failures:
1) Jasmine__TopLevel__Suite handles syntax errors in validator file
  Message:
    Expected 'Could not instantiate validator.js - Invalid or unexpected token' to be 'Could not instantiate validator.js - Unexpected token ILLEGAL'.
  Stack:
    Error: Expected 'Could not instantiate validator.js - Invalid or unexpected token' to be 'Could not instantiate validator.js - Unexpected token ILLEGAL'.
        at /home/travis/build/ampproject/amphtml/validator/nodejs/index_test.js:121:14
        at tryCallOne (/home/travis/build/ampproject/amphtml/validator/nodejs/node_modules/promise/lib/core.js:37:12)
        at /home/travis/build/ampproject/amphtml/validator/nodejs/node_modules/promise/lib/core.js:123:15
        at flush (/home/travis/build/ampproject/amphtml/validator/nodejs/node_modules/asap/raw.js:50:29)
```

**Comment by erwinmombay** [comment]
looks like one of the deps or core node changed something in 6.5.0

**Comment by erwinmombay** [comment]
temporary fix here https://github.com/ampproject/amphtml/pull/4765

@Gregable @powdercloud looks like 6.5 is the offending version. we could just add `if process.version > 6.4`

**Comment by jridgewell** [comment]
Let's revert now that #4767 is in.

**Comment by erwinmombay** [comment]
revert here https://github.com/ampproject/amphtml/pull/4769
