### ISSUE TITLE
Broken runtime tests on local

### ISSUE THREAD

**Issue by sriramkrish85** [ampproject/amphtml#5029]
```
Chrome 52.0.2743 (Mac OS X 10.11.6): Executed 263 of 2945 SUCCESS (0 secs / 3.541 secs)
Chrome 52.0.2743 (Mac OS X 10.11.6) runtime should convert AMP from array to AMP object in single-doc FAILED
	TypeError: Cannot read property 'split' of undefined
	    at isProxyOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:88997:26 <- /Users/skrish/amphtml/src/url.js:298:28)
	    at getSourceUrl (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89030:8 <- /Users/skrish/amphtml/src/url.js:334:7)
	    at getSourceOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89057:19 <- /Users/skrish/amphtml/src/url.js:364:18)
	    at new Storage (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:80662:45 <- /Users/skrish/amphtml/src/service/storage-impl.js:58:35)
	    at /var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81050:14 <- /Users/skrish/amphtml/src/service/storage-impl.js:371:11
	    at getServiceInternal (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:74101:62 <- /Users/skrish/amphtml/src/service.js:246:10)
	    at getService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73943:10 <- /Users/skrish/amphtml/src/service.js:78:9)
	    at installStorageService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81046:58 <- /Users/skrish/amphtml/src/service/storage-impl.js:365:45)
	    at installRuntimeServices (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73008:49 <- /Users/skrish/amphtml/src/runtime.js:92:24)
	    at adoptShared (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73072:3 <- /Users/skrish/amphtml/src/runtime.js:157:2)
Chrome 52.0.2743 (Mac OS X 10.11.6) runtime should convert AMP from array to AMP object in shadow-doc FAILED
	TypeError: Cannot read property 'split' of undefined
	    at isProxyOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:88997:26 <- /Users/skrish/amphtml/src/url.js:298:28)
	    at getSourceUrl (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89030:8 <- /Users/skrish/amphtml/src/url.js:334:7)
	    at getSourceOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89057:19 <- /Users/skrish/amphtml/src/url.js:364:18)
	    at new Storage (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:80662:45 <- /Users/skrish/amphtml/src/service/storage-impl.js:58:35)
	    at /var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81050:14 <- /Users/skrish/amphtml/src/service/storage-impl.js:371:11
	    at getServiceInternal (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:74101:62 <- /Users/skrish/amphtml/src/service.js:246:10)
	    at getService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73943:10 <- /Users/skrish/amphtml/src/service.js:78:9)
	    at installStorageService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81046:58 <- /Users/skrish/amphtml/src/service/storage-impl.js:365:45)
	    at installRuntimeServices (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73008:49 <- /Users/skrish/amphtml/src/runtime.js:92:24)
	    at adoptShared (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73072:3 <- /Users/skrish/amphtml/src/runtime.js:157:2)
Chrome 52.0.2743 (Mac OS X 10.11.6) runtime should NOT set cursor:pointer on document element on non-IOS FAILED
	TypeError: Cannot read property 'split' of undefined
	    at isProxyOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:88997:26 <- /Users/skrish/amphtml/src/url.js:298:28)
	    at getSourceUrl (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89030:8 <- /Users/skrish/amphtml/src/url.js:334:7)
	    at getSourceOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89057:19 <- /Users/skrish/amphtml/src/url.js:364:18)
	    at new Storage (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:80662:45 <- /Users/skrish/amphtml/src/service/storage-impl.js:58:35)
	    at /var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81050:14 <- /Users/skrish/amphtml/src/service/storage-impl.js:371:11
	    at getServiceInternal (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:74101:62 <- /Users/skrish/amphtml/src/service.js:246:10)
	    at getService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73943:10 <- /Users/skrish/amphtml/src/service.js:78:9)
	    at installStorageService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81046:58 <- /Users/skrish/amphtml/src/service/storage-impl.js:365:45)
	    at installRuntimeServices (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73008:49 <- /Users/skrish/amphtml/src/runtime.js:92:24)
	    at adoptShared (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73072:3 <- /Users/skrish/amphtml/src/runtime.js:157:2)
Chrome 52.0.2743 (Mac OS X 10.11.6) runtime should set cursor:pointer on document element on IOS FAILED
	TypeError: Cannot read property 'split' of undefined
	    at isProxyOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:88997:26 <- /Users/skrish/amphtml/src/url.js:298:28)
	    at getSourceUrl (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89030:8 <- /Users/skrish/amphtml/src/url.js:334:7)
	    at getSourceOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89057:19 <- /Users/skrish/amphtml/src/url.js:364:18)
	    at new Storage (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:80662:45 <- /Users/skrish/amphtml/src/service/storage-impl.js:58:35)
	    at /var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81050:14 <- /Users/skrish/amphtml/src/service/storage-impl.js:371:11
	    at getServiceInternal (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:74101:62 <- /Users/skrish/amphtml/src/service.js:246:10)
	    at getService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73943:10 <- /Users/skrish/amphtml/src/service.js:78:9)
	    at installStorageService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81046:58 <- /Users/skrish/amphtml/src/service/storage-impl.js:365:45)
	    at installRuntimeServices (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73008:49 <- /Users/skrish/amphtml/src/runtime.js:92:24)
	    at adoptShared (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73072:3 <- /Users/skrish/amphtml/src/runtime.js:157:2)
Chrome 52.0.2743 (Mac OS X 10.11.6) runtime should set cursor:pointer on IOS in shadow-doc FAILED
	TypeError: Cannot read property 'split' of undefined
	    at isProxyOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:88997:26 <- /Users/skrish/amphtml/src/url.js:298:28)
	    at getSourceUrl (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89030:8 <- /Users/skrish/amphtml/src/url.js:334:7)
	    at getSourceOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89057:19 <- /Users/skrish/amphtml/src/url.js:364:18)
	    at new Storage (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:80662:45 <- /Users/skrish/amphtml/src/service/storage-impl.js:58:35)
	    at /var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81050:14 <- /Users/skrish/amphtml/src/service/storage-impl.js:371:11
	    at getServiceInternal (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:74101:62 <- /Users/skrish/amphtml/src/service.js:246:10)
	    at getService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73943:10 <- /Users/skrish/amphtml/src/service.js:78:9)
	    at installStorageService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81046:58 <- /Users/skrish/amphtml/src/service/storage-impl.js:365:45)
	    at installRuntimeServices (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73008:49 <- /Users/skrish/amphtml/src/runtime.js:92:24)
	    at adoptShared (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73072:3 <- /Users/skrish/amphtml/src/runtime.js:157:2)
Chrome 52.0.2743 (Mac OS X 10.11.6) runtime should execute scheduled extensions & execute new extensions FAILED
	TypeError: Cannot read property 'split' of undefined
	    at isProxyOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:88997:26 <- /Users/skrish/amphtml/src/url.js:298:28)
	    at getSourceUrl (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89030:8 <- /Users/skrish/amphtml/src/url.js:334:7)
	    at getSourceOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89057:19 <- /Users/skrish/amphtml/src/url.js:364:18)
	    at new Storage (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:80662:45 <- /Users/skrish/amphtml/src/service/storage-impl.js:58:35)
	    at /var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81050:14 <- /Users/skrish/amphtml/src/service/storage-impl.js:371:11
	    at getServiceInternal (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:74101:62 <- /Users/skrish/amphtml/src/service.js:246:10)
	    at getService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73943:10 <- /Users/skrish/amphtml/src/service.js:78:9)
	    at installStorageService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81046:58 <- /Users/skrish/amphtml/src/service/storage-impl.js:365:45)
	    at installRuntimeServices (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73008:49 <- /Users/skrish/amphtml/src/runtime.js:92:24)
	    at adoptShared (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73072:3 <- /Users/skrish/amphtml/src/runtime.js:157:2)
Chrome 52.0.2743 (Mac OS X 10.11.6) runtime should execute function and struct AMP.push callbacks FAILED
	TypeError: Cannot read property 'split' of undefined
	    at isProxyOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:88997:26 <- /Users/skrish/amphtml/src/url.js:298:28)
	    at getSourceUrl (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89030:8 <- /Users/skrish/amphtml/src/url.js:334:7)
	    at getSourceOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89057:19 <- /Users/skrish/amphtml/src/url.js:364:18)
	    at new Storage (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:80662:45 <- /Users/skrish/amphtml/src/service/storage-impl.js:58:35)
	    at /var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81050:14 <- /Users/skrish/amphtml/src/service/storage-impl.js:371:11
	    at getServiceInternal (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:74101:62 <- /Users/skrish/amphtml/src/service.js:246:10)
	    at getService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73943:10 <- /Users/skrish/amphtml/src/service.js:78:9)
	    at installStorageService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81046:58 <- /Users/skrish/amphtml/src/service/storage-impl.js:365:45)
	    at installRuntimeServices (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73008:49 <- /Users/skrish/amphtml/src/runtime.js:92:24)
	    at adoptShared (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73072:3 <- /Users/skrish/amphtml/src/runtime.js:157:2)
Chrome 52.0.2743 (Mac OS X 10.11.6) runtime should wait for body before processing extensions FAILED
	TypeError: Cannot read property 'split' of undefined
	    at isProxyOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:88997:26 <- /Users/skrish/amphtml/src/url.js:298:28)
	    at getSourceUrl (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89030:8 <- /Users/skrish/amphtml/src/url.js:334:7)
	    at getSourceOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89057:19 <- /Users/skrish/amphtml/src/url.js:364:18)
	    at new Storage (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:80662:45 <- /Users/skrish/amphtml/src/service/storage-impl.js:58:35)
	    at /var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81050:14 <- /Users/skrish/amphtml/src/service/storage-impl.js:371:11
	    at getServiceInternal (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:74101:62 <- /Users/skrish/amphtml/src/service.js:246:10)
	    at getService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73943:10 <- /Users/skrish/amphtml/src/service.js:78:9)
	    at installStorageService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81046:58 <- /Users/skrish/amphtml/src/service/storage-impl.js:365:45)
	    at installRuntimeServices (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73008:49 <- /Users/skrish/amphtml/src/runtime.js:92:24)
	    at adoptShared (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73072:3 <- /Users/skrish/amphtml/src/runtime.js:157:2)
Chrome 52.0.2743 (Mac OS X 10.11.6) runtime should be robust against errors in early extensions FAILED
	TypeError: Cannot read property 'split' of undefined
	    at isProxyOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:88997:26 <- /Users/skrish/amphtml/src/url.js:298:28)
	    at getSourceUrl (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89030:8 <- /Users/skrish/amphtml/src/url.js:334:7)
	    at getSourceOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89057:19 <- /Users/skrish/amphtml/src/url.js:364:18)
	    at new Storage (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:80662:45 <- /Users/skrish/amphtml/src/service/storage-impl.js:58:35)
	    at /var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81050:14 <- /Users/skrish/amphtml/src/service/storage-impl.js:371:11
	    at getServiceInternal (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:74101:62 <- /Users/skrish/amphtml/src/service.js:246:10)
	    at getService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73943:10 <- /Users/skrish/amphtml/src/service.js:78:9)
	    at installStorageService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81046:58 <- /Users/skrish/amphtml/src/service/storage-impl.js:365:45)
	    at installRuntimeServices (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73008:49 <- /Users/skrish/amphtml/src/runtime.js:92:24)
	    at adoptShared (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73072:3 <- /Users/skrish/amphtml/src/runtime.js:157:2)
Chrome 52.0.2743 (Mac OS X 10.11.6) runtime single-mode "before each" hook for "should export properties to global AMP object" FAILED
	TypeError: Cannot read property 'split' of undefined
	    at isProxyOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:88997:26 <- /Users/skrish/amphtml/src/url.js:298:28)
	    at getSourceUrl (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89030:8 <- /Users/skrish/amphtml/src/url.js:334:7)
	    at getSourceOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89057:19 <- /Users/skrish/amphtml/src/url.js:364:18)
	    at new Storage (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:80662:45 <- /Users/skrish/amphtml/src/service/storage-impl.js:58:35)
	    at /var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81050:14 <- /Users/skrish/amphtml/src/service/storage-impl.js:371:11
	    at getServiceInternal (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:74101:62 <- /Users/skrish/amphtml/src/service.js:246:10)
	    at getService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73943:10 <- /Users/skrish/amphtml/src/service.js:78:9)
	    at installStorageService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81046:58 <- /Users/skrish/amphtml/src/service/storage-impl.js:365:45)
	    at installRuntimeServices (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73008:49 <- /Users/skrish/amphtml/src/runtime.js:92:24)
	    at adoptShared (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73072:3 <- /Users/skrish/amphtml/src/runtime.js:157:2)
Chrome 52.0.2743 (Mac OS X 10.11.6) runtime shadow-mode "before each" hook for "should export properties to global AMP object" FAILED
	TypeError: Cannot read property 'split' of undefined
	    at isProxyOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:88997:26 <- /Users/skrish/amphtml/src/url.js:298:28)
	    at getSourceUrl (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89030:8 <- /Users/skrish/amphtml/src/url.js:334:7)
	    at getSourceOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89057:19 <- /Users/skrish/amphtml/src/url.js:364:18)
	    at new Storage (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:80662:45 <- /Users/skrish/amphtml/src/service/storage-impl.js:58:35)
	    at /var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81050:14 <- /Users/skrish/amphtml/src/service/storage-impl.js:371:11
	    at getServiceInternal (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:74101:62 <- /Users/skrish/amphtml/src/service.js:246:10)
	    at getService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73943:10 <- /Users/skrish/amphtml/src/service.js:78:9)
	    at installStorageService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81046:58 <- /Users/skrish/amphtml/src/service/storage-impl.js:365:45)
	    at installRuntimeServices (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73008:49 <- /Users/skrish/amphtml/src/runtime.js:92:24)
	    at adoptShared (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73072:3 <- /Users/skrish/amphtml/src/runtime.js:157:2)
Chrome 52.0.2743 (Mac OS X 10.11.6) runtime attachShadowDoc "before each" hook for "should install services and styles" FAILED
	TypeError: Cannot read property 'split' of undefined
	    at isProxyOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:88997:26 <- /Users/skrish/amphtml/src/url.js:298:28)
	    at getSourceUrl (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89030:8 <- /Users/skrish/amphtml/src/url.js:334:7)
	    at getSourceOrigin (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:89057:19 <- /Users/skrish/amphtml/src/url.js:364:18)
	    at new Storage (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:80662:45 <- /Users/skrish/amphtml/src/service/storage-impl.js:58:35)
	    at /var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81050:14 <- /Users/skrish/amphtml/src/service/storage-impl.js:371:11
	    at getServiceInternal (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:74101:62 <- /Users/skrish/amphtml/src/service.js:246:10)
	    at getService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73943:10 <- /Users/skrish/amphtml/src/service.js:78:9)
	    at installStorageService (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:81046:58 <- /Users/skrish/amphtml/src/service/storage-impl.js:365:45)
	    at installRuntimeServices (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73008:49 <- /Users/skrish/amphtml/src/runtime.js:92:24)
	    at adoptShared (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:73072:3 <- /Users/skrish/amphtml/src/runtime.js:157:2)
Chrome 52.0.2743 (Mac OS X 10.11.6) runtime attachShadowDoc "after each" hook for "should install services and styles" FAILED
	TypeError: Cannot read property 'verify' of undefined
	    at Context.<anonymous> (/var/folders/nz/xmc89stj1bsczs9hj8tp9_p8005dqs/T/86cd75f7562b2de046ea7be99c8d7ffa.browserify:110343:21 <- /Users/skrish/amphtml/test/functional/test-runtime.js:550:21)
Chrome 52.0.2743 (Mac OS X 10.11.6): Executed 1641 of 2945 (13 FAILED) (skipped 1) (0 secs / 9.685 secs)
```

**Comment by mkhatib** [comment]
@sriramkrish85 I fixed the runtime split test failures yesterday. Was this a fresh run on master today?

**Comment by sriramkrish85** [comment]
looks fixed now
