### ISSUE TITLE
Fix tests in experiments

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#5041]
```
Chromium 51.0.2704 (Ubuntu 0.0.0) all-traffic-experiments-tests #randomlySelectUnsetPageExperiments handles experiment diverted path: control FAILED
	AssertionError: experiment is on: expected false to be true
	    at doAsserterAsyncAndAddThen (/home/travis/build/ampproject/amphtml/node_modules/chai-as-promised/lib/chai-as-promised.js:292:33)
	    at .<anonymous> (/home/travis/build/ampproject/amphtml/node_modules/chai-as-promised/lib/chai-as-promised.js:282:25)
	    at get (/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:5396:37)
	    at Context.<anonymous> (/tmp/f7c58e12910b6902c4d675cb4b5c39ac.browserify:3840:109 <- /home/travis/build/ampproject/amphtml/ads/google/a4a/test/test-traffic-experiments.js:102:35)
Chromium 51.0.2704 (Ubuntu 0.0.0): Executed 1724 of 2977 (22 FAILED) (skipped 24) (0 secs / 13.588 secs)
Chromium 51.0.2704 (Ubuntu 0.0.0) all-traffic-experiments-tests #randomlySelectUnsetPageExperiments handles experiment diverted path: experiment FAILED
	AssertionError: experiment is on: expected false to be true
	    at doAsserterAsyncAndAddThen (/home/travis/build/ampproject/amphtml/node_modules/chai-as-promised/lib/chai-as-promised.js:292:33)
	    at .<anonymous> (/home/travis/build/ampproject/amphtml/node_modules/chai-as-promised/lib/chai-as-promised.js:282:25)
	    at get (/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:5396:37)
	    at Context.<anonymous> (/tmp/f7c58e12910b6902c4d675cb4b5c39ac.browserify:3850:109 <- /home/travis/build/ampproject/amphtml/ads/google/a4a/test/test-traffic-experiments.js:114:35)
Chromium 51.0.2704 (Ubuntu 0.0.0): Executed 1725 of 2977 (23 FAILED) (skipped 24) (0 secs / 13.588 secs)
Chromium 51.0.2704 (Ubuntu 0.0.0) all-traffic-experiments-tests #randomlySelectUnsetPageExperiments handles multiple experiments FAILED
	AssertionError: expt_0 is on: expected false to be true
	    at doAsserterAsyncAndAddThen (/home/travis/build/ampproject/amphtml/node_modules/chai-as-promised/lib/chai-as-promised.js:292:33)
	    at .<anonymous> (/home/travis/build/ampproject/amphtml/node_modules/chai-as-promised/lib/chai-as-promised.js:282:25)
	    at get (/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:5396:37)
	    at Context.<anonymous> (/tmp/f7c58e12910b6902c4d675cb4b5c39ac.browserify:3877:95 <- /home/travis/build/ampproject/amphtml/ads/google/a4a/test/test-traffic-experiments.js:143:31)
Chromium 51.0.2704 (Ubuntu 0.0.0): Executed 1726 of 2977 (24 FAILED) (skipped 24) (0 secs / 13.588 secs)
Chromium 51.0.2704 (Ubuntu 0.0.0) all-traffic-experiments-tests #randomlySelectUnsetPageExperiments handles multi-way branches FAILED
	AssertionError: expt_0 is on: expected false to be true
	    at doAsserterAsyncAndAddThen (/home/travis/build/ampproject/amphtml/node_modules/chai-as-promised/lib/chai-as-promised.js:292:33)
	    at .<anonymous> (/home/travis/build/ampproject/amphtml/node_modules/chai-as-promised/lib/chai-as-promised.js:282:25)
	    at get (/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:5396:37)
	    at Context.<anonymous> (/tmp/f7c58e12910b6902c4d675cb4b5c39ac.browserify:3904:95 <- /home/travis/build/ampproject/amphtml/ads/google/a4a/test/test-traffic-experiments.js:175:31)
Chromium 51.0.2704 (Ubuntu 0.0.0): Executed 1727 of 2977 (25 FAILED) (skipped 24) (0 secs / 13.589 secs)
Chromium 51.0.2704 (Ubuntu 0.0.0) all-traffic-experiments-tests #randomlySelectUnsetPageExperiments handles multiple experiments with multi-way branches FAILED
	AssertionError: expt_0 is on: expected false to be true
	    at doAsserterAsyncAndAddThen (/home/travis/build/ampproject/amphtml/node_modules/chai-as-promised/lib/chai-as-promised.js:292:33)
	    at .<anonymous> (/home/travis/build/ampproject/amphtml/node_modules/chai-as-promised/lib/chai-as-promised.js:282:25)
	    at get (/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:5396:37)
	    at Context.<anonymous> (/tmp/f7c58e12910b6902c4d675cb4b5c39ac.browserify:3940:95 <- /home/travis/build/ampproject/amphtml/ads/google/a4a/test/test-traffic-experiments.js:213:31)
```

**Comment by dvoytenko** [comment]
Fixed by random fix.
