### ISSUE TITLE
AMP Form Flake

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#5775]
```
Chromium 51.0.2704 (Ubuntu 0.0.0) amp-form should allow rendering responses through templates FAILED
	AssertionError: expected null not to be null
	    at doAsserterAsyncAndAddThen (/home/travis/build/ampproject/amphtml/node_modules/chai-as-promised/lib/chai-as-promised.js:292:33)
	    at .<anonymous> (/home/travis/build/ampproject/amphtml/node_modules/chai-as-promised/lib/chai-as-promised.js:282:25)
	    at get (/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:5396:37)
	    at /tmp/c4798cd841690771cc0b2346e973d8e6.browserify:38735:43 <- /home/travis/build/ampproject/amphtml/extensions/amp-form/0.1/test/test-amp-form.js:451:42
```

**Comment by jridgewell** [comment]
Ha, this is because I [made](https://github.com/ampproject/amphtml/pull/5758) `timer` code run faster.
