### ISSUE TITLE
loadExtension tests failed

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#5787]
```
Chrome 54.0.2840 (Mac OS X 10.11.6) Extensions   loadExtension   should insert extension script correctly FAILED
	TypeError: Cannot read property 'amp-test' of undefined
	    at Context.<anonymous> (/var/folders/zy/2yz64_hx4y13mtfkjgyrw31h00bq__/T/702fd9c4794944464cdebe00d90ca033.browserify:108803:41 <- /Users/yuxichen/dev/amphtml/test/functional/test-extensions.js:320:41)
Chrome 54.0.2840 (Mac OS X 10.11.6) Extensions   loadExtension   should not insert when script exists in head FAILED
	TypeError: Cannot read property 'amp-test' of undefined
	    at Context.<anonymous> (/var/folders/zy/2yz64_hx4y13mtfkjgyrw31h00bq__/T/702fd9c4794944464cdebe00d90ca033.browserify:108829:41 <- /Users/yuxichen/dev/amphtml/test/functional/test-extensions.js:356:41)
Chrome 54.0.2840 (Mac OS X 10.11.6) Extensions   installExtensionsInChildWindow   should install extensions FAILED
	AssertionError: expected undefined to be true
	    at doAsserterAsyncAndAddThen (/Users/yuxichen/dev/amphtml/node_modules/chai-as-promised/lib/chai-as-promised.js:292:33)
	    at Assertion.<anonymous> (/Users/yuxichen/dev/amphtml/node_modules/chai-as-promised/lib/chai-as-promised.js:282:25)
	    at Assertion.get (/Users/yuxichen/dev/amphtml/node_modules/chai/chai.js:5396:37)
	    at /var/folders/zy/2yz64_hx4y13mtfkjgyrw31h00bq__/T/702fd9c4794944464cdebe00d90ca033.browserify:108919:64 <- /Users/yuxichen/dev/amphtml/test/functional/test-extensions.js:458:63

```

**Comment by cramforce** [comment]
@muxin Could you track this down?

**Comment by muxin** [comment]
Looking

**Comment by dvoytenko** [comment]
This is probably due to #5625 - at least not being helped by...
