### ISSUE TITLE
amp-form user-valid tests failed

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#5789]
```
Chrome 54.0.2840 (Mac OS X 10.11.6) amp-form User Validity should manage valid/invalid on input/fieldset/form on submit FAILED
	AssertionError: expected 'user-valid valid' to include 'user-invalid'
	    at /var/folders/zy/2yz64_hx4y13mtfkjgyrw31h00bq__/T/702fd9c4794944464cdebe00d90ca033.browserify:39341:39 <- /Users/yuxichen/dev/amphtml/extensions/amp-form/0.1/test/test-amp-form.js:724:38
Chrome 54.0.2840 (Mac OS X 10.11.6) amp-form User Validity should manage valid/invalid on input user interaction FAILED
	AssertionError: expected 'user-valid valid' to include 'user-invalid'
	    at /var/folders/zy/2yz64_hx4y13mtfkjgyrw31h00bq__/T/702fd9c4794944464cdebe00d90ca033.browserify:39377:39 <- /Users/yuxichen/dev/amphtml/extensions/amp-form/0.1/test/test-amp-form.js:760:38

```

**Comment by jridgewell** [comment]
Probably related to https://github.com/ampproject/amphtml/issues/5775.
