### ISSUE TITLE
Super flakey a4a integration test

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#6423]
```
Chrome 54.0.2840 (Linux 0.0.0) integration test: a4a should render a single AMP ad in a friendly iframe FAILED
	AssertionError: iframe doc: expected null to be truthy
	    at doAsserterAsyncAndAddThen (/home/travis/build/ampproject/amphtml/node_modules/chai-as-promised/lib/chai-as-promised.js:292:33)
	    at Assertion.<anonymous> (/home/travis/build/ampproject/amphtml/node_modules/chai-as-promised/lib/chai-as-promised.js:282:25)
	    at Assertion.get (/home/travis/build/ampproject/amphtml/node_modules/chai/chai.js:5396:37)
	    at expectRenderedInFriendlyIframe (/tmp/1b36fa6b09ef035ee51fbc50e2dcc2b8.browserify:11583:44 <- /home/travis/build/ampproject/amphtml/extensions/amp-a4a/0.1/test/test-a4a-integration.js:49:44)
	    at /tmp/1b36fa6b09ef035ee51fbc50e2dcc2b8.browserify:11653:7 <- /home/travis/build/ampproject/amphtml/extensions/amp-a4a/0.1/test/test-a4a-integration.js:118:6
```

**Comment by tdrl** [comment]
Looks like a race condition on whether the iframe content is loaded when we go to inspect it.  Working on a fix now.
