### ISSUE TITLE
Messaging with awaitResponse shouldn't error

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#6546]
```
Uncaught (in promise) Error: No messaging channel: undefined
    at Pi (http://localhost:8000/dist/v0.js:353:304)
    at Si (http://localhost:8000/dist/v0.js:352:84)
    at Mi.f.sendMessageAwaitResponse (http://localhost:8000/dist/v0.js:351:51)
    at Mi.f.requestFullOverlay (http://localhost:8000/dist/v0.js:346:252)
    at mi.f.enterLightboxMode (http://localhost:8000/dist/v0.js:303:50)
    at Z.push.f.g.activate (http://localhost:8000/dist/v0/amp-image-lightbox-0.1.js:48:260)
    at Z.f.executeAction (http://localhost:8000/dist/v0.js:130:297)
    at HTMLElement.b.sd (http://localhost:8000/dist/v0.js:160:131)
    at HTMLElement.b.enqueAction (http://localhost:8000/dist/v0.js:159:442)
    at dg (http://localhost:8000/dist/v0.js:195:163)
```

We should also figure out why it's `undefined`.

**Comment by jridgewell** [comment]
Fixed by https://github.com/ampproject/amphtml/pull/6544?

**Comment by muxin** [comment]
Yeah, this is fixed by #6544.

**Comment by jridgewell** [comment]
Unfortunately, there are a few more that will still cause this:

- https://github.com/ampproject/amphtml/pull/6508/files#diff-4355db0ba8ae714ce669b977af9c8dfdR785
- https://github.com/ampproject/amphtml/pull/6508/files#diff-4355db0ba8ae714ce669b977af9c8dfdR796

Both from History class. We need to either not call the Viewer update methods if there's no viewer, or Viewer needs to decide how to handle these cases when there's not a viewer.

**Comment by muxin** [comment]
For the history errors, did you see them? I thought we call `HistoryBindingVirtual_.push()` to `sendMessageAwaitResponse` when there's a viewer. If there's no viewer, the `sendMessageAwaitResponse` should not be called.

**Comment by jridgewell** [comment]
Whoot, @muxin pointed out that History uses a different implementation in viewer and normal contexts.
