### ISSUE TITLE
TypeError: doubleclick Error on emitLifecycleEvent adRequestEnd: this.g.setQqid is not a function

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#6876]
```
TypeError: doubleclick Error on emitLifecycleEvent adRequestEnd: this.g.setQqid is not a function
    at bc.push.f.k.emitLifecycleEvent (https://cdn.ampproject.org/rtv/001482359659944/v0/amp-ad-network-doubleclick-impl-0.1.js:94:153)
    at bc.c (https://cdn.ampproject.org/rtv/001482359659944/v0/amp-ad-network-doubleclick-impl-0.1.js:62:112)
    at https://cdn.ampproject.org/rtv/001482359659944/v0/amp-ad-network-doubleclick-impl-0.1.js:68:37
```
Sample page: https://cdn.ampproject.org/v/www.mynet.com/magazin/detay/magazin/acun-ilicalidan-sevgilisi-seyma-subasi-ve-eski-esi-zeynep-ilicaliya-62-milyon-dolarlik-jest/85301/amp/?amp_js_v=6

@keithwrightbos Is this error expected?

**Comment by jridgewell** [comment]
Fixed by https://github.com/ampproject/amphtml/pull/6505.
