### ISSUE TITLE
amp-analytics TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#6885]
```
TypeError: Cannot read property '1' of null
    at pc (https://cdn.ampproject.org/rtv/011481838084444/v0/amp-analytics-0.1.js:122:175)
    at qc (https://cdn.ampproject.org/rtv/011481838084444/v0/amp-analytics-0.1.js:122:300)
    at https://cdn.ampproject.org/rtv/011481838084444/v0/amp-analytics-0.1.js:121:380
    at https://cdn.ampproject.org/rtv/011481838084444/v0/amp-analytics-0.1.js:5:812
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at wa (https://cdn.ampproject.org/rtv/011481838084444/v0/amp-analytics-0.1.js:5:737)
    at Y (https://cdn.ampproject.org/rtv/011481838084444/v0/amp-analytics-0.1.js:121:205)
    at nc (https://cdn.ampproject.org/rtv/011481838084444/v0/amp-analytics-0.1.js:117:471)
    at hc.push.f.k.xa (https://cdn.ampproject.org/rtv/011481838084444/v0/amp-analytics-0.1.js:116:108)
```

The error occurs in https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/amp-analytics.js#L550 when the `match` is `null`.

Sample page: https://cdn.ampproject.org/v/www.heraldextra.com/news/community/animals/how-to-keep-it-a-toasty-winter-for-furry-friends/article_0f6a093e-69db-5618-a62d-3540caad4245.amp.html?amp_js_v=6

**Comment by avimehta** [comment]
looking.

**Comment by avimehta** [comment]
so this happens because there is a newline character in the string and the regex does not match anything when there is a newline character. 

How often does this happen? I can fix it for today's release but would just prefer to test it more if it is not widespread.

**Comment by muxin** [comment]
Thanks for fixing this! It's not widespread so I'll include the change in this week's canary.
