### ISSUE TITLE
Test failure on Mac due to browserslist not liking op_mini

### ISSUE THREAD

**Issue by jonkeller** [ampproject/amphtml#7031]
When running "gulp test --watch --safari --files=./extensions/amp-a4a/0.1/test/test-amp-a4a.js" on Mac, multiple occurrences of this are seen:

UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): BrowserslistError: Unknown browser query `op_mini all`

This results in the CSS not getting built. I suspect this is due to conflicting version requirements of browserslist, as shown below:
amp-html@0.1.0 /Users/jonkeller/workspace/jonkeller-amphtml/amphtml
├─┬ autoprefixer@6.1.1
│ ├── browserslist@1.0.1
├─┬ cssnano@3.3.2
│ ├─┬ postcss-merge-rules@2.1.1
│ │ ├── browserslist@1.5.2

A temporary workaround is to manually set the BROWSERSLIST env variable to something that excludes Opera, such as:

export BROWSERSLIST="last 2 Safari versions"

**Comment by aghassemi** [comment]
@jonkeller Please run `npm install` and try again. We recently upgraded our css dependencies to resolve this issue.

**Comment by jonkeller** [comment]
@aghassemi Unfortunately the issue is not resolved.
I ran git pull (from master) and then npm install. Output looked hopeful:
 jonkeller@jonkeller-macbookpro  ~/workspace/amphtml   master  npm install
amp-html@0.1.0 /Users/jonkeller/workspace/amphtml
├─┬ autoprefixer@6.6.1
│ ├── browserslist@1.5.2
│ └── normalize-range@0.1.2
├── postcss@5.2.10
└─┬ postcss-import@9.1.0
  └─┬ promise-each@2.2.0
    └── any-promise@0.1.0

However when re-running the gulp command above (after first running gulp clean), I got very similar output to what I had gotten originally:

[18:41:46] Using gulpfile ~/workspace/amphtml/gulpfile.js
[18:41:46] Starting 'build'...
[18:41:46] Bundling alp.js
[18:41:46] Bundling service-worker.js
[18:41:46] Recompiling CSS.
[18:41:46] Processing 3p/frame.max.html
[18:41:46] Processing 3p/nameframe.max.html
[18:41:46] 'build' errored after 386 ms
[18:41:46] BrowserslistError: Unknown browser query `op_mini all`
    at error (/Users/jonkeller/workspace/amphtml/node_modules/browserslist/index.js:23:15)
    at /Users/jonkeller/workspace/amphtml/node_modules/browserslist/index.js:90:13
    at Array.forEach (native)
    at browserslist (/Users/jonkeller/workspace/amphtml/node_modules/browserslist/index.js:62:16)
    at isSupported (/Users/jonkeller/workspace/amphtml/node_modules/caniuse-api/dist/index.js:75:10)
    at /Users/jonkeller/workspace/amphtml/node_modules/postcss-merge-rules/dist/lib/ensureCompatibility.js:95:66
    at /Users/jonkeller/workspace/amphtml/node_modules/postcss-selector-parser/dist/selectors/container.js:170:26
    at Selector.each (/Users/jonkeller/workspace/amphtml/node_modules/postcss-selector-parser/dist/selectors/container.js:153:22)
    at Selector.walk (/Users/jonkeller/workspace/amphtml/node_modules/postcss-selector-parser/dist/selectors/container.js:169:21)
    at /Users/jonkeller/workspace/amphtml/node_modules/postcss-selector-parser/dist/selectors/container.js:173:31
    at Root.each (/Users/jonkeller/workspace/amphtml/node_modules/postcss-selector-parser/dist/selectors/container.js:153:22)
    at Root.walk (/Users/jonkeller/workspace/amphtml/node_modules/postcss-selector-parser/dist/selectors/container.js:169:21)
    at Processor.func (/Users/jonkeller/workspace/amphtml/node_modules/postcss-merge-rules/dist/lib/ensureCompatibility.js:80:17)
    at Processor.process (/Users/jonkeller/workspace/amphtml/node_modules/postcss-selector-parser/dist/processor.js:34:14)
    at /Users/jonkeller/workspace/amphtml/node_modules/postcss-merge-rules/dist/lib/ensureCompatibility.js:121:12
    at Array.every (native)
    at ensureCompatibility (/Users/jonkeller/workspace/amphtml/node_modules/postcss-merge-rules/dist/lib/ensureCompatibility.js:77:22)
    at canMerge (/Users/jonkeller/workspace/amphtml/node_modules/postcss-merge-rules/dist/index.js:74:44)
    at /Users/jonkeller/workspace/amphtml/node_modules/postcss-merge-rules/dist/index.js:222:24
    at /Users/jonkeller/workspace/amphtml/node_modules/postcss/lib/container.js:241:28
    at /Users/jonkeller/workspace/amphtml/node_modules/postcss/lib/container.js:148:26
    at Root.each (/Users/jonkeller/workspace/amphtml/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/Users/jonkeller/workspace/amphtml/node_modules/postcss/lib/container.js:147:21)
    at Root.walkRules (/Users/jonkeller/workspace/amphtml/node_modules/postcss/lib/container.js:239:25)
    at /Users/jonkeller/workspace/amphtml/node_modules/postcss-merge-rules/dist/index.js:274:13
    at LazyResult.run (/Users/jonkeller/workspace/amphtml/node_modules/postcss/lib/lazy-result.js:276:20)
    at /Users/jonkeller/workspace/amphtml/node_modules/postcss/lib/lazy-result.js:190:37
    at LazyResult.asyncTick (/Users/jonkeller/workspace/amphtml/node_modules/postcss/lib/lazy-result.js:204:15)

**Comment by aghassemi** [comment]
@jonkeller Would you please remove `node_modules` directory and doing `npm install`, `gulp build` again?

**Comment by jonkeller** [comment]
@aghassemi Yikes, you're right, I did forget to rm node_modules! After your change + doing that, yes, this bug is gone. Thank you!

**Comment by aghassemi** [comment]
Great! Closing the issue. https://github.com/ampproject/amphtml/pull/7041 should prevent this in the future.
