### ISSUE TITLE
form proxy failing on `id` when `name=id`

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#7062]
Happening in **prod** and **canary** as well.

If there is a `select` in a form with `name="id"`, `amp-form` initialization fails with:
```
TypeError: target.id.substring is not a function
    at ActionService.installActionHandler (http://localhost:8000/dist/amp.js:15191:46)
    at new AmpForm (http://localhost:8000/dist/v0/amp-form-0.1.max.js:166:19)
    at http://localhost:8000/dist/v0/amp-form-0.1.max.js:655:7
    at Array.forEach (native)
    at http://localhost:8000/dist/v0/amp-form-0.1.max.js:654:34
    at onDocumentState (http://localhost:8000/dist/v0/amp-form-0.1.max.js:3956:5)
    at Object.onDocumentReady (http://localhost:8000/dist/v0/amp-form-0.1.max.js:3944:3)
    at installSubmissionHandlers (http://localhost:8000/dist/v0/amp-form-0.1.max.js:653:21)
    at http://localhost:8000/dist/v0/amp-form-0.1.max.js:668:7
    at Object.installStyles (http://localhost:8000/dist/v0/amp-form-0.1.max.js:7419:5)
```

Looks like `target.id` in `installActionHandler` returns an `array` in this case instead of empty string. Not sure why the proxy is not kicking in, proxy is definitely installed by the time `target.id` is called. Happening in latest Chrome so not a legacy browser issue.

/to @dvoytenko

**Comment by dvoytenko** [comment]
/cc @erwinmombay @mkhatib 

The work to fix these issues is ongoing. I'll see if we can have some short-term solution in the meantime.

**Comment by aghassemi** [comment]
Some sample Urls with the failure: 

http://www.boxingnewsandviews.com/2017/01/17/lemieux-stevens/amp/?amp_js_v=6
https://www.britroyals.com/kings.asp?id=george5&amp_js_v=6
