### ISSUE TITLE
Bug: test-placement.js tests failing

### ISSUE THREAD

**Issue by eduardcotmrf** [ampproject/amphtml#7366]
I've just updated the amp-html from master in my local enviroment and some test are failing.

This seems related to https://github.com/ampproject/amphtml/pull/7153.

If I run everything with: gulp test, everything works fine.
But if I do:
```
gulp clean
gulp build
gulp test --files=extensions/amp-auto-ads/0.1/test/test-placement.js --nobuild
```

I get this output:

```
[13:21:41] Starting 'test'...
[13:21:41] Webserver started at http://localhost:31862
[13:21:41] Started test responses server on localhost:31862
06 02 2017 13:21:42.854:WARN [watcher]: Pattern "/Users/eduardcot/amp/mrf/amphtml/dist.tools/**/*.js" does not match any file.
Chrome 55.0.2883 (Mac OS X 10.12.0) placement placeAd should place an ad with the correct attributes FAILED
	TypeError: Cannot read property 'create' of undefined
	    at CustomAmpElement.CustomElementsV1 (dist/v0/amp-ad-0.1.max.js:6702:54)
	    at CustomAmpElement.BaseCustomElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14284:104 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:430:25)
	    at new CustomAmpElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14245:103 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:404:24)
	    at HTMLDocument.document.createElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:2805:30 <- node_modules/document-register-element/build/document-register-element.node.js:1368:0)
	    at HTMLDocument.document.createElement (dist/v0/amp-ad-0.1.max.js:6730:30)
	    at createElementWithAttributes (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:16163:21 <- /Users/eduardcot/amp/mrf/amphtml/src/dom.js:160:22)
	    at Placement.createAdElement_ (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:712:54 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:203:8)
	    at /var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:681:38 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:171:31
Chrome 55.0.2883 (Mac OS X 10.12.0) placement placeAd should place an ad with the correct margins FAILED
	TypeError: Cannot read property 'create' of undefined
	    at CustomAmpElement.CustomElementsV1 (dist/v0/amp-ad-0.1.max.js:6702:54)
	    at CustomAmpElement.BaseCustomElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14284:104 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:430:25)
	    at new CustomAmpElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14245:103 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:404:24)
	    at HTMLDocument.document.createElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:2805:30 <- node_modules/document-register-element/build/document-register-element.node.js:1368:0)
	    at HTMLDocument.document.createElement (dist/v0/amp-ad-0.1.max.js:6730:30)
	    at createElementWithAttributes (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:16163:21 <- /Users/eduardcot/amp/mrf/amphtml/src/dom.js:160:22)
	    at Placement.createAdElement_ (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:712:54 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:203:8)
	    at /var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:681:38 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:171:31
Chrome 55.0.2883 (Mac OS X 10.12.0) placement placeAd should place an ad with top margin only FAILED
	TypeError: Cannot read property 'create' of undefined
	    at CustomAmpElement.CustomElementsV1 (dist/v0/amp-ad-0.1.max.js:6702:54)
	    at CustomAmpElement.BaseCustomElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14284:104 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:430:25)
	    at new CustomAmpElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14245:103 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:404:24)
	    at HTMLDocument.document.createElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:2805:30 <- node_modules/document-register-element/build/document-register-element.node.js:1368:0)
	    at HTMLDocument.document.createElement (dist/v0/amp-ad-0.1.max.js:6730:30)
	    at createElementWithAttributes (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:16163:21 <- /Users/eduardcot/amp/mrf/amphtml/src/dom.js:160:22)
	    at Placement.createAdElement_ (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:712:54 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:203:8)
	    at /var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:681:38 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:171:31
Chrome 55.0.2883 (Mac OS X 10.12.0) placement placeAd should place an ad with bottom margin only FAILED
	TypeError: Cannot read property 'create' of undefined
	    at CustomAmpElement.CustomElementsV1 (dist/v0/amp-ad-0.1.max.js:6702:54)
	    at CustomAmpElement.BaseCustomElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14284:104 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:430:25)
	    at new CustomAmpElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14245:103 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:404:24)
	    at HTMLDocument.document.createElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:2805:30 <- node_modules/document-register-element/build/document-register-element.node.js:1368:0)
	    at HTMLDocument.document.createElement (dist/v0/amp-ad-0.1.max.js:6730:30)
	    at createElementWithAttributes (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:16163:21 <- /Users/eduardcot/amp/mrf/amphtml/src/dom.js:160:22)
	    at Placement.createAdElement_ (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:712:54 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:203:8)
	    at /var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:681:38 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:171:31
Chrome 55.0.2883 (Mac OS X 10.12.0) placement placeAd should place an ad with no margins FAILED
	TypeError: Cannot read property 'create' of undefined
	    at CustomAmpElement.CustomElementsV1 (dist/v0/amp-ad-0.1.max.js:6702:54)
	    at CustomAmpElement.BaseCustomElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14284:104 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:430:25)
	    at new CustomAmpElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14245:103 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:404:24)
	    at HTMLDocument.document.createElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:2805:30 <- node_modules/document-register-element/build/document-register-element.node.js:1368:0)
	    at HTMLDocument.document.createElement (dist/v0/amp-ad-0.1.max.js:6730:30)
	    at createElementWithAttributes (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:16163:21 <- /Users/eduardcot/amp/mrf/amphtml/src/dom.js:160:22)
	    at Placement.createAdElement_ (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:712:54 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:203:8)
	    at /var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:681:38 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:171:31
Chrome 55.0.2883 (Mac OS X 10.12.0) placement placeAd should report placement placed when resize allowed FAILED
	TypeError: Cannot read property 'create' of undefined
	    at CustomAmpElement.CustomElementsV1 (dist/v0/amp-ad-0.1.max.js:6702:54)
	    at CustomAmpElement.BaseCustomElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14284:104 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:430:25)
	    at new CustomAmpElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14245:103 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:404:24)
	    at HTMLDocument.document.createElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:2805:30 <- node_modules/document-register-element/build/document-register-element.node.js:1368:0)
	    at HTMLDocument.document.createElement (dist/v0/amp-ad-0.1.max.js:6730:30)
	    at createElementWithAttributes (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:16163:21 <- /Users/eduardcot/amp/mrf/amphtml/src/dom.js:160:22)
	    at Placement.createAdElement_ (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:712:54 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:203:8)
	    at /var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:681:38 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:171:31
Chrome 55.0.2883 (Mac OS X 10.12.0) placement placeAd should report resize failed when resize not allowed FAILED
	TypeError: Cannot read property 'create' of undefined
	    at CustomAmpElement.CustomElementsV1 (dist/v0/amp-ad-0.1.max.js:6702:54)
	    at CustomAmpElement.BaseCustomElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14284:104 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:430:25)
	    at new CustomAmpElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14245:103 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:404:24)
	    at HTMLDocument.document.createElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:2805:30 <- node_modules/document-register-element/build/document-register-element.node.js:1368:0)
	    at HTMLDocument.document.createElement (dist/v0/amp-ad-0.1.max.js:6730:30)
	    at createElementWithAttributes (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:16163:21 <- /Users/eduardcot/amp/mrf/amphtml/src/dom.js:160:22)
	    at Placement.createAdElement_ (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:712:54 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:203:8)
	    at /var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:681:38 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:171:31
Chrome 55.0.2883 (Mac OS X 10.12.0) placement Ad positioning should place the ad before the anchor FAILED
	TypeError: Cannot read property 'create' of undefined
	    at CustomAmpElement.CustomElementsV1 (dist/v0/amp-ad-0.1.max.js:6702:54)
	    at CustomAmpElement.BaseCustomElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14284:104 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:430:25)
	    at new CustomAmpElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14245:103 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:404:24)
	    at HTMLDocument.document.createElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:2805:30 <- node_modules/document-register-element/build/document-register-element.node.js:1368:0)
	    at HTMLDocument.document.createElement (dist/v0/amp-ad-0.1.max.js:6730:30)
	    at createElementWithAttributes (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:16163:21 <- /Users/eduardcot/amp/mrf/amphtml/src/dom.js:160:22)
	    at Placement.createAdElement_ (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:712:54 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:203:8)
	    at /var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:681:38 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:171:31
Chrome 55.0.2883 (Mac OS X 10.12.0) placement Ad positioning should place the ad after the anchor FAILED
	TypeError: Cannot read property 'create' of undefined
	    at CustomAmpElement.CustomElementsV1 (dist/v0/amp-ad-0.1.max.js:6702:54)
	    at CustomAmpElement.BaseCustomElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14284:104 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:430:25)
	    at new CustomAmpElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14245:103 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:404:24)
	    at HTMLDocument.document.createElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:2805:30 <- node_modules/document-register-element/build/document-register-element.node.js:1368:0)
	    at HTMLDocument.document.createElement (dist/v0/amp-ad-0.1.max.js:6730:30)
	    at createElementWithAttributes (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:16163:21 <- /Users/eduardcot/amp/mrf/amphtml/src/dom.js:160:22)
	    at Placement.createAdElement_ (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:712:54 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:203:8)
	    at /var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:681:38 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:171:31
Chrome 55.0.2883 (Mac OS X 10.12.0) placement Ad positioning should place the ad as the first child of the anchor FAILED
	TypeError: Cannot read property 'create' of undefined
	    at CustomAmpElement.CustomElementsV1 (dist/v0/amp-ad-0.1.max.js:6702:54)
	    at CustomAmpElement.BaseCustomElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14284:104 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:430:25)
	    at new CustomAmpElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14245:103 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:404:24)
	    at HTMLDocument.document.createElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:2805:30 <- node_modules/document-register-element/build/document-register-element.node.js:1368:0)
	    at HTMLDocument.document.createElement (dist/v0/amp-ad-0.1.max.js:6730:30)
	    at createElementWithAttributes (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:16163:21 <- /Users/eduardcot/amp/mrf/amphtml/src/dom.js:160:22)
	    at Placement.createAdElement_ (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:712:54 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:203:8)
	    at /var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:681:38 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:171:31
Chrome 55.0.2883 (Mac OS X 10.12.0) placement Ad positioning should place the ad as the last child of the anchor FAILED
	TypeError: Cannot read property 'create' of undefined
	    at CustomAmpElement.CustomElementsV1 (dist/v0/amp-ad-0.1.max.js:6702:54)
	    at CustomAmpElement.BaseCustomElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14284:104 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:430:25)
	    at new CustomAmpElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14245:103 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:404:24)
	    at HTMLDocument.document.createElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:2805:30 <- node_modules/document-register-element/build/document-register-element.node.js:1368:0)
	    at HTMLDocument.document.createElement (dist/v0/amp-ad-0.1.max.js:6730:30)
	    at createElementWithAttributes (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:16163:21 <- /Users/eduardcot/amp/mrf/amphtml/src/dom.js:160:22)
	    at Placement.createAdElement_ (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:712:54 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:203:8)
	    at /var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:681:38 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:171:31
Chrome 55.0.2883 (Mac OS X 10.12.0) placement Ad positioning should place the ad inside the 2nd anchor with class name FAILED
	TypeError: Cannot read property 'create' of undefined
	    at CustomAmpElement.CustomElementsV1 (dist/v0/amp-ad-0.1.max.js:6702:54)
	    at CustomAmpElement.BaseCustomElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14284:104 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:430:25)
	    at new CustomAmpElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:14245:103 <- /Users/eduardcot/amp/mrf/amphtml/src/custom-element.js:404:24)
	    at HTMLDocument.document.createElement (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:2805:30 <- node_modules/document-register-element/build/document-register-element.node.js:1368:0)
	    at HTMLDocument.document.createElement (dist/v0/amp-ad-0.1.max.js:6730:30)
	    at createElementWithAttributes (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:16163:21 <- /Users/eduardcot/amp/mrf/amphtml/src/dom.js:160:22)
	    at Placement.createAdElement_ (/var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:712:54 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:203:8)
	    at /var/folders/1s/wb13vhc53bs6l_fz8x2gvw3r0000gn/T/1e026969d9c5b644913d5e6f758a8bec.browserify:681:38 <- /Users/eduardcot/amp/mrf/amphtml/extensions/amp-auto-ads/0.1/placement.js:171:31
Chrome 55.0.2883 (Mac OS X 10.12.0): Executed 25 of 25 (12 FAILED) (0.469 secs / 0.356 secs)
```

This happens to me with your master branch clean.

**Comment by lannka** [comment]
@tlong2 do you want to take a look?

**Comment by tlong2** [comment]
The problem seems to be that the tests are inserting real <amp-ad> elements. When running gulp test, this is fine but when running an individual file's tests the amp-ad element isn't registered or something so there is an error?

Could someone explain what the different in test environment is between gult test and gulp test files=...
Or is this simply that there is leakage between tests and the extensions/amp-ad tests don't tidy up after themselves and leave the amp-ad element registered?

**Comment by lannka** [comment]
@tlong2 yep, there're leakage between tests.

We typically create iframe for each test case. `describes.realWin()` will help you do that.

**Comment by tlong2** [comment]
Got fixed by https://github.com/ampproject/amphtml/pull/7535

**Comment by tlong2** [comment]
Seems to have been broken again. Tests fail again when running gulp test --files=extensions/amp-auto-ads/0.1/test/test-*

**Comment by lannka** [comment]
@erwinmombay do you know what action should @tlong2 take so that I can assign this to him?

**Comment by erwinmombay** [comment]
@lannka i think they need to be part of the org unfortunately

**Comment by jasti** [comment]
@tlong2 do you have an update on this?

**Comment by lannka** [comment]
Tried locally, it's passing now.
