### ISSUE TITLE
amp-auto-ads: JSON Syntax errors

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#8998]
Nearly 40,000 (sampled) reports!

```
Error: amp-auto-ads config xhr failed: SyntaxError: Unexpected end of JSON input
    at ta (https://cdn.ampproject.org/rtv/011493083583453/v0.js:9:358)
    at ra.f.Hd (https://cdn.ampproject.org/rtv/011493083583453/v0.js:5:199)
    at ra.f.error (https://cdn.ampproject.org/rtv/011493083583453/v0.js:5:309)
    at https://cdn.ampproject.org/rtv/011493083583453/v0/amp-auto-ads-0.1.js:17:259

// Unminified
Error: amp-auto-ads config xhr failed: SyntaxError: Unexpected end of JSON input
    at Error (https://raw.githubusercontent.com/ampproject/amphtml/1493083583453/src/log.js:441:17)
    at ra.f.apply (https://raw.githubusercontent.com/ampproject/amphtml/1493083583453/src/log.js:197:21)
    at ra.f.apply (https://raw.githubusercontent.com/ampproject/amphtml/1493083583453/src/log.js:211:19)
    at https://raw.githubusercontent.com/ampproject/amphtml/1493083583453/extensions/amp-auto-ads/0.1/amp-auto-ads.js:75:11
```

This leads into the next [bug](https://github.com/ampproject/amphtml/issues/8997).

/to @tlong2

**Comment by zapic0** [comment]
I'm still getting this error

**Comment by jridgewell** [comment]
It's likely your json configuration is incorrect, then.
