### ISSUE TITLE
gulp test fails without running any tests

### ISSUE THREAD

**Issue by taymonbeal** [ampproject/amphtml#9106]
Test log:

```
/home/taymon/amphtml/build-system/tasks/visual-diff.js:91
  let webpage = '';
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/taymon/amphtml/build-system/tasks/index.js:35:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/taymon/amphtml/gulpfile.js:40:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/home/taymon/.nvm/versions/node/v4.7.2/lib/node_modules/gulp/bin/gulp.js:116:3)
```

**Comment by jridgewell** [comment]
The issue is that everything under `/build-system` is not compiled from ES6 to ES5.
