### ISSUE TITLE
Errors when attaching shadow doc with slides

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#9291]
Open the carousel here: https://www.standard.co.uk/stayingin/tvfilm/bafta-tv-awards-2017-date-time-nominees-and-how-to-watch-in-the-uk-a3537786.html?ines_tg=1

and close it to see the error message. You'll need to let the service worker install

```
custom-element.js:1049 Uncaught TypeError: Cannot read property 'remove' of null
    at HTMLElement.Zf.b.disconnectedCallback (https://cdn.ampproject.org/shadow-v0.js:168:21)
    at https://cdn.ampproject.org/rtv/011494446565961/v0/amp-carousel-0.1.js:21:318
    at Array.forEach (native)
    at S.push.f.f.buildSlides (https://cdn.ampproject.org/rtv/011494446565961/v0/amp-carousel-0.1.js:21:142)
    at S.push.f.f.buildCarousel (https://cdn.ampproject.org/rtv/011494446565961/v0/amp-carousel-0.1.js:16:326)
    at S.push.f.f.buildCallback (https://cdn.ampproject.org/rtv/011494446565961/v0/amp-carousel-0.1.js:11:465)
    at HTMLElement.Zf.b.build (https://cdn.ampproject.org/shadow-v0.js:156:514)
    at ch.f.build (https://cdn.ampproject.org/shadow-v0.js:234:151)
    at mh (https://cdn.ampproject.org/shadow-v0.js:255:244)
    at qh (https://cdn.ampproject.org/shadow-v0.js:254:460)
Zf.b.disconnectedCallback @ custom-element.js:1049
(anonymous) @ slidescroll.js:184
push.f.f.buildSlides @ slidescroll.js:178
push.f.f.buildCarousel @ base-slides.js:51
push.f.f.buildCallback @ base-carousel.js:45
Zf.b.build @ custom-element.js:718
f.build @ resource.js:290
mh @ resources-impl.js:552
qh @ resources-impl.js:511
f.upgraded @ resources-impl.js:611
Zf.b.rc @ custom-element.js:656
Zf.b.ze @ custom-element.js:1037
Zf.b.connectedCallback @ custom-element.js:975
i @ shell.js:232
(anonymous) @ shell.js:102
log.js:467 Uncaught Error: No ampdoc found for [object HTMLElement]
    at va (https://cdn.ampproject.org/shadow-v0.js:8:169)
    at ta.f.createError (https://cdn.ampproject.org/shadow-v0.js:4:36)
    at wf.getAmpDoc (https://cdn.ampproject.org/shadow-v0.js:130:512)
    at HTMLElement.Zf.b.connectedCallback (https://cdn.ampproject.org/shadow-v0.js:162:11)
    at https://cdn.ampproject.org/rtv/011494446565961/v0/amp-carousel-0.1.js:21:318
    at Array.forEach (native)
    at S.push.f.f.buildSlides (https://cdn.ampproject.org/rtv/011494446565961/v0/amp-carousel-0.1.js:21:142)
    at S.push.f.f.buildCarousel (https://cdn.ampproject.org/rtv/011494446565961/v0/amp-carousel-0.1.js:16:326)
    at S.push.f.f.buildCallback (https://cdn.ampproject.org/rtv/011494446565961/v0/amp-carousel-0.1.js:11:465)
    at HTMLElement.Zf.b.build (https://cdn.ampproject.org/shadow-v0.js:156:514)
va @ log.js:467
f.createError @ log.js:239
wf.getAmpDoc @ ampdoc-impl.js:153
Zf.b.connectedCallback @ custom-element.js:947
(anonymous) @ slidescroll.js:184
push.f.f.buildSlides @ slidescroll.js:178
push.f.f.buildCarousel @ base-slides.js:51
push.f.f.buildCallback @ base-carousel.js:45
Zf.b.build @ custom-element.js:718
f.build @ resource.js:290
mh @ resources-impl.js:552
qh @ resources-impl.js:511
f.upgraded @ resources-impl.js:611
Zf.b.rc @ custom-element.js:656
Zf.b.ze @ custom-element.js:1037
Zf.b.connectedCallback @ custom-element.js:975
i @ shell.js:232
(anonymous) @ shell.js:102
custom-element.js:1049 Uncaught TypeError: Cannot read property 'remove' of null
    at HTMLElement.Zf.b.disconnectedCallback (https://cdn.ampproject.org/shadow-v0.js:168:21)
    at https://cdn.ampproject.org/rtv/011494446565961/v0/amp-carousel-0.1.js:21:318
    at Array.forEach (native)
    at S.push.f.f.buildSlides (https://cdn.ampproject.org/rtv/011494446565961/v0/amp-carousel-0.1.js:21:142)
    at S.push.f.f.buildCarousel (https://cdn.ampproject.org/rtv/011494446565961/v0/amp-carousel-0.1.js:16:326)
    at S.push.f.f.buildCallback (https://cdn.ampproject.org/rtv/011494446565961/v0/amp-carousel-0.1.js:11:465)
    at HTMLElement.Zf.b.build (https://cdn.ampproject.org/shadow-v0.js:156:514)
    at ch.f.build (https://cdn.ampproject.org/shadow-v0.js:234:151)
    at mh (https://cdn.ampproject.org/shadow-v0.js:255:244)
    at qh (https://cdn.ampproject.org/shadow-v0.js:254:460)`

**Comment by choumx** [comment]
Looks like the same issue as https://github.com/choumx/amp-pwa/issues/10.

**Comment by andreban** [comment]
I'm testing locally, and it seems to be related to `type="slides"`, so this breaks:

```
  <amp-carousel height="300" type="slides">
    <amp-img 
      src="/articles/img/bird_cropped.png" 
      width="400"
      height="300"
      alt="Alt">
    </amp-img>

    <amp-img
      src="/articles/img/bird_cropped.png" 
      width="400"
      height="300"
      alt="Alt">
    </amp-img>
  </amp-carousel>
```

but this works:
```
  <amp-carousel height="300" type="carousel">
    <amp-img 
      src="/articles/img/bird_cropped.png" 
      width="400"
      height="300"
      alt="Alt">
    </amp-img>

    <amp-img
      src="/articles/img/bird_cropped.png" 
      width="400"
      height="300"
      alt="Alt">
    </amp-img>
  </amp-carousel>
```

Will try to share my test somewhere.

**Comment by andreban** [comment]
Using Chrome 58.0.3029.110

To reproduce:
1. Navigate to: https://amp-pwa-carousel.firebaseapp.com/
2. Navigate to any of the 2 links, no errors will be show on the console. 
3. Click on the blue header to return to the main page (back button not setup properly)
4. Navigate to the second link. 

The 2nd link, uses `type=carousel` and never breaks.

**Comment by choumx** [comment]
This is weird. 

`connectedCallback` is invoked for `amp-img` descendants of `amp-carousel[type="slides"]` immediately after [this line](https://github.com/ampproject/amphtml/blob/e562037b71b77b5ce2bff5a99e073fd4d0fd5688/extensions/amp-carousel/0.1/slidescroll.js#L184). This is surprising since the parent (`slideWrapper`) is clearly not connected.

In fact, the full dance caused by `appendChild` is `connectedCallback` -> `disconnectedCallback` -> `connectedCallback`. Happens on Chrome and Safari. Perhaps I'm misreading the [HTML spec](https://html.spec.whatwg.org/multipage/infrastructure.html#becomes-connected).

I've tested a fix that makes sure that `slideWrapper` is actually connected and it appears to work, though the reason why those callbacks are invoked in the first place still eludes me.
