### ISSUE TITLE
amp-form XHR test is flaky 

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#9358]
```
...................................
Chrome 58.0.3029 (Linux 0.0.0)  shadow ampdoc  amp-form   XHR   AMP-Redirect-To should redirect on error and header is set FAILED
	AssertionError: expected 0 to equal 1
	    at /tmp/0d63eb9846d3beddb9e442e31c71c7cb.browserify:73241:38 <- /home/travis/build/ampproject/amphtml/extensions/amp-form/0.1/test/test-amp-form.js:1560:37
	    at <anonymous>
```

https://travis-ci.org/ampproject/amphtml/builds/232622496?utm_source=github_status&utm_medium=notification

**Comment by aghassemi** [comment]
reopening, didn't do it. still happening:

```
............................................................
Chrome 45.0.2454 (Linux 0.0.0) AmpForm Integration   Submit xhr-GET should submit and render success FAILED
	AssertionError: expected 0 to equal 1
	    at /tmp/2a902269a2ad3ffacb4951546a4a8607.browserify:3095:36 <- /home/travis/build/ampproject/amphtml/extensions/amp-form/0.1/test/integration/test-integration-form.js:226:35
..
Chrome 45.0.2454 (Linux 0.0.0): Executed 126 of 175 (1 FAILED) (skipped 49) (28.649 secs / 20.504 secs)
.......................................................................
Safari 9.1.2 (Mac OS X 10.11.6): Executed 106 of 175 (skipped 69) SUCCESS (33.156 secs / 31.987 secs)
................................................................................
............................................................................
Edge 14.14393.0 (Windows 10 0.0.0): Executed 119 of 175 (skipped 56) SUCCESS (47.299 secs / 32.748 secs)
................................................................................
........................
Chrome Mobile 44.0.2403 (Android 6.0.0) AmpForm Integration   Submit xhr-GET should submit and render success FAILED
	AssertionError: expected 0 to equal 1
	    at /tmp/2a902269a2ad3ffacb4951546a4a8607.browserify:3095:36 <- /home/travis/build/ampproject/amphtml/extensions/amp-form/0.1/test/integration/test-integration-form.js:226:35
..
Chrome Mobile 44.0.2403 (Android 6.0.0): Executed 114 of 175 (1 FAILED) (skipped 61) (21.741 secs / 11.112 secs)
```
