### ISSUE TITLE
"gulp clean" is broken

### ISSUE THREAD

**Issue by rsimha-amp** [ampproject/amphtml#9522]
```
rsimha@bobdylan (master):~/src/amphtml$ gulp clean
module.js:472
    throw err;
    ^

Error: Cannot find module 'file-reader'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/google/home/rsimha/src/amphtml/build-system/tasks/runtime-test.js:22:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/google/home/rsimha/src/amphtml/build-system/tasks/index.js:33:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/google/home/rsimha/src/amphtml/gulpfile.js:40:1)
    at Module._compile (module.js:571:32)
rsimha@bobdylan (master):~/src/amphtml$ 

```

**Comment by lannka** [comment]
you need to do `npm i`

**Comment by rsimha-amp** [comment]
Interesting. Yes, `npm i` fixed it. Was that documented somewhere?

**Comment by choumx** [comment]
It's a common error that happens when a new package dependency is added.

**Comment by lannka** [comment]
oh ye, it came to me yesterday, so i knew it :-)
