### ISSUE TITLE
Error on running gulp

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#970]
I haven't see anything that doesn't work, though :)

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8000
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at Function.app.listen (/Users/malteubl/ws/amp/node_modules/connect/lib/proto.js:188:24)
    at Object.<anonymous> (/Users/malteubl/ws/amp/build-system/server.js:51:5)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
```

Probably related to demo serving.

CC @jaboc83

**Comment by cramforce** [comment]
Never mind. Was on the wrong machine :)

**Comment by kamijha** [comment]
```
PS C:\xampp\htdocs\AMPJavaScript> gulp
[21:36:08] Using gulpfile C:\xampp\htdocs\AMPJavaScript\gulpfile.js
[21:36:08] Starting 'update-packages'...
[21:36:09] All packages in node_modules are up to date.
[21:36:09] Patched node_modules/web-animations-js/web-animations.install.js
[21:36:09] Finished 'update-packages' after 761 ms
[21:36:09] Starting 'watch'...
[21:36:09] Running watch. Press Ctrl + C to cancel...
[21:36:09] Building the runtime for local testing with the prod AMP config.
[21:36:09] ⤷ Use --config={canary|prod} with your gulp watch command to specify which config to apply.
[21:36:09] Building all AMP extensions.
[21:36:09] ⤷ Use --noextensions to skip building extensions.
[21:36:09] ⤷ Use --extensions=amp-foo,amp-bar to choose which extensions to build.
[21:36:09] ⤷ Use --extensions=minimal_set to build just the extensions needed to load article.amp.html.
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: spawn sh ENOENT
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
PS C:\xampp\htdocs\AMPJavaScript> gulp
[21:45:32] Using gulpfile C:\xampp\htdocs\AMPJavaScript\gulpfile.js
[21:45:32] Starting 'update-packages'...
[21:45:33] All packages in node_modules are up to date.
[21:45:33] Finished 'update-packages' after 911 ms
[21:45:33] Starting 'watch'...
[21:45:33] Running watch. Press Ctrl + C to cancel...
[21:45:33] Building the runtime for local testing with the prod AMP config.
[21:45:33] ⤷ Use --config={canary|prod} with your gulp watch command to specify which config to apply.
[21:45:33] Building all AMP extensions.
[21:45:33] ⤷ Use --noextensions to skip building extensions.
[21:45:33] ⤷ Use --extensions=amp-foo,amp-bar to choose which extensions to build.
[21:45:33] ⤷ Use --extensions=minimal_set to build just the extensions needed to load article.amp.html.
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: spawn sh ENOENT
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
PS C:\xampp\htdocs\AMPJavaScript>
```

Not sure why this is occurring, i just followed this doc: https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md#one-time-setup

**Comment by SeanC-Nimble** [comment]
For anyone who is interested:
Issue was caused by /build-system/exec.js
method `execScriptAsync` was trying to spawn 'sh' however im using windows.
So changed from

`
exports.execScriptAsync = function(script, options) {
 childProcess.spawn('sh', [ '-c', script], options);
};
`
to 

`
exports.execScriptAsync = function(script, options) {
  let sh = 'sh';
  let shFlag = '-c';

  if (process.platform === 'win32') {
    sh = 'cmd';
    shFlag = '/c';
  } 

  return childProcess.spawn(sh, [shFlag, script], options);
};
`
