### ISSUE TITLE
Flaky integration test amp-form

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#9907]
https://travis-ci.org/ampproject/amphtml/jobs/242641942

```
Chrome 45.0.2454 (Linux 0.0.0) AmpForm Integration   Submit xhr-POST should submit and render success FAILED
	Error: Timeout waiting for render finished
	    at poll (/home/travis/build/ampproject/amphtml/testing/iframe.js:413:17 <- /tmp/1cdfdf8c28006aa7b83f2c72cb85513d.browserify:55427:18)
Chrome 45.0.2454 (Linux 0.0.0) AmpForm Integration   Submit xhr-POST should submit and render error FAILED
	Error: Timeout waiting for render finished
	    at poll (/home/travis/build/ampproject/amphtml/testing/iframe.js:413:17 <- /tmp/1cdfdf8c28006aa7b83f2c72cb85513d.browserify:55427:18)
Chrome 45.0.2454 (Linux 0.0.0) AmpForm Integration   Submit xhr-GET should submit and render success FAILED
	Error: Timeout waiting for render finished
	    at poll (/home/travis/build/ampproject/amphtml/testing/iframe.js:413:17 <- /tmp/1cdfdf8c28006aa7b83f2c72cb85513d.browserify:55427:18)
Chrome 45.0.2454 (Linux 0.0.0) AmpForm Integration   Submit xhr-GET should submit and render error FAILED
	Error: Timeout waiting for render finished
	    at poll (/home/travis/build/ampproject/amphtml/testing/iframe.js:413:17 <- /tmp/1cdfdf8c28006aa7b83f2c72cb85513d.browserify:55427:18)

**Comment by muxin** [comment]
Duplicate of https://github.com/ampproject/amphtml/issues/10187
